window.activedef={
  "AssassinsTalisman": {
    "BattleUse": "S_AssassinsTalisman",
    "Charge": 2,
    "ChargeBattleNum": 2,
    "Description": "可以给无法行动的敌人使用，目标的下一次所受伤害增加 30%。",
    "FieldUse": "",
    "Itemclass": "Rare",
    "KeyID": "AssassinsTalisman",
    "Lock": 0,
    "Name": "暗杀者符咒",
    "NoDrop": 0,
    "Special": 0,
    "Target": null,
    "active_battle": true,
    "active_field": 0,
    "image": "Assassin's Card"
  },
  "BlankCard": {
    "BattleUse": "S_BlankCard",
    "Charge": 1,
    "ChargeBattleNum": 3,
    "Description": "将手中的第 4 个技能费用变成 0。",
    "FieldUse": "",
    "Itemclass": "Rare",
    "KeyID": "BlankCard",
    "Lock": 0,
    "Name": "第 4 张卡片",
    "NoDrop": 0,
    "Special": 0,
    "Target": null,
    "active_battle": true,
    "active_field": 0,
    "image": "4thCard"
  },
  "DivineSword": {
    "BattleUse": "S_DivineSword",
    "Charge": 2,
    "ChargeBattleNum": 1,
    "Description": "所有友军的每 1 层增益给敌人造成 5 点伤害。",
    "FieldUse": "",
    "Itemclass": "Rare",
    "KeyID": "DivineSword",
    "Lock": 0,
    "Name": "护士的大剑",
    "NoDrop": 0,
    "Special": 0,
    "Target": null,
    "active_battle": true,
    "active_field": 0,
    "image": "Nurse's GreatSword"
  },
  "GoldenCoin": {
    "BattleUse": "S_GoldenCoin",
    "Charge": 2,
    "ChargeBattleNum": 2,
    "Description": "本回合获得 1 点法力值。",
    "FieldUse": "",
    "Itemclass": "Rare",
    "KeyID": "GoldenCoin",
    "Lock": 0,
    "Name": "黄金硬币",
    "NoDrop": 0,
    "Special": 0,
    "Target": null,
    "active_battle": true,
    "active_field": 0,
    "image": "Golden Coin"
  },
  "LucysNecklace": {
    "BattleUse": "S_LucysNecklace",
    "Charge": 1,
    "ChargeBattleNum": 0,
    "Description": "立即解除友军无法战斗状态。\n 在营地内充能 1 次。\n <Hard>无法充能。</Hard>",
    "FieldUse": "LucysNecklace",
    "Itemclass": "Rare",
    "KeyID": "LucysNecklace",
    "Lock": false,
    "Name": "露西的项链",
    "NoDrop": true,
    "Special": true,
    "Target": "deathally",
    "active_battle": false,
    "active_field": true,
    "image": "LucyNeck"
  },
  "LucysNecklace2": {
    "BattleUse": "S_LucysNecklace2",
    "Charge": 2,
    "ChargeBattleNum": 0,
    "Description": "立即解除友军无法战斗状态。\n 在营地内充能 1 次。\n <Hard>无法充能。</Hard>",
    "FieldUse": "LucysNecklace2",
    "Itemclass": "Rare",
    "KeyID": "LucysNecklace2",
    "Lock": false,
    "Name": "露西的项链",
    "NoDrop": true,
    "Special": true,
    "Target": "deathally",
    "active_battle": false,
    "active_field": true,
    "image": "Lucyneck1"
  },
  "LucysNecklace3": {
    "BattleUse": "S_LucysNecklace3",
    "Charge": 2,
    "ChargeBattleNum": 0,
    "Description": "立即解除友军无法战斗状态。\n 在营地内充能 1 次。\n <Hard>无法充能。</Hard>",
    "FieldUse": "LucysNecklace3",
    "Itemclass": "Unique",
    "KeyID": "LucysNecklace3",
    "Lock": false,
    "Name": "露西的项链",
    "NoDrop": true,
    "Special": true,
    "Target": "deathally",
    "active_battle": false,
    "active_field": true,
    "image": "Lucyneck2"
  },
  "LucysNecklace4": {
    "BattleUse": "S_LucysNecklace3",
    "Charge": 3,
    "ChargeBattleNum": 0,
    "Description": "立即解除友军无法战斗状态。\n 在营地内充能 1 次。\n <Hard>无法充能。</Hard>",
    "FieldUse": "LucysNecklace4",
    "Itemclass": "Legendary",
    "KeyID": "LucysNecklace4",
    "Lock": false,
    "Name": "露西的项链",
    "NoDrop": true,
    "Special": true,
    "Target": "deathally",
    "active_battle": false,
    "active_field": true,
    "image": "Lucyneck3"
  },
  "LunchBox": {
    "BattleUse": "S_LunchBox",
    "Charge": 1,
    "ChargeBattleNum": 3,
    "Description": "超额恢复所有友军 5 点体力值。",
    "FieldUse": "",
    "Itemclass": "Rare",
    "KeyID": "LunchBox",
    "Lock": 0,
    "Name": "便当",
    "NoDrop": 0,
    "Special": 0,
    "Target": "Misc",
    "active_battle": true,
    "active_field": 0,
    "image": "Lunch Box"
  },
  "MagicCard": {
    "BattleUse": "S_MagicCard",
    "Charge": 2,
    "ChargeBattleNum": 2,
    "Description": "抽取 1 个技能。",
    "FieldUse": "",
    "Itemclass": "Rare",
    "KeyID": "MagicCard",
    "Lock": 0,
    "Name": "魔法卡片",
    "NoDrop": 0,
    "Special": 0,
    "Target": null,
    "active_battle": true,
    "active_field": 0,
    "image": "Trick Card"
  },
  "Megaphone": {
    "BattleUse": "S_Megaphone",
    "Charge": 1,
    "ChargeBattleNum": 2,
    "Description": "改变所选敌人的嘲讽状态。",
    "FieldUse": "",
    "Itemclass": "Rare",
    "KeyID": "Megaphone",
    "Lock": 0,
    "Name": "恼人的扩音器",
    "NoDrop": 0,
    "Special": 0,
    "Target": null,
    "active_battle": true,
    "active_field": 0,
    "image": "Annoying Speaker"
  },
  "PotLid": {
    "BattleUse": "S_PotLid",
    "Charge": 2,
    "ChargeBattleNum": 2,
    "Description": "赋予目标 8 点保护罩。",
    "FieldUse": "",
    "Itemclass": "Rare",
    "KeyID": "PotLid",
    "Lock": 0,
    "Name": "锅盖",
    "NoDrop": 0,
    "Special": 0,
    "Target": null,
    "active_battle": true,
    "active_field": 0,
    "image": "Pot Lid"
  },
  "ShadowPriest_Thurible": {
    "BattleUse": "S_ShadowPriest_Thurible",
    "Charge": 2,
    "ChargeBattleNum": 0,
    "Description": "恢复友军 &a（攻击力 35% + 5）点体力值。",
    "FieldUse": "ShadowPriest_Thurible",
    "Itemclass": "Unique",
    "KeyID": "ShadowPriest_Thurible",
    "Lock": false,
    "Name": "灵魂香炉",
    "NoDrop": true,
    "Special": true,
    "Target": "ally",
    "active_battle": true,
    "active_field": false,
    "image": "ShadowPriestActive"
  },
  "Vaccine": {
    "BattleUse": "S_Vaccine",
    "Charge": 1,
    "ChargeBattleNum": 2,
    "Description": "对目标造成 5 点痛苦伤害，并解除所有减益。",
    "FieldUse": "",
    "Itemclass": "Rare",
    "KeyID": "Vaccine",
    "Lock": 0,
    "Name": "疫苗注射器",
    "NoDrop": 0,
    "Special": 0,
    "Target": null,
    "active_battle": true,
    "active_field": 0,
    "image": "Vaccine Syringe"
  },
  "Whetstone": {
    "BattleUse": "S_Whetstone",
    "Charge": 2,
    "ChargeBattleNum": 2,
    "Description": "下一个出手的费用小于 2 的技能暴击率增加100%。",
    "FieldUse": "",
    "Itemclass": "Rare",
    "KeyID": "Whetstone",
    "Lock": 0,
    "Name": "磨刀石",
    "NoDrop": 0,
    "Special": 0,
    "Target": null,
    "active_battle": true,
    "active_field": 0,
    "image": "Hone"
  }
}