audio_root = "audio/";
audio = [
    "StoryBGM_1_Loop.mp3",
    "Challenge.mp3",
    "Main.mp3",
    "Campfire.mp3",
    "Story_3_Abyss_loop.mp3",
    "Memory Lane.mp3",
    "Sir Dorchi.mp3",
    "Dystopia (Loop).mp3",
    "OutBreak.mp3",
    "Chrono Ark intro.mp3",
    "Opposition.mp3",
    "ReStart.mp3",
    "Virtual Emotions.mp3",
    "StoryBGM_0.mp3",
    "Pheonix Theme.mp3",
    "Ark Sight.mp3",
    "CA_Battle01.mp3",
    "There's No Way (Loop).mp3",
    "Camp Ambi.mp3",
    "Changed Intro.mp3",
    "There's No Way (Intro).mp3",
    "Clock Tower.mp3",
    "Chrono Ark normal.mp3",
    "Chrono Ark ex.mp3",
    "StoryBGM_2.mp3",
    "CA_Field01_2.mp3",
    "bangjoo_side_ambience.mp3",
    "Ark System Ambi Loop.mp3",
    "bangjoo_intro.mp3",
    "bangjoo_loop.mp3",
    "bangjoo_side_loop.mp3",
];