const carddef = [{
        "AutoDelete": 0,
        "Basic": false,
        "Category": "LucySkill",
        "Counting": 0,
        "Description": "抽取 2 个技能，并给抽取的技能添加幻影剑增益。\n 若阿扎尔处于无法战斗的状态，则不添加幻影剑增益。",
        "Disposable": false,
        "Effect_Self": "null",
        "Effect_Target": "null",
        "EnemyPreview": false,
        "EnemySkillSpeed": 0,
        "Except": false,
        "Fatal": false,
        "HealSkill": false,
        "IgnoreTaunt": false,
        "KeyID": "S_Azar_8_LucyDraw",
        "Lock": false,
        "LucyPartyDraw": "Azar",
        "NODOD": false,
        "Name": "幻影分裂",
        "NoBasicSkill": false,
        "NoDrop": false,
        "NotChuck": false,
        "NotCount": false,
        "PlusKeyWords": [],
        "PlusSkillView": "",
        "PlusViewBuffList": [],
        "Rare": false,
        "SKillExtendedItem": [],
        "SkillExtended": [
            "Extended_Azar_8"
        ],
        "SpecialUnlock": false,
        "Target": "Misc",
        "Track": false,
        "UnknownTarget": false,
        "UseAp": 1,
        "User": "LucyDraw",
        "ViewBuff": false,
        "image": "Azar_8.png"
    },
    {
        "AutoDelete": 0,
        "Basic": false,
        "Category": "LucySkill",
        "Counting": 0,
        "Description": "",
        "Disposable": true,
        "Effect_Self": "null",
        "Effect_Target": "SE_DorchiX_Lucy_T",
        "EnemyPreview": false,
        "EnemySkillSpeed": 0,
        "Except": false,
        "Fatal": false,
        "HealSkill": false,
        "IgnoreTaunt": false,
        "KeyID": "SE_DorchiX_Lucy_T",
        "Lock": false,
        "LucyPartyDraw": "",
        "NODOD": false,
        "Name": "保护舞动的草叶",
        "NoBasicSkill": false,
        "NoDrop": true,
        "NotChuck": true,
        "NotCount": true,
        "PlusKeyWords": [],
        "PlusSkillView": "",
        "PlusViewBuffList": [],
        "Rare": false,
        "SKillExtendedItem": [],
        "SkillExtended": [],
        "SpecialUnlock": false,
        "Target": "all_ally",
        "Track": false,
        "UnknownTarget": false,
        "UseAp": 0,
        "User": "Lucy",
        "ViewBuff": false,
        "image": "DorchiX.png"
    },
    {
        "AutoDelete": 0,
        "Basic": false,
        "Category": "LucySkill",
        "Counting": 0,
        "Description": "从牌库中优先抽取2个攻击技能，该技能的费用减少1点。",
        "Disposable": false,
        "Effect_Self": "null",
        "Effect_Target": "null",
        "EnemyPreview": false,
        "EnemySkillSpeed": 0,
        "Except": false,
        "Fatal": false,
        "HealSkill": false,
        "IgnoreTaunt": false,
        "KeyID": "S_Hein_12_LucyD",
        "Lock": false,
        "LucyPartyDraw": "Hein",
        "NODOD": false,
        "Name": "磨刀",
        "NoBasicSkill": false,
        "NoDrop": false,
        "NotChuck": false,
        "NotCount": false,
        "PlusKeyWords": [],
        "PlusSkillView": "",
        "PlusViewBuffList": [],
        "Rare": false,
        "SKillExtendedItem": [],
        "SkillExtended": [
            "S_Hein_12_LucyD"
        ],
        "SpecialUnlock": false,
        "Target": "Misc",
        "Track": false,
        "UnknownTarget": false,
        "UseAp": 1,
        "User": "LucyDraw",
        "ViewBuff": true,
        "image": "Hein_12.png"
    },
    {
        "AutoDelete": 0,
        "Basic": false,
        "Category": "LucySkill",
        "Counting": 0,
        "Description": "从牌库中抽取 2 个技能，并解除所选友军的随机 1 个减益。",
        "Disposable": false,
        "Effect_Self": "null",
        "Effect_Target": "SE_Joey_9_LucyD_T",
        "EnemyPreview": false,
        "EnemySkillSpeed": 0,
        "Except": false,
        "Fatal": false,
        "HealSkill": false,
        "IgnoreTaunt": false,
        "KeyID": "S_Joey_9_LucyD",
        "Lock": false,
        "LucyPartyDraw": "Joey",
        "NODOD": false,
        "Name": "草莓味药丸",
        "NoBasicSkill": false,
        "NoDrop": false,
        "NotChuck": false,
        "NotCount": false,
        "PlusKeyWords": [],
        "PlusSkillView": "",
        "PlusViewBuffList": [],
        "Rare": false,
        "SKillExtendedItem": [],
        "SkillExtended": [
            "Extended_Joey_9"
        ],
        "SpecialUnlock": false,
        "Target": "ally",
        "Track": false,
        "UnknownTarget": false,
        "UseAp": 0,
        "User": "LucyDraw",
        "ViewBuff": true,
        "image": "Joey_9.png"
    },
    {
        "AutoDelete": 1,
        "Basic": false,
        "Category": "LucySkill",
        "Counting": 0,
        "Description": "可使用&a次\n 破坏所有领地内的超·幻影剑。\n 此技能无法被赋予超·幻影剑。\n 回合开始时，若手中没有此技能，则抽取此技能。",
        "Disposable": false,
        "Effect_Self": "null",
        "Effect_Target": "SE_LBossFirst_LucySwordremove_T",
        "EnemyPreview": false,
        "EnemySkillSpeed": 0,
        "Except": false,
        "Fatal": false,
        "HealSkill": false,
        "IgnoreTaunt": true,
        "KeyID": "S_LBossFirst_LucySwordremove",
        "Lock": false,
        "LucyPartyDraw": "",
        "NODOD": false,
        "Name": "摧毁幻影剑",
        "NoBasicSkill": false,
        "NoDrop": false,
        "NotChuck": true,
        "NotCount": true,
        "PlusKeyWords": [],
        "PlusSkillView": "",
        "PlusViewBuffList": [],
        "Rare": false,
        "SKillExtendedItem": [],
        "SkillExtended": [
            "S_LBossFirst_LucySwordremove"
        ],
        "SpecialUnlock": false,
        "Target": "Misc",
        "Track": false,
        "UnknownTarget": false,
        "UseAp": 0,
        "User": "LucyBoss",
        "ViewBuff": false,
        "image": "LBoss_1.png"
    },
    {
        "AutoDelete": 0,
        "Basic": false,
        "Category": "LucySkill",
        "Counting": 99,
        "Description": "露西与阿扎尔展开决斗！",
        "Disposable": false,
        "Effect_Self": "null",
        "Effect_Target": "SE_Null",
        "EnemyPreview": false,
        "EnemySkillSpeed": 0,
        "Except": true,
        "Fatal": false,
        "HealSkill": false,
        "IgnoreTaunt": true,
        "KeyID": "S_LbossFirst_NextPhase_Lucy",
        "Lock": false,
        "LucyPartyDraw": "",
        "NODOD": true,
        "Name": "露西的决斗！",
        "NoBasicSkill": false,
        "NoDrop": false,
        "NotChuck": false,
        "NotCount": true,
        "PlusKeyWords": [],
        "PlusSkillView": "",
        "PlusViewBuffList": [],
        "Rare": false,
        "SKillExtendedItem": [],
        "SkillExtended": [
            "S_LbossFirst_NextPhase_Lucy"
        ],
        "SpecialUnlock": false,
        "Target": "enemy",
        "Track": false,
        "UnknownTarget": false,
        "UseAp": 2,
        "User": "LucyBoss",
        "ViewBuff": false,
        "image": "LBoss_2.png"
    },
    {
        "AutoDelete": 0,
        "Basic": false,
        "Category": "LucySkill",
        "Counting": 99,
        "Description": "破坏所有超·幻影剑。\n 露西与阿扎尔展开决斗！",
        "Disposable": false,
        "Effect_Self": "null",
        "Effect_Target": "SE_Null",
        "EnemyPreview": false,
        "EnemySkillSpeed": 0,
        "Except": true,
        "Fatal": false,
        "HealSkill": false,
        "IgnoreTaunt": true,
        "KeyID": "S_LbossFirst_NextPhase_LucyP2",
        "Lock": false,
        "LucyPartyDraw": "",
        "NODOD": true,
        "Name": "露西的决斗！",
        "NoBasicSkill": false,
        "NoDrop": false,
        "NotChuck": false,
        "NotCount": true,
        "PlusKeyWords": [],
        "PlusSkillView": "",
        "PlusViewBuffList": [],
        "Rare": false,
        "SKillExtendedItem": [],
        "SkillExtended": [
            "S_LbossFirst_NextPhase_Lucy"
        ],
        "SpecialUnlock": false,
        "Target": "enemy",
        "Track": false,
        "UnknownTarget": false,
        "UseAp": 2,
        "User": "LucyBoss",
        "ViewBuff": false,
        "image": "LBoss_3.png"
    },
    {
        "AutoDelete": 1,
        "Basic": false,
        "Category": "LucySkill",
        "Counting": 0,
        "Description": "使用时无任何效果。\n 抽取此技能时，再额外抽取一个技能。\n 当此技能被握在手中时，主动释放手中技能的友军获得 3 点痛苦伤害。",
        "Disposable": false,
        "Effect_Self": "null",
        "Effect_Target": "SE_Null",
        "EnemyPreview": false,
        "EnemySkillSpeed": 0,
        "Except": false,
        "Fatal": false,
        "HealSkill": false,
        "IgnoreTaunt": false,
        "KeyID": "S_LucyCurse_Banana",
        "Lock": false,
        "LucyPartyDraw": "",
        "NODOD": false,
        "Name": "香蕉皮",
        "NoBasicSkill": false,
        "NoDrop": false,
        "NotChuck": true,
        "NotCount": false,
        "PlusKeyWords": [],
        "PlusSkillView": "",
        "PlusViewBuffList": [],
        "Rare": false,
        "SKillExtendedItem": [],
        "SkillExtended": [
            "S_LucyCurse_Banana"
        ],
        "SpecialUnlock": false,
        "Target": "Misc",
        "Track": false,
        "UnknownTarget": false,
        "UseAp": 2,
        "User": "LucyCurse",
        "ViewBuff": false,
        "image": "Curse_Banana.png"
    },
    {
        "AutoDelete": 0,
        "Basic": false,
        "Category": "LucySkill",
        "Counting": 0,
        "Description": "无法使用\n 抽取此技能时，再额外抽取一个技能。\n 当此技能被握在手中时，从手中主动释放 8 个技能后回合<b>强制结束</b>，并丢弃此技能。",
        "Disposable": false,
        "Effect_Self": "null",
        "Effect_Target": "SE_Null",
        "EnemyPreview": false,
        "EnemySkillSpeed": 0,
        "Except": false,
        "Fatal": false,
        "HealSkill": false,
        "IgnoreTaunt": false,
        "KeyID": "S_LucyCurse_CursedClock",
        "Lock": false,
        "LucyPartyDraw": "",
        "NODOD": false,
        "Name": "受诅咒的表",
        "NoBasicSkill": false,
        "NoDrop": false,
        "NotChuck": true,
        "NotCount": false,
        "PlusKeyWords": [],
        "PlusSkillView": "",
        "PlusViewBuffList": [],
        "Rare": false,
        "SKillExtendedItem": [],
        "SkillExtended": [
            "S_LucyCurse_CursedClock"
        ],
        "SpecialUnlock": false,
        "Target": "Misc",
        "Track": false,
        "UnknownTarget": false,
        "UseAp": 0,
        "User": "LucyCurse",
        "ViewBuff": false,
        "image": "Curse_CursedClock.png"
    },
    {
        "AutoDelete": 0,
        "Basic": false,
        "Category": "LucySkill",
        "Counting": 0,
        "Description": "无法使用",
        "Disposable": false,
        "Effect_Self": "null",
        "Effect_Target": "SE_Null",
        "EnemyPreview": false,
        "EnemySkillSpeed": 0,
        "Except": false,
        "Fatal": false,
        "HealSkill": false,
        "IgnoreTaunt": false,
        "KeyID": "S_LucyCurse_Heavy",
        "Lock": false,
        "LucyPartyDraw": "",
        "NODOD": false,
        "Name": "沉重的背包",
        "NoBasicSkill": false,
        "NoDrop": false,
        "NotChuck": false,
        "NotCount": false,
        "PlusKeyWords": [],
        "PlusSkillView": "",
        "PlusViewBuffList": [],
        "Rare": false,
        "SKillExtendedItem": [],
        "SkillExtended": [
            "S_LucyCurse_Heavy"
        ],
        "SpecialUnlock": false,
        "Target": "Misc",
        "Track": false,
        "UnknownTarget": false,
        "UseAp": 5,
        "User": "LucyCurse",
        "ViewBuff": false,
        "image": "Curse_Heavy.png"
    },
    {
        "AutoDelete": 0,
        "Basic": false,
        "Category": "LucySkill",
        "Counting": 0,
        "Description": "战斗开始时，将此技能放在牌库的最上方。",
        "Disposable": false,
        "Effect_Self": "null",
        "Effect_Target": "SE_Null",
        "EnemyPreview": false,
        "EnemySkillSpeed": 0,
        "Except": true,
        "Fatal": false,
        "HealSkill": false,
        "IgnoreTaunt": false,
        "KeyID": "S_LucyCurse_Late",
        "Lock": false,
        "LucyPartyDraw": "",
        "NODOD": false,
        "Name": "迟来的应对",
        "NoBasicSkill": false,
        "NoDrop": false,
        "NotChuck": false,
        "NotCount": true,
        "PlusKeyWords": [],
        "PlusSkillView": "",
        "PlusViewBuffList": [],
        "Rare": false,
        "SKillExtendedItem": [],
        "SkillExtended": [
            "S_LucyCurse_Late"
        ],
        "SpecialUnlock": false,
        "Target": "Misc",
        "Track": false,
        "UnknownTarget": false,
        "UseAp": 0,
        "User": "LucyCurse",
        "ViewBuff": false,
        "image": "Curse_Late.png"
    },
    {
        "AutoDelete": 0,
        "Basic": false,
        "Category": "null",
        "Counting": 0,
        "Description": "增加1次等待次数。\n 在等待后立即使用时暴击率增加100%。",
        "Disposable": false,
        "Effect_Self": "null",
        "Effect_Target": "SE_LucyC_0_T",
        "EnemyPreview": false,
        "EnemySkillSpeed": 0,
        "Except": false,
        "Fatal": false,
        "HealSkill": false,
        "IgnoreTaunt": true,
        "KeyID": "S_LucyC_0",
        "Lock": false,
        "LucyPartyDraw": "",
        "NODOD": false,
        "Name": "时差攻击",
        "NoBasicSkill": false,
        "NoDrop": false,
        "NotChuck": false,
        "NotCount": false,
        "PlusKeyWords": [],
        "PlusSkillView": "",
        "PlusViewBuffList": [],
        "Rare": false,
        "SKillExtendedItem": [],
        "SkillExtended": [
            "S_LucyC_0"
        ],
        "SpecialUnlock": false,
        "Target": "enemy",
        "Track": false,
        "UnknownTarget": false,
        "UseAp": 1,
        "User": "LucyC",
        "ViewBuff": false,
        "image": "0.png"
    },
    {
        "AutoDelete": 0,
        "Basic": false,
        "Category": "null",
        "Counting": 0,
        "Description": "",
        "Disposable": false,
        "Effect_Self": "null",
        "Effect_Target": "SE_LucyC_1_S",
        "EnemyPreview": false,
        "EnemySkillSpeed": 0,
        "Except": false,
        "Fatal": false,
        "HealSkill": false,
        "IgnoreTaunt": false,
        "KeyID": "S_LucyC_1",
        "Lock": false,
        "LucyPartyDraw": "",
        "NODOD": false,
        "Name": "迅捷位移",
        "NoBasicSkill": true,
        "NoDrop": false,
        "NotChuck": false,
        "NotCount": false,
        "PlusKeyWords": [],
        "PlusSkillView": "",
        "PlusViewBuffList": [],
        "Rare": false,
        "SKillExtendedItem": [],
        "SkillExtended": [],
        "SpecialUnlock": false,
        "Target": "self",
        "Track": false,
        "UnknownTarget": false,
        "UseAp": 1,
        "User": "LucyC",
        "ViewBuff": false,
        "image": "1.png"
    },
    {
        "AutoDelete": 0,
        "Basic": false,
        "Category": "null",
        "Counting": 0,
        "Description": "恢复与“位移”技能费用相等的法力值。",
        "Disposable": false,
        "Effect_Self": "null",
        "Effect_Target": "SE_LucyC_2_T",
        "EnemyPreview": false,
        "EnemySkillSpeed": 0,
        "Except": false,
        "Fatal": false,
        "HealSkill": false,
        "IgnoreTaunt": true,
        "KeyID": "S_LucyC_2",
        "Lock": false,
        "LucyPartyDraw": "",
        "NODOD": false,
        "Name": "急速位移",
        "NoBasicSkill": false,
        "NoDrop": false,
        "NotChuck": false,
        "NotCount": true,
        "PlusKeyWords": [],
        "PlusSkillView": "",
        "PlusViewBuffList": [],
        "Rare": false,
        "SKillExtendedItem": [],
        "SkillExtended": [
            "S_LucyC_2"
        ],
        "SpecialUnlock": false,
        "Target": "enemy",
        "Track": false,
        "UnknownTarget": false,
        "UseAp": 1,
        "User": "LucyC",
        "ViewBuff": false,
        "image": "2.png"
    },
    {
        "AutoDelete": 0,
        "Basic": false,
        "Category": "null",
        "Counting": 0,
        "Description": "本回合内每一次等待额外造成&a点伤害 。",
        "Disposable": false,
        "Effect_Self": "null",
        "Effect_Target": "SE_LucyC_3_T",
        "EnemyPreview": false,
        "EnemySkillSpeed": 0,
        "Except": false,
        "Fatal": false,
        "HealSkill": false,
        "IgnoreTaunt": true,
        "KeyID": "S_LucyC_3",
        "Lock": false,
        "LucyPartyDraw": "",
        "NODOD": false,
        "Name": "集中一击",
        "NoBasicSkill": false,
        "NoDrop": false,
        "NotChuck": false,
        "NotCount": false,
        "PlusKeyWords": [],
        "PlusSkillView": "",
        "PlusViewBuffList": [],
        "Rare": false,
        "SKillExtendedItem": [],
        "SkillExtended": [
            "S_LucyC_3"
        ],
        "SpecialUnlock": false,
        "Target": "enemy",
        "Track": false,
        "UnknownTarget": false,
        "UseAp": 2,
        "User": "LucyC",
        "ViewBuff": false,
        "image": "3.png"
    },
    {
        "AutoDelete": 0,
        "Basic": false,
        "Category": "null",
        "Counting": 0,
        "Description": "",
        "Disposable": true,
        "Effect_Self": "SE_LucyC_4_S",
        "Effect_Target": "SE_LucyC_4_T",
        "EnemyPreview": false,
        "EnemySkillSpeed": 0,
        "Except": false,
        "Fatal": false,
        "HealSkill": false,
        "IgnoreTaunt": false,
        "KeyID": "S_LucyC_4",
        "Lock": false,
        "LucyPartyDraw": "",
        "NODOD": false,
        "Name": "放风筝",
        "NoBasicSkill": false,
        "NoDrop": false,
        "NotChuck": false,
        "NotCount": true,
        "PlusKeyWords": [],
        "PlusSkillView": "",
        "PlusViewBuffList": [],
        "Rare": false,
        "SKillExtendedItem": [],
        "SkillExtended": [],
        "SpecialUnlock": false,
        "Target": "enemy",
        "Track": false,
        "UnknownTarget": false,
        "UseAp": 2,
        "User": "LucyC",
        "ViewBuff": false,
        "image": "4.png"
    },
    {
        "AutoDelete": 2,
        "Basic": false,
        "Category": "null",
        "Counting": 0,
        "Description": "此技能可在眩晕状态下释放。\n 解除自身所有减益，根据‘位移’技能的费用(&a)触发以下效果。\n 等待次数+&a，恢复&a点法力值，抽取&a个技能。",
        "Disposable": true,
        "Effect_Self": "null",
        "Effect_Target": "SE_LucyC_5_S",
        "EnemyPreview": false,
        "EnemySkillSpeed": 0,
        "Except": false,
        "Fatal": false,
        "HealSkill": false,
        "IgnoreTaunt": false,
        "KeyID": "S_LucyC_5",
        "Lock": false,
        "LucyPartyDraw": "",
        "NODOD": false,
        "Name": "深呼吸",
        "NoBasicSkill": true,
        "NoDrop": false,
        "NotChuck": false,
        "NotCount": true,
        "PlusKeyWords": [],
        "PlusSkillView": "",
        "PlusViewBuffList": [],
        "Rare": false,
        "SKillExtendedItem": [],
        "SkillExtended": [
            "S_LucyC_5"
        ],
        "SpecialUnlock": false,
        "Target": "self",
        "Track": false,
        "UnknownTarget": false,
        "UseAp": 0,
        "User": "LucyC",
        "ViewBuff": false,
        "image": "5.png"
    },
    {
        "AutoDelete": 0,
        "Basic": false,
        "Category": "null",
        "Counting": 0,
        "Description": "当手中没有‘位移’技能时触发\n 给手中最上面的技能赋予‘灵巧位移'，并优先抽取牌库中其他友军的技能。\n ‘灵巧位移’相当于‘位移’增益。",
        "Disposable": false,
        "Effect_Self": "null",
        "Effect_Target": "SE_LucyC_6_T",
        "EnemyPreview": false,
        "EnemySkillSpeed": 0,
        "Except": false,
        "Fatal": false,
        "HealSkill": false,
        "IgnoreTaunt": true,
        "KeyID": "S_LucyC_6",
        "Lock": false,
        "LucyPartyDraw": "",
        "NODOD": false,
        "Name": "混乱打击",
        "NoBasicSkill": false,
        "NoDrop": false,
        "NotChuck": false,
        "NotCount": false,
        "PlusKeyWords": [],
        "PlusSkillView": "",
        "PlusViewBuffList": [],
        "Rare": false,
        "SKillExtendedItem": [],
        "SkillExtended": [
            "S_LucyC_6"
        ],
        "SpecialUnlock": false,
        "Target": "enemy",
        "Track": false,
        "UnknownTarget": false,
        "UseAp": 1,
        "User": "LucyC",
        "ViewBuff": false,
        "image": "6.png"
    },
    {
        "AutoDelete": 0,
        "Basic": false,
        "Category": "null",
        "Counting": 0,
        "Description": "使用此技能击杀敌人时恢复3点法力值。",
        "Disposable": false,
        "Effect_Self": "null",
        "Effect_Target": "SE_LucyC_7_T",
        "EnemyPreview": false,
        "EnemySkillSpeed": 0,
        "Except": false,
        "Fatal": false,
        "HealSkill": false,
        "IgnoreTaunt": true,
        "KeyID": "S_LucyC_7",
        "Lock": false,
        "LucyPartyDraw": "",
        "NODOD": false,
        "Name": "乘胜追击",
        "NoBasicSkill": true,
        "NoDrop": false,
        "NotChuck": false,
        "NotCount": false,
        "PlusKeyWords": [],
        "PlusSkillView": "",
        "PlusViewBuffList": [],
        "Rare": false,
        "SKillExtendedItem": [],
        "SkillExtended": [
            "S_LucyC_7"
        ],
        "SpecialUnlock": false,
        "Target": "enemy",
        "Track": true,
        "UnknownTarget": false,
        "UseAp": 2,
        "User": "LucyC",
        "ViewBuff": false,
        "image": "7.png"
    },
    {
        "AutoDelete": 0,
        "Basic": false,
        "Category": "LucySkill",
        "Counting": 0,
        "Description": "抽取 2 个技能。\n 若手中没有技能则抽取 3 个。",
        "Disposable": false,
        "Effect_Self": "null",
        "Effect_Target": "SE_LucyD_0_T",
        "EnemyPreview": false,
        "EnemySkillSpeed": 0,
        "Except": false,
        "Fatal": false,
        "HealSkill": false,
        "IgnoreTaunt": false,
        "KeyID": "S_LucyD_0",
        "Lock": false,
        "LucyPartyDraw": "",
        "NODOD": false,
        "Name": "抽牌",
        "NoBasicSkill": false,
        "NoDrop": false,
        "NotChuck": false,
        "NotCount": false,
        "PlusKeyWords": [],
        "PlusSkillView": "",
        "PlusViewBuffList": [],
        "Rare": false,
        "SKillExtendedItem": [],
        "SkillExtended": [
            "Extended_LucyD_0"
        ],
        "SpecialUnlock": false,
        "Target": "Misc",
        "Track": false,
        "UnknownTarget": false,
        "UseAp": 0,
        "User": "LucyDraw",
        "ViewBuff": true,
        "image": "D0.png"
    },
    {
        "AutoDelete": 0,
        "Basic": false,
        "Category": "LucySkill",
        "Counting": 0,
        "Description": "立即抽取一个技能，在 3 回合期间增加 1 次抽牌次数。\n （包括立即抽牌在内共 3 次）",
        "Disposable": false,
        "Effect_Self": "null",
        "Effect_Target": "SE_LucyD_1_T",
        "EnemyPreview": false,
        "EnemySkillSpeed": 0,
        "Except": false,
        "Fatal": false,
        "HealSkill": false,
        "IgnoreTaunt": false,
        "KeyID": "S_LucyD_1",
        "Lock": false,
        "LucyPartyDraw": "",
        "NODOD": false,
        "Name": "连续抽牌",
        "NoBasicSkill": false,
        "NoDrop": false,
        "NotChuck": false,
        "NotCount": false,
        "PlusKeyWords": [],
        "PlusSkillView": "",
        "PlusViewBuffList": [],
        "Rare": false,
        "SKillExtendedItem": [],
        "SkillExtended": [
            "Extended_LucyD_1"
        ],
        "SpecialUnlock": false,
        "Target": "Misc",
        "Track": false,
        "UnknownTarget": false,
        "UseAp": 0,
        "User": "LucyDraw",
        "ViewBuff": true,
        "image": "D1.png"
    },
    {
        "AutoDelete": 0,
        "Basic": false,
        "Category": "LucySkill",
        "Counting": 0,
        "Description": "抽取与拥有剩余体力极限的友军数量相等的技能。",
        "Disposable": false,
        "Effect_Self": "null",
        "Effect_Target": "SE_LucyD_10_T",
        "EnemyPreview": false,
        "EnemySkillSpeed": 0,
        "Except": false,
        "Fatal": false,
        "HealSkill": false,
        "IgnoreTaunt": false,
        "KeyID": "S_LucyD_10",
        "Lock": true,
        "LucyPartyDraw": "",
        "NODOD": false,
        "Name": "克服危机",
        "NoBasicSkill": false,
        "NoDrop": false,
        "NotChuck": true,
        "NotCount": false,
        "PlusKeyWords": [],
        "PlusSkillView": "",
        "PlusViewBuffList": [],
        "Rare": false,
        "SKillExtendedItem": [],
        "SkillExtended": [
            "S_LucyD_10"
        ],
        "SpecialUnlock": false,
        "Target": "Misc",
        "Track": false,
        "UnknownTarget": false,
        "UseAp": 0,
        "User": "LucyDraw",
        "ViewBuff": true,
        "image": "D10.png"
    },
    {
        "AutoDelete": 0,
        "Basic": false,
        "Category": "LucySkill",
        "Counting": 0,
        "Description": "选择 - 从牌库中抽取2个想要的技能，放逐“翻滚”技能后，从牌库的随机2个技能中选择一个技能放逐。\n或抽取2个技能。",
        "Disposable": false,
        "Effect_Self": "null",
        "Effect_Target": "SE_Null",
        "EnemyPreview": false,
        "EnemySkillSpeed": 0,
        "Except": false,
        "Fatal": false,
        "HealSkill": false,
        "IgnoreTaunt": false,
        "KeyID": "S_LucyD_11",
        "Lock": true,
        "LucyPartyDraw": "",
        "NODOD": false,
        "Name": "翻滚",
        "NoBasicSkill": false,
        "NoDrop": false,
        "NotChuck": false,
        "NotCount": false,
        "PlusKeyWords": [],
        "PlusSkillView": "",
        "PlusViewBuffList": [],
        "Rare": false,
        "SKillExtendedItem": [],
        "SkillExtended": [
            "S_LucyD_11"
        ],
        "SpecialUnlock": true,
        "Target": "Misc",
        "Track": false,
        "UnknownTarget": false,
        "UseAp": 0,
        "User": "LucyDraw",
        "ViewBuff": false,
        "image": "D11.png"
    },
    {
        "AutoDelete": 0,
        "Basic": false,
        "Category": "null",
        "Counting": 0,
        "Description": "从牌库中抽取2个想要的技能，放逐“翻滚”技能后，从牌库的随机2个技能中选择一个技能放逐。",
        "Disposable": false,
        "Effect_Self": "null",
        "Effect_Target": "SE_Null",
        "EnemyPreview": false,
        "EnemySkillSpeed": 0,
        "Except": false,
        "Fatal": false,
        "HealSkill": false,
        "IgnoreTaunt": false,
        "KeyID": "S_LucyD_11_0",
        "Lock": false,
        "LucyPartyDraw": "",
        "NODOD": false,
        "Name": "翻滚",
        "NoBasicSkill": false,
        "NoDrop": false,
        "NotChuck": false,
        "NotCount": false,
        "PlusKeyWords": [],
        "PlusSkillView": "",
        "PlusViewBuffList": [],
        "Rare": false,
        "SKillExtendedItem": [],
        "SkillExtended": [],
        "SpecialUnlock": false,
        "Target": "Misc",
        "Track": false,
        "UnknownTarget": false,
        "UseAp": 0,
        "User": "LucyDraw",
        "ViewBuff": false,
        "image": "D11_L.png"
    },
    {
        "AutoDelete": 0,
        "Basic": false,
        "Category": "null",
        "Counting": 0,
        "Description": "抽取2个技能。",
        "Disposable": false,
        "Effect_Self": "null",
        "Effect_Target": "SE_Null",
        "EnemyPreview": false,
        "EnemySkillSpeed": 0,
        "Except": false,
        "Fatal": false,
        "HealSkill": false,
        "IgnoreTaunt": false,
        "KeyID": "S_LucyD_11_1",
        "Lock": false,
        "LucyPartyDraw": "",
        "NODOD": false,
        "Name": "缓慢翻滚",
        "NoBasicSkill": false,
        "NoDrop": false,
        "NotChuck": false,
        "NotCount": false,
        "PlusKeyWords": [],
        "PlusSkillView": "",
        "PlusViewBuffList": [],
        "Rare": false,
        "SKillExtendedItem": [],
        "SkillExtended": [],
        "SpecialUnlock": false,
        "Target": "Misc",
        "Track": false,
        "UnknownTarget": false,
        "UseAp": 0,
        "User": "LucyDraw",
        "ViewBuff": false,
        "image": "D11_R.png"
    },
    {
        "AutoDelete": 0,
        "Basic": false,
        "Category": "LucySkill",
        "Counting": 0,
        "Description": "抽取3个技能。\n将此技能握在手中时，如果释放了其它技能，则抽取2个技能。",
        "Disposable": false,
        "Effect_Self": "null",
        "Effect_Target": "null",
        "EnemyPreview": false,
        "EnemySkillSpeed": 0,
        "Except": false,
        "Fatal": false,
        "HealSkill": false,
        "IgnoreTaunt": false,
        "KeyID": "S_LucyD_12",
        "Lock": false,
        "LucyPartyDraw": "",
        "NODOD": false,
        "Name": "闪电抽牌",
        "NoBasicSkill": false,
        "NoDrop": false,
        "NotChuck": false,
        "NotCount": false,
        "PlusKeyWords": [],
        "PlusSkillView": "",
        "PlusViewBuffList": [],
        "Rare": false,
        "SKillExtendedItem": [],
        "SkillExtended": [
            "S_LucyD_12"
        ],
        "SpecialUnlock": false,
        "Target": "Misc",
        "Track": false,
        "UnknownTarget": false,
        "UseAp": 0,
        "User": "LucyDraw",
        "ViewBuff": false,
        "image": "D12.png"
    },
    {
        "AutoDelete": 0,
        "Basic": false,
        "Category": "LucySkill",
        "Counting": 0,
        "Description": "选择 - 抽取2个技能。\n或恢复2点法力值。",
        "Disposable": false,
        "Effect_Self": "null",
        "Effect_Target": "null",
        "EnemyPreview": false,
        "EnemySkillSpeed": 0,
        "Except": false,
        "Fatal": false,
        "HealSkill": false,
        "IgnoreTaunt": false,
        "KeyID": "S_LucyD_13",
        "Lock": false,
        "LucyPartyDraw": "",
        "NODOD": false,
        "Name": "零食",
        "NoBasicSkill": false,
        "NoDrop": false,
        "NotChuck": false,
        "NotCount": false,
        "PlusKeyWords": [],
        "PlusSkillView": "",
        "PlusViewBuffList": [],
        "Rare": false,
        "SKillExtendedItem": [],
        "SkillExtended": [
            "S_LucyD_13"
        ],
        "SpecialUnlock": false,
        "Target": "Misc",
        "Track": false,
        "UnknownTarget": false,
        "UseAp": 0,
        "User": "LucyDraw",
        "ViewBuff": false,
        "image": "D13.png"
    },
    {
        "AutoDelete": 0,
        "Basic": false,
        "Category": "null",
        "Counting": 0,
        "Description": "抽取2个技能。",
        "Disposable": false,
        "Effect_Self": "null",
        "Effect_Target": "null",
        "EnemyPreview": false,
        "EnemySkillSpeed": 0,
        "Except": false,
        "Fatal": false,
        "HealSkill": false,
        "IgnoreTaunt": false,
        "KeyID": "S_LucyD_13_0",
        "Lock": false,
        "LucyPartyDraw": "",
        "NODOD": false,
        "Name": "蛋包饭",
        "NoBasicSkill": false,
        "NoDrop": false,
        "NotChuck": false,
        "NotCount": false,
        "PlusKeyWords": [],
        "PlusSkillView": "",
        "PlusViewBuffList": [],
        "Rare": false,
        "SKillExtendedItem": [],
        "SkillExtended": [],
        "SpecialUnlock": false,
        "Target": "Misc",
        "Track": false,
        "UnknownTarget": false,
        "UseAp": 0,
        "User": "LucyDraw",
        "ViewBuff": false,
        "image": "D13_B.png"
    },
    {
        "AutoDelete": 0,
        "Basic": false,
        "Category": "null",
        "Counting": 0,
        "Description": "恢复2点法力值。",
        "Disposable": false,
        "Effect_Self": "null",
        "Effect_Target": "null",
        "EnemyPreview": false,
        "EnemySkillSpeed": 0,
        "Except": false,
        "Fatal": false,
        "HealSkill": false,
        "IgnoreTaunt": false,
        "KeyID": "S_LucyD_13_1",
        "Lock": false,
        "LucyPartyDraw": "",
        "NODOD": false,
        "Name": "香蕉牛奶",
        "NoBasicSkill": false,
        "NoDrop": false,
        "NotChuck": false,
        "NotCount": false,
        "PlusKeyWords": [],
        "PlusSkillView": "",
        "PlusViewBuffList": [],
        "Rare": false,
        "SKillExtendedItem": [],
        "SkillExtended": [],
        "SpecialUnlock": false,
        "Target": "Misc",
        "Track": false,
        "UnknownTarget": false,
        "UseAp": 0,
        "User": "LucyDraw",
        "ViewBuff": false,
        "image": "D13_O.png"
    },
    {
        "AutoDelete": 0,
        "Basic": false,
        "Category": "LucySkill",
        "Counting": 0,
        "Description": "抽取2个技能，并恢复2点法力值。\n下一回合开始时法力值减少2点。",
        "Disposable": false,
        "Effect_Self": "null",
        "Effect_Target": "null",
        "EnemyPreview": false,
        "EnemySkillSpeed": 0,
        "Except": false,
        "Fatal": false,
        "HealSkill": false,
        "IgnoreTaunt": false,
        "KeyID": "S_LucyD_14",
        "Lock": false,
        "LucyPartyDraw": "",
        "NODOD": false,
        "Name": "热身",
        "NoBasicSkill": false,
        "NoDrop": false,
        "NotChuck": false,
        "NotCount": false,
        "PlusKeyWords": [],
        "PlusSkillView": "",
        "PlusViewBuffList": [],
        "Rare": false,
        "SKillExtendedItem": [],
        "SkillExtended": [
            "S_LucyD_14"
        ],
        "SpecialUnlock": false,
        "Target": "Misc",
        "Track": false,
        "UnknownTarget": false,
        "UseAp": 0,
        "User": "LucyDraw",
        "ViewBuff": false,
        "image": "D14.png"
    },
    {
        "AutoDelete": 0,
        "Basic": false,
        "Category": "LucySkill",
        "Counting": 0,
        "Description": "抽取3个技能。\n抽取的技能附带一回合后弃牌。",
        "Disposable": false,
        "Effect_Self": "null",
        "Effect_Target": "null",
        "EnemyPreview": false,
        "EnemySkillSpeed": 0,
        "Except": false,
        "Fatal": false,
        "HealSkill": false,
        "IgnoreTaunt": false,
        "KeyID": "S_LucyD_15",
        "Lock": false,
        "LucyPartyDraw": "",
        "NODOD": false,
        "Name": "央求",
        "NoBasicSkill": false,
        "NoDrop": false,
        "NotChuck": false,
        "NotCount": false,
        "PlusKeyWords": [],
        "PlusSkillView": "",
        "PlusViewBuffList": [],
        "Rare": false,
        "SKillExtendedItem": [],
        "SkillExtended": [
            "S_LucyD_15"
        ],
        "SpecialUnlock": false,
        "Target": "Misc",
        "Track": false,
        "UnknownTarget": false,
        "UseAp": 0,
        "User": "LucyDraw",
        "ViewBuff": false,
        "image": "D15.png"
    },
    {
        "AutoDelete": 0,
        "Basic": false,
        "Category": "LucySkill",
        "Counting": 0,
        "Description": "查看牌库中最上面的3个技能，并抽取所选的技能。\n抽取的技能费用减少2点。",
        "Disposable": false,
        "Effect_Self": "null",
        "Effect_Target": "null",
        "EnemyPreview": false,
        "EnemySkillSpeed": 0,
        "Except": false,
        "Fatal": false,
        "HealSkill": false,
        "IgnoreTaunt": false,
        "KeyID": "S_LucyD_16",
        "Lock": false,
        "LucyPartyDraw": "",
        "NODOD": false,
        "Name": "深思熟虑",
        "NoBasicSkill": false,
        "NoDrop": false,
        "NotChuck": false,
        "NotCount": false,
        "PlusKeyWords": [],
        "PlusSkillView": "",
        "PlusViewBuffList": [],
        "Rare": false,
        "SKillExtendedItem": [],
        "SkillExtended": [
            "S_LucyD_16"
        ],
        "SpecialUnlock": false,
        "Target": "Misc",
        "Track": false,
        "UnknownTarget": false,
        "UseAp": 0,
        "User": "LucyDraw",
        "ViewBuff": false,
        "image": "D16.png"
    },
    {
        "AutoDelete": 0,
        "Basic": false,
        "Category": "LucySkill",
        "Counting": 0,
        "Description": "抽取 2 个技能，增加 2 次技能交换次数。",
        "Disposable": false,
        "Effect_Self": "null",
        "Effect_Target": "SE_LucyD_2_T",
        "EnemyPreview": false,
        "EnemySkillSpeed": 0,
        "Except": false,
        "Fatal": false,
        "HealSkill": false,
        "IgnoreTaunt": false,
        "KeyID": "S_LucyD_2",
        "Lock": false,
        "LucyPartyDraw": "",
        "NODOD": false,
        "Name": "重复利用",
        "NoBasicSkill": false,
        "NoDrop": false,
        "NotChuck": false,
        "NotCount": false,
        "PlusKeyWords": [],
        "PlusSkillView": "",
        "PlusViewBuffList": [],
        "Rare": false,
        "SKillExtendedItem": [],
        "SkillExtended": [
            "Extended_LucyD_2"
        ],
        "SpecialUnlock": false,
        "Target": "Misc",
        "Track": false,
        "UnknownTarget": false,
        "UseAp": 1,
        "User": "LucyDraw",
        "ViewBuff": true,
        "image": "D2.png"
    },
    {
        "AutoDelete": 0,
        "Basic": false,
        "Category": "LucySkill",
        "Counting": 0,
        "Description": "按顺序查看牌库中的技能，并选择其中 1 个技能抽取。",
        "Disposable": false,
        "Effect_Self": "null",
        "Effect_Target": "SE_LucyD_3_T",
        "EnemyPreview": false,
        "EnemySkillSpeed": 0,
        "Except": false,
        "Fatal": false,
        "HealSkill": false,
        "IgnoreTaunt": false,
        "KeyID": "S_LucyD_3",
        "Lock": false,
        "LucyPartyDraw": "",
        "NODOD": false,
        "Name": "找牌",
        "NoBasicSkill": false,
        "NoDrop": false,
        "NotChuck": false,
        "NotCount": true,
        "PlusKeyWords": [],
        "PlusSkillView": "",
        "PlusViewBuffList": [],
        "Rare": false,
        "SKillExtendedItem": [],
        "SkillExtended": [
            "Extended_LucyD_3"
        ],
        "SpecialUnlock": false,
        "Target": "Misc",
        "Track": false,
        "UnknownTarget": false,
        "UseAp": 0,
        "User": "LucyDraw",
        "ViewBuff": true,
        "image": "D3.png"
    },
    {
        "AutoDelete": 0,
        "Basic": false,
        "Category": "LucySkill",
        "Counting": 0,
        "Description": "丢弃手中最下面的一个技能，并抽取 3 个技能。",
        "Disposable": false,
        "Effect_Self": "null",
        "Effect_Target": "SE_LucyD_4_T",
        "EnemyPreview": false,
        "EnemySkillSpeed": 0,
        "Except": false,
        "Fatal": false,
        "HealSkill": false,
        "IgnoreTaunt": false,
        "KeyID": "S_LucyD_4",
        "Lock": false,
        "LucyPartyDraw": "",
        "NODOD": false,
        "Name": "急中生智",
        "NoBasicSkill": false,
        "NoDrop": false,
        "NotChuck": false,
        "NotCount": false,
        "PlusKeyWords": [],
        "PlusSkillView": "",
        "PlusViewBuffList": [],
        "Rare": false,
        "SKillExtendedItem": [],
        "SkillExtended": [
            "Extended_LucyD_4"
        ],
        "SpecialUnlock": false,
        "Target": "Misc",
        "Track": false,
        "UnknownTarget": false,
        "UseAp": 0,
        "User": "LucyDraw",
        "ViewBuff": true,
        "image": "D4.png"
    },
    {
        "AutoDelete": 0,
        "Basic": false,
        "Category": "LucySkill",
        "Counting": 1,
        "Description": "<b>释放两次</b>\n 从牌库中的 3 个技能中选择 1 个抽取。",
        "Disposable": false,
        "Effect_Self": "null",
        "Effect_Target": "SE_LucyD_5_T",
        "EnemyPreview": false,
        "EnemySkillSpeed": 0,
        "Except": false,
        "Fatal": false,
        "HealSkill": false,
        "IgnoreTaunt": false,
        "KeyID": "S_LucyD_5",
        "Lock": false,
        "LucyPartyDraw": "",
        "NODOD": false,
        "Name": "战术选择",
        "NoBasicSkill": false,
        "NoDrop": false,
        "NotChuck": false,
        "NotCount": false,
        "PlusKeyWords": [],
        "PlusSkillView": "",
        "PlusViewBuffList": [],
        "Rare": false,
        "SKillExtendedItem": [],
        "SkillExtended": [
            "Extended_LucyD_5"
        ],
        "SpecialUnlock": false,
        "Target": "Misc",
        "Track": false,
        "UnknownTarget": false,
        "UseAp": 0,
        "User": "LucyDraw",
        "ViewBuff": true,
        "image": "D5.png"
    },
    {
        "AutoDelete": 0,
        "Basic": false,
        "Category": "LucySkill",
        "Counting": 0,
        "Description": "抽取 3 个技能。\n 恢复目标的所有体力极限。",
        "Disposable": true,
        "Effect_Self": "null",
        "Effect_Target": "SE_LucyD_6_T",
        "EnemyPreview": false,
        "EnemySkillSpeed": 0,
        "Except": false,
        "Fatal": false,
        "HealSkill": false,
        "IgnoreTaunt": false,
        "KeyID": "S_LucyD_6",
        "Lock": true,
        "LucyPartyDraw": "",
        "NODOD": false,
        "Name": "一线光",
        "NoBasicSkill": false,
        "NoDrop": false,
        "NotChuck": false,
        "NotCount": true,
        "PlusKeyWords": [],
        "PlusSkillView": "",
        "PlusViewBuffList": [],
        "Rare": false,
        "SKillExtendedItem": [],
        "SkillExtended": [
            "Extended_Lucy_D_6"
        ],
        "SpecialUnlock": false,
        "Target": "ally",
        "Track": false,
        "UnknownTarget": false,
        "UseAp": 2,
        "User": "LucyDraw",
        "ViewBuff": true,
        "image": "D6.png"
    },
    {
        "AutoDelete": 0,
        "Basic": false,
        "Category": "LucySkill",
        "Counting": 0,
        "Description": "弃掉手中的所有技能，抽取 4 个技能。\n 手中每有一个不同的技能，此技能费用减少 1 点。",
        "Disposable": false,
        "Effect_Self": "null",
        "Effect_Target": "SE_LucyD_7_T",
        "EnemyPreview": false,
        "EnemySkillSpeed": 0,
        "Except": false,
        "Fatal": false,
        "HealSkill": false,
        "IgnoreTaunt": false,
        "KeyID": "S_LucyD_7",
        "Lock": true,
        "LucyPartyDraw": "",
        "NODOD": false,
        "Name": "重整旗鼓",
        "NoBasicSkill": false,
        "NoDrop": false,
        "NotChuck": false,
        "NotCount": false,
        "PlusKeyWords": [],
        "PlusSkillView": "",
        "PlusViewBuffList": [],
        "Rare": false,
        "SKillExtendedItem": [],
        "SkillExtended": [
            "Extended_Lucy_D_7"
        ],
        "SpecialUnlock": false,
        "Target": "Misc",
        "Track": false,
        "UnknownTarget": false,
        "UseAp": 3,
        "User": "LucyDraw",
        "ViewBuff": true,
        "image": "D7.png"
    },
    {
        "AutoDelete": 0,
        "Basic": false,
        "Category": "LucySkill",
        "Counting": 0,
        "Description": "优先抽取所选目标的 3 个技能 。\n 该技能每回合费用减少。",
        "Disposable": false,
        "Effect_Self": "null",
        "Effect_Target": "SE_LucyD_8_T",
        "EnemyPreview": false,
        "EnemySkillSpeed": 0,
        "Except": false,
        "Fatal": false,
        "HealSkill": false,
        "IgnoreTaunt": false,
        "KeyID": "S_LucyD_8",
        "Lock": true,
        "LucyPartyDraw": "",
        "NODOD": false,
        "Name": "扇风点火",
        "NoBasicSkill": false,
        "NoDrop": false,
        "NotChuck": false,
        "NotCount": false,
        "PlusKeyWords": [],
        "PlusSkillView": "",
        "PlusViewBuffList": [],
        "Rare": false,
        "SKillExtendedItem": [],
        "SkillExtended": [
            "Extended_Lucy_D_8"
        ],
        "SpecialUnlock": false,
        "Target": "ally",
        "Track": false,
        "UnknownTarget": false,
        "UseAp": 2,
        "User": "LucyDraw",
        "ViewBuff": true,
        "image": "D8.png"
    },
    {
        "AutoDelete": 0,
        "Basic": false,
        "Category": "LucySkill",
        "Counting": 0,
        "Description": "从牌库中选择 2 个技能拿到手中。",
        "Disposable": false,
        "Effect_Self": "null",
        "Effect_Target": "SE_LucyD_9_T",
        "EnemyPreview": false,
        "EnemySkillSpeed": 0,
        "Except": false,
        "Fatal": false,
        "HealSkill": false,
        "IgnoreTaunt": false,
        "KeyID": "S_LucyD_9",
        "Lock": true,
        "LucyPartyDraw": "",
        "NODOD": false,
        "Name": "寻找更多",
        "NoBasicSkill": false,
        "NoDrop": false,
        "NotChuck": false,
        "NotCount": false,
        "PlusKeyWords": [],
        "PlusSkillView": "",
        "PlusViewBuffList": [],
        "Rare": false,
        "SKillExtendedItem": [],
        "SkillExtended": [
            "Extended_LucyD_9"
        ],
        "SpecialUnlock": false,
        "Target": "Misc",
        "Track": false,
        "UnknownTarget": false,
        "UseAp": 2,
        "User": "LucyDraw",
        "ViewBuff": true,
        "image": "D9.png"
    },
    {
        "AutoDelete": 0,
        "Basic": false,
        "Category": "LucySkill",
        "Counting": 0,
        "Description": "所选技能获得迅速，且<b>本次战斗期间</b>该技能的费用减少 1 点。",
        "Disposable": true,
        "Effect_Self": "null",
        "Effect_Target": "null",
        "EnemyPreview": false,
        "EnemySkillSpeed": 0,
        "Except": false,
        "Fatal": false,
        "HealSkill": false,
        "IgnoreTaunt": false,
        "KeyID": "S_Lucy_0",
        "Lock": false,
        "LucyPartyDraw": "",
        "NODOD": false,
        "Name": "加速",
        "NoBasicSkill": false,
        "NoDrop": false,
        "NotChuck": false,
        "NotCount": true,
        "PlusKeyWords": [],
        "PlusSkillView": "",
        "PlusViewBuffList": [],
        "Rare": false,
        "SKillExtendedItem": [],
        "SkillExtended": [
            "Extended_Lucy_0"
        ],
        "SpecialUnlock": false,
        "Target": "skill",
        "Track": false,
        "UnknownTarget": false,
        "UseAp": 0,
        "User": "Lucy",
        "ViewBuff": true,
        "image": "0.png"
    },
    {
        "AutoDelete": 0,
        "Basic": false,
        "Category": "LucySkill",
        "Counting": 0,
        "Description": "随机生成所选友军的可使用技能，抽取至手牌补满，并附带放逐。",
        "Disposable": true,
        "Effect_Self": "null",
        "Effect_Target": "null",
        "EnemyPreview": false,
        "EnemySkillSpeed": 0,
        "Except": false,
        "Fatal": false,
        "HealSkill": false,
        "IgnoreTaunt": false,
        "KeyID": "S_Lucy_1",
        "Lock": false,
        "LucyPartyDraw": "",
        "NODOD": false,
        "Name": "潜能",
        "NoBasicSkill": false,
        "NoDrop": false,
        "NotChuck": false,
        "NotCount": true,
        "PlusKeyWords": [],
        "PlusSkillView": "",
        "PlusViewBuffList": [],
        "Rare": false,
        "SKillExtendedItem": [],
        "SkillExtended": [
            "Extended_Lucy_1"
        ],
        "SpecialUnlock": false,
        "Target": "ally",
        "Track": false,
        "UnknownTarget": false,
        "UseAp": 2,
        "User": "Lucy",
        "ViewBuff": true,
        "image": "1.png"
    },
    {
        "AutoDelete": 0,
        "Basic": false,
        "Category": "LucySkill",
        "Counting": 0,
        "Description": "本次战斗期间最大法力值增加。\n 每回合费用减少 1 点。",
        "Disposable": true,
        "Effect_Self": "null",
        "Effect_Target": "SE_Lucy_10_T",
        "EnemyPreview": false,
        "EnemySkillSpeed": 0,
        "Except": false,
        "Fatal": false,
        "HealSkill": false,
        "IgnoreTaunt": false,
        "KeyID": "S_Lucy_10",
        "Lock": false,
        "LucyPartyDraw": "",
        "NODOD": false,
        "Name": "增加最大法力值",
        "NoBasicSkill": false,
        "NoDrop": false,
        "NotChuck": false,
        "NotCount": true,
        "PlusKeyWords": [],
        "PlusSkillView": "",
        "PlusViewBuffList": [],
        "Rare": false,
        "SKillExtendedItem": [],
        "SkillExtended": [
            "Extended_Lucy_10"
        ],
        "SpecialUnlock": false,
        "Target": "Misc",
        "Track": false,
        "UnknownTarget": false,
        "UseAp": 1,
        "User": "Lucy",
        "ViewBuff": true,
        "image": "10.png"
    },
    {
        "AutoDelete": 0,
        "Basic": false,
        "Category": "LucySkill",
        "Counting": 0,
        "Description": "本次回合期间每当在<b>牌库</b>中抽取技能，恢复 1 点法力值。\n 抽取 1 个技能。",
        "Disposable": true,
        "Effect_Self": "null",
        "Effect_Target": "SE_Lucy_11_T",
        "EnemyPreview": false,
        "EnemySkillSpeed": 0,
        "Except": false,
        "Fatal": false,
        "HealSkill": false,
        "IgnoreTaunt": false,
        "KeyID": "S_Lucy_11",
        "Lock": true,
        "LucyPartyDraw": "",
        "NODOD": false,
        "Name": "魔法抽牌",
        "NoBasicSkill": false,
        "NoDrop": false,
        "NotChuck": false,
        "NotCount": false,
        "PlusKeyWords": [],
        "PlusSkillView": "",
        "PlusViewBuffList": [],
        "Rare": false,
        "SKillExtendedItem": [],
        "SkillExtended": [
            "Extended_Lucy_11"
        ],
        "SpecialUnlock": false,
        "Target": "Misc",
        "Track": false,
        "UnknownTarget": false,
        "UseAp": 2,
        "User": "Lucy",
        "ViewBuff": true,
        "image": "11.png"
    },
    {
        "AutoDelete": 0,
        "Basic": false,
        "Category": "LucySkill",
        "Counting": 0,
        "Description": "抽取 5 个技能。\n 将抽取的技能释放给随机目标并放逐。",
        "Disposable": true,
        "Effect_Self": "null",
        "Effect_Target": "SE_Lucy_12_T",
        "EnemyPreview": false,
        "EnemySkillSpeed": 0,
        "Except": false,
        "Fatal": false,
        "HealSkill": false,
        "IgnoreTaunt": false,
        "KeyID": "S_Lucy_12",
        "Lock": true,
        "LucyPartyDraw": "",
        "NODOD": false,
        "Name": "突破极限",
        "NoBasicSkill": false,
        "NoDrop": false,
        "NotChuck": false,
        "NotCount": false,
        "PlusKeyWords": [],
        "PlusSkillView": "",
        "PlusViewBuffList": [],
        "Rare": false,
        "SKillExtendedItem": [],
        "SkillExtended": [
            "Extended_Lucy_12"
        ],
        "SpecialUnlock": false,
        "Target": "Misc",
        "Track": false,
        "UnknownTarget": false,
        "UseAp": 2,
        "User": "Lucy",
        "ViewBuff": true,
        "image": "12.png"
    },
    {
        "AutoDelete": 0,
        "Basic": false,
        "Category": "LucySkill",
        "Counting": 0,
        "Description": "重复释放上个回合中<b>从手中释放的所有技能</b>。\n （露西技能除外）",
        "Disposable": true,
        "Effect_Self": "null",
        "Effect_Target": "SE_Lucy_13_T",
        "EnemyPreview": false,
        "EnemySkillSpeed": 0,
        "Except": false,
        "Fatal": false,
        "HealSkill": false,
        "IgnoreTaunt": false,
        "KeyID": "S_Lucy_13",
        "Lock": true,
        "LucyPartyDraw": "",
        "NODOD": false,
        "Name": "重现",
        "NoBasicSkill": false,
        "NoDrop": false,
        "NotChuck": false,
        "NotCount": false,
        "PlusKeyWords": [],
        "PlusSkillView": "",
        "PlusViewBuffList": [],
        "Rare": false,
        "SKillExtendedItem": [],
        "SkillExtended": [
            "Extended_Lucy_13"
        ],
        "SpecialUnlock": false,
        "Target": "Misc",
        "Track": false,
        "UnknownTarget": false,
        "UseAp": 3,
        "User": "Lucy",
        "ViewBuff": true,
        "image": "13.png"
    },
    {
        "AutoDelete": 0,
        "Basic": false,
        "Category": "LucySkill",
        "Counting": 0,
        "Description": "所有友军下一次固定能力的费用减少 1 点，并附带迅速、基本功。",
        "Disposable": true,
        "Effect_Self": "null",
        "Effect_Target": "SE_Lucy_14_T",
        "EnemyPreview": false,
        "EnemySkillSpeed": 0,
        "Except": false,
        "Fatal": false,
        "HealSkill": false,
        "IgnoreTaunt": false,
        "KeyID": "S_Lucy_14",
        "Lock": true,
        "LucyPartyDraw": "",
        "NODOD": false,
        "Name": "战旗",
        "NoBasicSkill": false,
        "NoDrop": false,
        "NotChuck": false,
        "NotCount": true,
        "PlusKeyWords": [],
        "PlusSkillView": "",
        "PlusViewBuffList": [],
        "Rare": false,
        "SKillExtendedItem": [],
        "SkillExtended": [
            "Extended_Lucy_14"
        ],
        "SpecialUnlock": false,
        "Target": "Misc",
        "Track": false,
        "UnknownTarget": false,
        "UseAp": 0,
        "User": "Lucy",
        "ViewBuff": true,
        "image": "14.png"
    },
    {
        "AutoDelete": 7,
        "Basic": false,
        "Category": "LucySkill",
        "Counting": 0,
        "Description": "握在手中时，该技能下面的所有技能获得迅速。\n 每当释放下面一个技能时，X 回合后丢弃减少 1 回合。",
        "Disposable": false,
        "Effect_Self": "null",
        "Effect_Target": "SE_Lucy_15_T",
        "EnemyPreview": false,
        "EnemySkillSpeed": 0,
        "Except": false,
        "Fatal": false,
        "HealSkill": false,
        "IgnoreTaunt": false,
        "KeyID": "S_Lucy_15",
        "Lock": true,
        "LucyPartyDraw": "",
        "NODOD": false,
        "Name": "加速魔法阵",
        "NoBasicSkill": false,
        "NoDrop": false,
        "NotChuck": false,
        "NotCount": true,
        "PlusKeyWords": [],
        "PlusSkillView": "",
        "PlusViewBuffList": [],
        "Rare": false,
        "SKillExtendedItem": [],
        "SkillExtended": [
            "S_Lucy_15"
        ],
        "SpecialUnlock": false,
        "Target": "Misc",
        "Track": false,
        "UnknownTarget": false,
        "UseAp": 0,
        "User": "Lucy",
        "ViewBuff": true,
        "image": "15.png"
    },
    {
        "AutoDelete": 0,
        "Basic": false,
        "Category": "LucySkill",
        "Counting": 0,
        "Description": "释放手中所有费用最高的技能。",
        "Disposable": true,
        "Effect_Self": "null",
        "Effect_Target": "SE_Lucy_16_T",
        "EnemyPreview": false,
        "EnemySkillSpeed": 0,
        "Except": false,
        "Fatal": false,
        "HealSkill": false,
        "IgnoreTaunt": false,
        "KeyID": "S_Lucy_16",
        "Lock": true,
        "LucyPartyDraw": "",
        "NODOD": false,
        "Name": "总攻！",
        "NoBasicSkill": false,
        "NoDrop": false,
        "NotChuck": false,
        "NotCount": true,
        "PlusKeyWords": [],
        "PlusSkillView": "",
        "PlusViewBuffList": [],
        "Rare": false,
        "SKillExtendedItem": [],
        "SkillExtended": [
            "S_Lucy_16"
        ],
        "SpecialUnlock": false,
        "Target": "Misc",
        "Track": false,
        "UnknownTarget": false,
        "UseAp": 2,
        "User": "Lucy",
        "ViewBuff": true,
        "image": "16.png"
    },
    {
        "AutoDelete": 0,
        "Basic": false,
        "Category": "LucySkill",
        "Counting": 0,
        "Description": "在本回合中每当队员受到伤害时，对所有敌人造成 &a 点伤害。\n （每经过一个区域增加 1 点伤害）\n 若受到友军造成的伤害，则抽取技能。",
        "Disposable": true,
        "Effect_Self": "null",
        "Effect_Target": "SE_Lucy_17_T",
        "EnemyPreview": false,
        "EnemySkillSpeed": 0,
        "Except": false,
        "Fatal": false,
        "HealSkill": false,
        "IgnoreTaunt": false,
        "KeyID": "S_Lucy_17",
        "Lock": true,
        "LucyPartyDraw": "",
        "NODOD": false,
        "Name": "暗黑形态",
        "NoBasicSkill": false,
        "NoDrop": false,
        "NotChuck": false,
        "NotCount": true,
        "PlusKeyWords": [],
        "PlusSkillView": "",
        "PlusViewBuffList": [],
        "Rare": false,
        "SKillExtendedItem": [],
        "SkillExtended": [
            "S_Lucy_17"
        ],
        "SpecialUnlock": false,
        "Target": "Misc",
        "Track": false,
        "UnknownTarget": false,
        "UseAp": 0,
        "User": "Lucy",
        "ViewBuff": true,
        "image": "17.png"
    },
    {
        "AutoDelete": 0,
        "Basic": false,
        "Category": "LucySkill",
        "Counting": 0,
        "Description": "在牌库中选择队员的技能。\n 生成 2 个该技能。",
        "Disposable": true,
        "Effect_Self": "null",
        "Effect_Target": "SE_Lucy_18_T",
        "EnemyPreview": false,
        "EnemySkillSpeed": 0,
        "Except": false,
        "Fatal": false,
        "HealSkill": false,
        "IgnoreTaunt": false,
        "KeyID": "S_Lucy_18",
        "Lock": true,
        "LucyPartyDraw": "",
        "NODOD": false,
        "Name": "帽子戏法",
        "NoBasicSkill": false,
        "NoDrop": false,
        "NotChuck": false,
        "NotCount": false,
        "PlusKeyWords": [],
        "PlusSkillView": "",
        "PlusViewBuffList": [],
        "Rare": false,
        "SKillExtendedItem": [],
        "SkillExtended": [
            "S_Lucy_18"
        ],
        "SpecialUnlock": false,
        "Target": "Misc",
        "Track": false,
        "UnknownTarget": false,
        "UseAp": 2,
        "User": "Lucy",
        "ViewBuff": true,
        "image": "18.png"
    },
    {
        "AutoDelete": 0,
        "Basic": false,
        "Category": "LucySkill",
        "Counting": 0,
        "Description": "抽取技能，直到手中有 6 个技能为止。",
        "Disposable": false,
        "Effect_Self": "null",
        "Effect_Target": "SE_Null",
        "EnemyPreview": false,
        "EnemySkillSpeed": 0,
        "Except": false,
        "Fatal": false,
        "HealSkill": false,
        "IgnoreTaunt": false,
        "KeyID": "S_Lucy_19",
        "Lock": false,
        "LucyPartyDraw": "",
        "NODOD": false,
        "Name": "耍赖",
        "NoBasicSkill": false,
        "NoDrop": false,
        "NotChuck": false,
        "NotCount": true,
        "PlusKeyWords": [],
        "PlusSkillView": "",
        "PlusViewBuffList": [],
        "Rare": false,
        "SKillExtendedItem": [],
        "SkillExtended": [
            "S_Lucy_19"
        ],
        "SpecialUnlock": false,
        "Target": "Misc",
        "Track": false,
        "UnknownTarget": false,
        "UseAp": 1,
        "User": "Lucy",
        "ViewBuff": false,
        "image": "19.png"
    },
    {
        "AutoDelete": 0,
        "Basic": false,
        "Category": "LucySkill",
        "Counting": 0,
        "Description": "展示选择目标的随机 3 个专属技能，生成其中 1 个技能并附带放逐。",
        "Disposable": false,
        "Effect_Self": "null",
        "Effect_Target": "SE_Lucy_2_T",
        "EnemyPreview": false,
        "EnemySkillSpeed": 0,
        "Except": false,
        "Fatal": false,
        "HealSkill": false,
        "IgnoreTaunt": false,
        "KeyID": "S_Lucy_2",
        "Lock": false,
        "LucyPartyDraw": "",
        "NODOD": false,
        "Name": "应援",
        "NoBasicSkill": false,
        "NoDrop": false,
        "NotChuck": false,
        "NotCount": true,
        "PlusKeyWords": [],
        "PlusSkillView": "",
        "PlusViewBuffList": [],
        "Rare": false,
        "SKillExtendedItem": [],
        "SkillExtended": [
            "Extended_Lucy_2"
        ],
        "SpecialUnlock": false,
        "Target": "ally",
        "Track": false,
        "UnknownTarget": false,
        "UseAp": 0,
        "User": "Lucy",
        "ViewBuff": true,
        "image": "2.png"
    },
    {
        "AutoDelete": 0,
        "Basic": false,
        "Category": "LucySkill",
        "Counting": 0,
        "Description": "对目标造成相当于所持金币数 2%(&a) 的伤害，并失去相等数量的金币。",
        "Disposable": false,
        "Effect_Self": "null",
        "Effect_Target": "SE_Null",
        "EnemyPreview": false,
        "EnemySkillSpeed": 0,
        "Except": false,
        "Fatal": false,
        "HealSkill": false,
        "IgnoreTaunt": false,
        "KeyID": "S_Lucy_20",
        "Lock": true,
        "LucyPartyDraw": "",
        "NODOD": false,
        "Name": "金钱的力量",
        "NoBasicSkill": false,
        "NoDrop": false,
        "NotChuck": false,
        "NotCount": true,
        "PlusKeyWords": [],
        "PlusSkillView": "",
        "PlusViewBuffList": [],
        "Rare": false,
        "SKillExtendedItem": [],
        "SkillExtended": [
            "S_Lucy_20"
        ],
        "SpecialUnlock": false,
        "Target": "enemy",
        "Track": false,
        "UnknownTarget": false,
        "UseAp": 2,
        "User": "Lucy",
        "ViewBuff": false,
        "image": "20.png"
    },
    {
        "AutoDelete": 0,
        "Basic": false,
        "Category": "LucySkill",
        "Counting": 0,
        "Description": "从手中的队员技能中选择一个未强化的技能。\n 从2个强化效果中选择1个获得，该强化效果持续至本次战斗结束。\n 从牌库中抽取1个技能。",
        "Disposable": true,
        "Effect_Self": "null",
        "Effect_Target": "SE_Null",
        "EnemyPreview": false,
        "EnemySkillSpeed": 0,
        "Except": false,
        "Fatal": false,
        "HealSkill": false,
        "IgnoreTaunt": false,
        "KeyID": "S_Lucy_21",
        "Lock": false,
        "LucyPartyDraw": "",
        "NODOD": false,
        "Name": "注入魔法",
        "NoBasicSkill": false,
        "NoDrop": false,
        "NotChuck": false,
        "NotCount": true,
        "PlusKeyWords": [],
        "PlusSkillView": "",
        "PlusViewBuffList": [],
        "Rare": false,
        "SKillExtendedItem": [],
        "SkillExtended": [
            "S_Lucy_21"
        ],
        "SpecialUnlock": false,
        "Target": "skill",
        "Track": false,
        "UnknownTarget": false,
        "UseAp": 0,
        "User": "Lucy",
        "ViewBuff": false,
        "image": "21.png"
    },
    {
        "AutoDelete": 0,
        "Basic": false,
        "Category": "LucySkill",
        "Counting": 0,
        "Description": "给手中所有队员的技能赋予随机强化效果，并持续之本次战斗结束。\n 已经强化的技能无法再次强化。\n 从牌库中抽取1个技能。",
        "Disposable": true,
        "Effect_Self": "null",
        "Effect_Target": "SE_Null",
        "EnemyPreview": false,
        "EnemySkillSpeed": 0,
        "Except": false,
        "Fatal": false,
        "HealSkill": false,
        "IgnoreTaunt": false,
        "KeyID": "S_Lucy_22",
        "Lock": true,
        "LucyPartyDraw": "",
        "NODOD": false,
        "Name": "注入范围魔法",
        "NoBasicSkill": false,
        "NoDrop": false,
        "NotChuck": false,
        "NotCount": true,
        "PlusKeyWords": [],
        "PlusSkillView": "",
        "PlusViewBuffList": [],
        "Rare": false,
        "SKillExtendedItem": [],
        "SkillExtended": [
            "S_Lucy_22"
        ],
        "SpecialUnlock": false,
        "Target": "Misc",
        "Track": false,
        "UnknownTarget": false,
        "UseAp": 1,
        "User": "Lucy",
        "ViewBuff": false,
        "image": "22.png"
    },
    {
        "AutoDelete": 0,
        "Basic": false,
        "Category": "LucySkill",
        "Counting": 0,
        "Description": "抽取一个技能。\n 查看牌库后，将想要的技能放在牌库的最上方。\n 将该技能拿到手中时费用变成 0。",
        "Disposable": false,
        "Effect_Self": "null",
        "Effect_Target": "SE_Null",
        "EnemyPreview": false,
        "EnemySkillSpeed": 0,
        "Except": false,
        "Fatal": false,
        "HealSkill": false,
        "IgnoreTaunt": false,
        "KeyID": "S_Lucy_23",
        "Lock": true,
        "LucyPartyDraw": "",
        "NODOD": false,
        "Name": "提议",
        "NoBasicSkill": false,
        "NoDrop": false,
        "NotChuck": false,
        "NotCount": true,
        "PlusKeyWords": [],
        "PlusSkillView": "",
        "PlusViewBuffList": [],
        "Rare": false,
        "SKillExtendedItem": [],
        "SkillExtended": [
            "S_Lucy_23"
        ],
        "SpecialUnlock": false,
        "Target": "Misc",
        "Track": false,
        "UnknownTarget": false,
        "UseAp": 1,
        "User": "Lucy",
        "ViewBuff": false,
        "image": "23.png"
    },
    {
        "AutoDelete": 0,
        "Basic": false,
        "Category": "LucySkill",
        "Counting": 0,
        "Description": "丢弃选择的技能。\n 选择 - 根据该技能的费用，抽取相等数量的技能。\n 或根据该技能的费用，恢复相等数量的法力值。\n 最高上限为 4 点。",
        "Disposable": false,
        "Effect_Self": "null",
        "Effect_Target": "SE_Null",
        "EnemyPreview": false,
        "EnemySkillSpeed": 0,
        "Except": false,
        "Fatal": false,
        "HealSkill": false,
        "IgnoreTaunt": false,
        "KeyID": "S_Lucy_24",
        "Lock": true,
        "LucyPartyDraw": "",
        "NODOD": false,
        "Name": "战术改变",
        "NoBasicSkill": false,
        "NoDrop": false,
        "NotChuck": false,
        "NotCount": false,
        "PlusKeyWords": [],
        "PlusSkillView": "",
        "PlusViewBuffList": [],
        "Rare": false,
        "SKillExtendedItem": [],
        "SkillExtended": [
            "S_Lucy_24"
        ],
        "SpecialUnlock": false,
        "Target": "skill",
        "Track": false,
        "UnknownTarget": false,
        "UseAp": 0,
        "User": "Lucy",
        "ViewBuff": false,
        "image": "24.png"
    },
    {
        "AutoDelete": 0,
        "Basic": false,
        "Category": "null",
        "Counting": 0,
        "Description": "抽取 &a 个技能。",
        "Disposable": false,
        "Effect_Self": "null",
        "Effect_Target": "SE_Null",
        "EnemyPreview": false,
        "EnemySkillSpeed": 0,
        "Except": false,
        "Fatal": false,
        "HealSkill": false,
        "IgnoreTaunt": false,
        "KeyID": "S_Lucy_24_0",
        "Lock": false,
        "LucyPartyDraw": "",
        "NODOD": false,
        "Name": "战术调整",
        "NoBasicSkill": false,
        "NoDrop": false,
        "NotChuck": false,
        "NotCount": false,
        "PlusKeyWords": [],
        "PlusSkillView": "",
        "PlusViewBuffList": [],
        "Rare": false,
        "SKillExtendedItem": [],
        "SkillExtended": [],
        "SpecialUnlock": false,
        "Target": "Misc",
        "Track": false,
        "UnknownTarget": false,
        "UseAp": 0,
        "User": "Lucy",
        "ViewBuff": false,
        "image": "24_l.png"
    },
    {
        "AutoDelete": 0,
        "Basic": false,
        "Category": "null",
        "Counting": 0,
        "Description": "恢复 &a 点法力值。",
        "Disposable": false,
        "Effect_Self": "null",
        "Effect_Target": "SE_Null",
        "EnemyPreview": false,
        "EnemySkillSpeed": 0,
        "Except": false,
        "Fatal": false,
        "HealSkill": false,
        "IgnoreTaunt": false,
        "KeyID": "S_Lucy_24_1",
        "Lock": false,
        "LucyPartyDraw": "",
        "NODOD": false,
        "Name": "暂时撤退",
        "NoBasicSkill": false,
        "NoDrop": false,
        "NotChuck": false,
        "NotCount": false,
        "PlusKeyWords": [],
        "PlusSkillView": "",
        "PlusViewBuffList": [],
        "Rare": false,
        "SKillExtendedItem": [],
        "SkillExtended": [],
        "SpecialUnlock": false,
        "Target": "Misc",
        "Track": false,
        "UnknownTarget": false,
        "UseAp": 0,
        "User": "Lucy",
        "ViewBuff": false,
        "image": "24_r.png"
    },
    {
        "AutoDelete": 0,
        "Basic": false,
        "Category": "LucySkill",
        "Counting": 0,
        "Description": "将敌人的体力值变为0点。\n 若目标是BOSS，当目标体力值降到40%以下时立即死亡。\n 每当通过1个区域时费用增加1点。\n <b>使用后将从牌库中放逐。</b>\n （此技能无法通过‘许愿泉水’以外的方式获得。）",
        "Disposable": true,
        "Effect_Self": "null",
        "Effect_Target": "SE_Null",
        "EnemyPreview": false,
        "EnemySkillSpeed": 0,
        "Except": false,
        "Fatal": false,
        "HealSkill": false,
        "IgnoreTaunt": true,
        "KeyID": "S_Lucy_25",
        "Lock": true,
        "LucyPartyDraw": "",
        "NODOD": false,
        "Name": "最后一击",
        "NoBasicSkill": false,
        "NoDrop": false,
        "NotChuck": false,
        "NotCount": true,
        "PlusKeyWords": [],
        "PlusSkillView": "",
        "PlusViewBuffList": [],
        "Rare": false,
        "SKillExtendedItem": [],
        "SkillExtended": [
            "S_Lucy_25"
        ],
        "SpecialUnlock": true,
        "Target": "enemy",
        "Track": true,
        "UnknownTarget": false,
        "UseAp": 1,
        "User": "Lucy",
        "ViewBuff": false,
        "image": "25.png"
    },
    {
        "AutoDelete": 0,
        "Basic": false,
        "Category": "LucySkill",
        "Counting": 0,
        "Description": "查看弃牌库，并选择一个技能拿到手中。\n该技能的费用减少3点。",
        "Disposable": false,
        "Effect_Self": "null",
        "Effect_Target": "SE_Lucy_26_T",
        "EnemyPreview": false,
        "EnemySkillSpeed": 0,
        "Except": false,
        "Fatal": false,
        "HealSkill": false,
        "IgnoreTaunt": false,
        "KeyID": "S_Lucy_26",
        "Lock": true,
        "LucyPartyDraw": "",
        "NODOD": false,
        "Name": "钓鱼",
        "NoBasicSkill": false,
        "NoDrop": false,
        "NotChuck": false,
        "NotCount": true,
        "PlusKeyWords": [],
        "PlusSkillView": "",
        "PlusViewBuffList": [],
        "Rare": false,
        "SKillExtendedItem": [],
        "SkillExtended": [
            "S_Lucy_26"
        ],
        "SpecialUnlock": false,
        "Target": "Misc",
        "Track": false,
        "UnknownTarget": false,
        "UseAp": 2,
        "User": "Lucy",
        "ViewBuff": false,
        "image": "26.png"
    },
    {
        "AutoDelete": 0,
        "Basic": false,
        "Category": "LucySkill",
        "Counting": 0,
        "Description": "手中所有技能的费用减少 1 点。",
        "Disposable": false,
        "Effect_Self": "null",
        "Effect_Target": "null",
        "EnemyPreview": false,
        "EnemySkillSpeed": 0,
        "Except": false,
        "Fatal": false,
        "HealSkill": false,
        "IgnoreTaunt": false,
        "KeyID": "S_Lucy_3",
        "Lock": false,
        "LucyPartyDraw": "",
        "NODOD": false,
        "Name": "超加速",
        "NoBasicSkill": false,
        "NoDrop": false,
        "NotChuck": false,
        "NotCount": true,
        "PlusKeyWords": [],
        "PlusSkillView": "",
        "PlusViewBuffList": [],
        "Rare": false,
        "SKillExtendedItem": [],
        "SkillExtended": [
            "Extended_Lucy_3"
        ],
        "SpecialUnlock": false,
        "Target": "Misc",
        "Track": false,
        "UnknownTarget": false,
        "UseAp": 0,
        "User": "Lucy",
        "ViewBuff": true,
        "image": "3.png"
    },
    {
        "AutoDelete": 0,
        "Basic": false,
        "Category": "LucySkill",
        "Counting": 0,
        "Description": "在牌库中抽取 3 个技能，该技能费用为 0 。",
        "Disposable": true,
        "Effect_Self": "null",
        "Effect_Target": "null",
        "EnemyPreview": false,
        "EnemySkillSpeed": 0,
        "Except": false,
        "Fatal": false,
        "HealSkill": false,
        "IgnoreTaunt": false,
        "KeyID": "S_Lucy_5",
        "Lock": false,
        "LucyPartyDraw": "",
        "NODOD": false,
        "Name": "运筹帷幄",
        "NoBasicSkill": false,
        "NoDrop": false,
        "NotChuck": false,
        "NotCount": false,
        "PlusKeyWords": [],
        "PlusSkillView": "",
        "PlusViewBuffList": [],
        "Rare": false,
        "SKillExtendedItem": [],
        "SkillExtended": [
            "Extended_Lucy_5"
        ],
        "SpecialUnlock": false,
        "Target": "Misc",
        "Track": false,
        "UnknownTarget": false,
        "UseAp": 1,
        "User": "Lucy",
        "ViewBuff": true,
        "image": "5.png"
    },
    {
        "AutoDelete": 0,
        "Basic": false,
        "Category": "LucySkill",
        "Counting": 0,
        "Description": "从牌库和弃牌库中翻开费用大于 0 的 2 个普通技能，从中选择 1 个技能进行复制直到手牌补满，所选技能附带迅速、放逐，且 2 回合后弃牌。",
        "Disposable": true,
        "Effect_Self": "null",
        "Effect_Target": "null",
        "EnemyPreview": false,
        "EnemySkillSpeed": 0,
        "Except": false,
        "Fatal": false,
        "HealSkill": false,
        "IgnoreTaunt": false,
        "KeyID": "S_Lucy_6",
        "Lock": true,
        "LucyPartyDraw": "",
        "NODOD": false,
        "Name": "复制",
        "NoBasicSkill": false,
        "NoDrop": false,
        "NotChuck": false,
        "NotCount": false,
        "PlusKeyWords": [],
        "PlusSkillView": "",
        "PlusViewBuffList": [],
        "Rare": false,
        "SKillExtendedItem": [],
        "SkillExtended": [
            "Extended_Lucy_6"
        ],
        "SpecialUnlock": false,
        "Target": "Misc",
        "Track": false,
        "UnknownTarget": false,
        "UseAp": 1,
        "User": "Lucy",
        "ViewBuff": true,
        "image": "6.png"
    },
    {
        "AutoDelete": 0,
        "Basic": false,
        "Category": "LucySkill",
        "Counting": 0,
        "Description": "所有友军随机释放专属技能。",
        "Disposable": true,
        "Effect_Self": "null",
        "Effect_Target": "SE_Lucy_7_T",
        "EnemyPreview": false,
        "EnemySkillSpeed": 0,
        "Except": false,
        "Fatal": false,
        "HealSkill": false,
        "IgnoreTaunt": false,
        "KeyID": "S_Lucy_7",
        "Lock": true,
        "LucyPartyDraw": "",
        "NODOD": false,
        "Name": "团队合作",
        "NoBasicSkill": false,
        "NoDrop": false,
        "NotChuck": false,
        "NotCount": true,
        "PlusKeyWords": [],
        "PlusSkillView": "",
        "PlusViewBuffList": [],
        "Rare": false,
        "SKillExtendedItem": [],
        "SkillExtended": [
            "Extended_Lucy_7"
        ],
        "SpecialUnlock": false,
        "Target": "Misc",
        "Track": false,
        "UnknownTarget": false,
        "UseAp": 3,
        "User": "Lucy",
        "ViewBuff": true,
        "image": "7.png"
    },
    {
        "AutoDelete": 0,
        "Basic": false,
        "Category": "LucySkill",
        "Counting": 0,
        "Description": "随机出示 3 个露西技能，从中选择 1 个技能拿到手中。",
        "Disposable": true,
        "Effect_Self": "null",
        "Effect_Target": "SE_Lucy_8_T",
        "EnemyPreview": false,
        "EnemySkillSpeed": 0,
        "Except": false,
        "Fatal": false,
        "HealSkill": false,
        "IgnoreTaunt": false,
        "KeyID": "S_Lucy_8",
        "Lock": false,
        "LucyPartyDraw": "",
        "NODOD": false,
        "Name": "可能性",
        "NoBasicSkill": false,
        "NoDrop": false,
        "NotChuck": false,
        "NotCount": true,
        "PlusKeyWords": [],
        "PlusSkillView": "",
        "PlusViewBuffList": [],
        "Rare": false,
        "SKillExtendedItem": [],
        "SkillExtended": [
            "Extended_Lucy_8"
        ],
        "SpecialUnlock": false,
        "Target": "Misc",
        "Track": false,
        "UnknownTarget": false,
        "UseAp": 1,
        "User": "Lucy",
        "ViewBuff": true,
        "image": "8.png"
    },
    {
        "AutoDelete": 0,
        "Basic": false,
        "Category": "LucySkill",
        "Counting": 0,
        "Description": "将本次回合中出手的友军技能以倒计时 9 的技能再次释放。",
        "Disposable": true,
        "Effect_Self": "null",
        "Effect_Target": "SE_Lucy_9_T",
        "EnemyPreview": false,
        "EnemySkillSpeed": 0,
        "Except": false,
        "Fatal": false,
        "HealSkill": false,
        "IgnoreTaunt": false,
        "KeyID": "S_Lucy_9",
        "Lock": true,
        "LucyPartyDraw": "",
        "NODOD": false,
        "Name": "自动蓄力",
        "NoBasicSkill": false,
        "NoDrop": false,
        "NotChuck": false,
        "NotCount": false,
        "PlusKeyWords": [],
        "PlusSkillView": "",
        "PlusViewBuffList": [],
        "Rare": false,
        "SKillExtendedItem": [],
        "SkillExtended": [
            "Extended_Lucy_9"
        ],
        "SpecialUnlock": false,
        "Target": "Misc",
        "Track": false,
        "UnknownTarget": false,
        "UseAp": 2,
        "User": "Lucy",
        "ViewBuff": true,
        "image": "9.png"
    },
    {
        "AutoDelete": 0,
        "Basic": false,
        "Category": "LucySkill",
        "Counting": 0,
        "Description": "抽取 1 个技能。\n 在本回合中，每当通过补充箭矢恢复法力值时，从牌库中抽取技能。",
        "Disposable": false,
        "Effect_Self": "null",
        "Effect_Target": "SE_Mement_LucyDraw_T",
        "EnemyPreview": false,
        "EnemySkillSpeed": 0,
        "Except": false,
        "Fatal": false,
        "HealSkill": false,
        "IgnoreTaunt": false,
        "KeyID": "S_Mement_LucyDraw",
        "Lock": false,
        "LucyPartyDraw": "Mement",
        "NODOD": false,
        "Name": "制作箭矢",
        "NoBasicSkill": false,
        "NoDrop": false,
        "NotChuck": false,
        "NotCount": false,
        "PlusKeyWords": [],
        "PlusSkillView": "",
        "PlusViewBuffList": [],
        "Rare": false,
        "SKillExtendedItem": [],
        "SkillExtended": [
            "S_Mement_LucyDraw"
        ],
        "SpecialUnlock": false,
        "Target": "Misc",
        "Track": false,
        "UnknownTarget": false,
        "UseAp": 0,
        "User": "LucyDraw",
        "ViewBuff": false,
        "image": "Mement_draw.png"
    },
    {
        "AutoDelete": 0,
        "Basic": false,
        "Category": "LucySkill",
        "Counting": 0,
        "Description": "从牌库中抽取 2 个技能，并给所选目标添加燃烧。",
        "Disposable": false,
        "Effect_Self": "null",
        "Effect_Target": "SE_MissChain_12_LucyD_T",
        "EnemyPreview": false,
        "EnemySkillSpeed": 0,
        "Except": false,
        "Fatal": false,
        "HealSkill": false,
        "IgnoreTaunt": false,
        "KeyID": "S_MissChain_12_LucyD",
        "Lock": false,
        "LucyPartyDraw": "MissChain",
        "NODOD": false,
        "Name": "烈火重生",
        "NoBasicSkill": false,
        "NoDrop": false,
        "NotChuck": false,
        "NotCount": false,
        "PlusKeyWords": [],
        "PlusSkillView": "",
        "PlusViewBuffList": [],
        "Rare": false,
        "SKillExtendedItem": [],
        "SkillExtended": [
            "S_MissChain_12"
        ],
        "SpecialUnlock": false,
        "Target": "ally",
        "Track": false,
        "UnknownTarget": false,
        "UseAp": 0,
        "User": "LucyDraw",
        "ViewBuff": true,
        "image": "Miss_12.png"
    },
    {
        "AutoDelete": 0,
        "Basic": false,
        "Category": "LucySkill",
        "Counting": 0,
        "Description": "查看牌库中的4个技能，并选择其中2个拿到手中。\n若抽取的技能有预见效果，则激活预见。",
        "Disposable": false,
        "Effect_Self": "null",
        "Effect_Target": "SE_Priest_7_T",
        "EnemyPreview": false,
        "EnemySkillSpeed": 0,
        "Except": false,
        "Fatal": false,
        "HealSkill": false,
        "IgnoreTaunt": false,
        "KeyID": "S_Priest_7_LucyD",
        "Lock": false,
        "LucyPartyDraw": "Priest",
        "NODOD": false,
        "Name": "神的启示",
        "NoBasicSkill": false,
        "NoDrop": false,
        "NotChuck": false,
        "NotCount": false,
        "PlusKeyWords": [],
        "PlusSkillView": "",
        "PlusViewBuffList": [],
        "Rare": false,
        "SKillExtendedItem": [],
        "SkillExtended": [
            "Extended_Priest_7"
        ],
        "SpecialUnlock": false,
        "Target": "Misc",
        "Track": false,
        "UnknownTarget": false,
        "UseAp": 0,
        "User": "LucyDraw",
        "ViewBuff": true,
        "image": "Priest_7.png"
    },
    {
        "AutoDelete": 0,
        "Basic": false,
        "Category": "LucySkill",
        "Counting": 0,
        "Description": "从牌库中优先抽取2个恢复技能，该技能的费用减少1点。",
        "Disposable": false,
        "Effect_Self": "null",
        "Effect_Target": "SE_Prime_7_T",
        "EnemyPreview": false,
        "EnemySkillSpeed": 0,
        "Except": false,
        "Fatal": false,
        "HealSkill": false,
        "IgnoreTaunt": false,
        "KeyID": "S_Prime_7_LucyDraw",
        "Lock": false,
        "LucyPartyDraw": "Prime",
        "NODOD": false,
        "Name": "治疗！",
        "NoBasicSkill": false,
        "NoDrop": false,
        "NotChuck": false,
        "NotCount": false,
        "PlusKeyWords": [],
        "PlusSkillView": "",
        "PlusViewBuffList": [],
        "Rare": false,
        "SKillExtendedItem": [],
        "SkillExtended": [
            "S_Prime_7_LucyDraw"
        ],
        "SpecialUnlock": false,
        "Target": "ally",
        "Track": false,
        "UnknownTarget": false,
        "UseAp": 1,
        "User": "LucyDraw",
        "ViewBuff": true,
        "image": "Prime_7.png"
    },
    {
        "AutoDelete": 2,
        "Basic": false,
        "Category": "LucySkill",
        "Counting": 0,
        "Description": "此技能会在战斗结束后继续留在牌库中。\n <b>使用后将从牌库中放逐。</b>\n 无法在获得技能的战斗中使用。",
        "Disposable": true,
        "Effect_Self": "null",
        "Effect_Target": "SE_Null",
        "EnemyPreview": false,
        "EnemySkillSpeed": 0,
        "Except": false,
        "Fatal": false,
        "HealSkill": false,
        "IgnoreTaunt": false,
        "KeyID": "S_S1_LittleMaid_0_Lucy",
        "Lock": false,
        "LucyPartyDraw": "",
        "NODOD": false,
        "Name": "抖落灰尘",
        "NoBasicSkill": false,
        "NoDrop": false,
        "NotChuck": false,
        "NotCount": false,
        "PlusKeyWords": [],
        "PlusSkillView": "",
        "PlusViewBuffList": [],
        "Rare": false,
        "SKillExtendedItem": [],
        "SkillExtended": [
            "S_S1_LittleMaid_0_Lucy"
        ],
        "SpecialUnlock": false,
        "Target": "Misc",
        "Track": false,
        "UnknownTarget": false,
        "UseAp": 1,
        "User": "Lucy",
        "ViewBuff": false,
        "image": "LittleMaid.png"
    },
    {
        "AutoDelete": 0,
        "Basic": false,
        "Category": "LucySkill",
        "Counting": 0,
        "Description": "<b>可使用<color=red> &a 次</color></b>\n 解除所有印记。\n 回合开始时，若手中没有该技能，则抽取该技能。",
        "Disposable": false,
        "Effect_Self": "null",
        "Effect_Target": "SE_S2_MainBoss_1_Lucy_0_T",
        "EnemyPreview": false,
        "EnemySkillSpeed": 0,
        "Except": false,
        "Fatal": false,
        "HealSkill": true,
        "IgnoreTaunt": false,
        "KeyID": "",
        "Lock": false,
        "LucyPartyDraw": "",
        "NODOD": false,
        "Name": "净化",
        "NoBasicSkill": false,
        "NoDrop": true,
        "NotChuck": true,
        "NotCount": true,
        "PlusKeyWords": [],
        "PlusSkillView": "",
        "PlusViewBuffList": [],
        "Rare": false,
        "SKillExtendedItem": [],
        "SkillExtended": [
            "Extended_S2_MainBoss_1_Lucy_0"
        ],
        "SpecialUnlock": false,
        "Target": "ally",
        "Track": false,
        "UnknownTarget": false,
        "UseAp": 1,
        "User": "Lucy",
        "ViewBuff": true,
        "image": "MainBoss_1.png"
    },
    {
        "AutoDelete": 0,
        "Basic": false,
        "Category": "LucySkill",
        "Counting": 0,
        "Description": "从牌库中抽取 2 个技能并为灵魂香炉充能 1 次。\n 若香炉的充能量已达到最大值则再抽取 1 个技能。",
        "Disposable": false,
        "Effect_Self": "null",
        "Effect_Target": "SE_ShadowPriest_10_T",
        "EnemyPreview": false,
        "EnemySkillSpeed": 0,
        "Except": false,
        "Fatal": false,
        "HealSkill": false,
        "IgnoreTaunt": false,
        "KeyID": "S_ShadowPriest_10_LucyDraw",
        "Lock": false,
        "LucyPartyDraw": "ShadowPriest",
        "NODOD": false,
        "Name": "香炉充能",
        "NoBasicSkill": false,
        "NoDrop": false,
        "NotChuck": false,
        "NotCount": false,
        "PlusKeyWords": [],
        "PlusSkillView": "",
        "PlusViewBuffList": [],
        "Rare": false,
        "SKillExtendedItem": [],
        "SkillExtended": [
            "S_ShadowPriest_10_LucyDraw"
        ],
        "SpecialUnlock": false,
        "Target": "Misc",
        "Track": false,
        "UnknownTarget": false,
        "UseAp": 0,
        "User": "LucyDraw",
        "ViewBuff": true,
        "image": "ShadowPriest_10.png"
    },
    {
        "AutoDelete": 0,
        "Basic": false,
        "Category": "LucySkill",
        "Counting": 0,
        "Description": "抽取 2 个技能。\n 选择 - 解除所有友军的干扰减益\n 或改变所有敌人的嘲讽状态\n 或恢复1 点法力值。\n 已经选择的额外能力无法在本次战斗期间选择。",
        "Disposable": false,
        "Effect_Self": "null",
        "Effect_Target": "SE_SilverStein_5_T",
        "EnemyPreview": false,
        "EnemySkillSpeed": 0,
        "Except": false,
        "Fatal": false,
        "HealSkill": false,
        "IgnoreTaunt": false,
        "KeyID": "S_SilverStein_5_LucyD",
        "Lock": false,
        "LucyPartyDraw": "SilverStein",
        "NODOD": false,
        "Name": "紧急装备",
        "NoBasicSkill": false,
        "NoDrop": false,
        "NotChuck": false,
        "NotCount": false,
        "PlusKeyWords": [],
        "PlusSkillView": "",
        "PlusViewBuffList": [],
        "Rare": false,
        "SKillExtendedItem": [],
        "SkillExtended": [
            "Extended_SilverStein_5"
        ],
        "SpecialUnlock": false,
        "Target": "Misc",
        "Track": false,
        "UnknownTarget": false,
        "UseAp": 0,
        "User": "LucyDraw",
        "ViewBuff": true,
        "image": "SilverStein_5.png"
    },
    {
        "AutoDelete": 0,
        "Basic": false,
        "Category": "LucySkill",
        "Counting": 0,
        "Description": "从牌库中抽取费用最高的 2 个技能，并叠加 1 层特丽莎凝神的层数。",
        "Disposable": false,
        "Effect_Self": "null",
        "Effect_Target": "SE_Trisha_10_LucyDraw_T",
        "EnemyPreview": false,
        "EnemySkillSpeed": 0,
        "Except": false,
        "Fatal": false,
        "HealSkill": false,
        "IgnoreTaunt": false,
        "KeyID": "S_Trisha_10_LucyDraw",
        "Lock": false,
        "LucyPartyDraw": "Trisha",
        "NODOD": false,
        "Name": "潜行",
        "NoBasicSkill": false,
        "NoDrop": false,
        "NotChuck": false,
        "NotCount": false,
        "PlusKeyWords": [],
        "PlusSkillView": "",
        "PlusViewBuffList": [],
        "Rare": false,
        "SKillExtendedItem": [],
        "SkillExtended": [
            "S_Trisha_10_LucyDraw"
        ],
        "SpecialUnlock": false,
        "Target": "Misc",
        "Track": false,
        "UnknownTarget": false,
        "UseAp": 0,
        "User": "LucyDraw",
        "ViewBuff": true,
        "image": "Trisha_10.png"
    }
];
window.carddef = carddef;