window.consumedef = {
  "ArtifactPouch": {
    "BattleUse": null,
    "Description": "使用时可从随机 3 个遗物中选择一个获得。",
    "FieldUse": "ArtifactPouch",
    "KeyID": "ArtifactPouch",
    "Lock": 0,
    "Name": "遗物袋",
    "Price": 800,
    "Stack": 0,
    "Target": null,
    "active_battle": 0,
    "active_field": true,
    "image": "ArtifactPouch",
    "itemClass": "Unique"
  },
  "Bread": {
    "BattleUse": null,
    "Description": "恢复一名队员 20% 的体力值。\n 营地 - 恢复所有友军 20% 的体力值。",
    "FieldUse": "Bread",
    "KeyID": "Bread",
    "Lock": false,
    "Name": "面包",
    "Price": 160,
    "Stack": 10,
    "Target": "ally",
    "active_battle": false,
    "active_field": true,
    "image": "Food",
    "itemClass": "Common"
  },
  "Celestial": {
    "BattleUse": null,
    "Description": "展示所有友军的协同强化各 1 个，并选择其中 1 个进行强化。\n 仅展示根据条件可进行强化的选项。",
    "FieldUse": "Celestial",
    "KeyID": "Celestial",
    "Lock": 0,
    "Name": "天神组",
    "Price": 1000,
    "Stack": 0,
    "Target": null,
    "active_battle": 0,
    "active_field": true,
    "image": "Celestial",
    "itemClass": "Legendary"
  },
  "Dinner": {
    "BattleUse": null,
    "Description": "恢复所有友军60%的体力值。",
    "FieldUse": "Dinner",
    "KeyID": "Dinner",
    "Lock": false,
    "Name": "晚宴",
    "Price": 500,
    "Stack": 1,
    "Target": null,
    "active_battle": false,
    "active_field": true,
    "image": "Meat dinner",
    "itemClass": "Unique"
  },
  "EquipPouch": {
    "BattleUse": null,
    "Description": "使用时可从随机3个传说装备中选择一个获得。",
    "FieldUse": "EquipPouch",
    "KeyID": "EquipPouch",
    "Lock": 0,
    "Name": "传说装备袋",
    "Price": 800,
    "Stack": 0,
    "Target": null,
    "active_battle": 0,
    "active_field": true,
    "image": "ArtifactPouch",
    "itemClass": "Unique"
  },
  "GoldenApple": {
    "BattleUse": "S_GoldenApple",
    "Description": "超额恢复友军 25 点体力值。\n 可作为装备组合材料使用。\n 在营地中使用时：所有友军（包括后续招募的队员）的暴击率增加 4%，命中率增加 4%。",
    "FieldUse": "GoldenApple",
    "KeyID": "GoldenApple",
    "Lock": false,
    "Name": "金苹果",
    "Price": 1000,
    "Stack": 0,
    "Target": "ally",
    "active_battle": true,
    "active_field": true,
    "image": "GoldenApple",
    "itemClass": "Unique"
  },
  "GoldenBread": {
    "BattleUse": null,
    "Description": "恢复友军 50% 的体力值，同时解除无法战斗状态。\n 在营地中使用时：恢复所有友军 40% 的体力值，增加所有友军（包括后续招募的队员）3 点最大体力值。",
    "FieldUse": "GoldenBread",
    "KeyID": "GoldenBread",
    "Lock": false,
    "Name": "黄金面包",
    "Price": 1000,
    "Stack": 1,
    "Target": "deathally",
    "active_battle": false,
    "active_field": true,
    "image": "GoldenBread",
    "itemClass": "Unique"
  },
  "Herb": {
    "BattleUse": "S_Herb",
    "Description": "<sprite=1>解除所有痛苦减益",
    "FieldUse": "",
    "KeyID": "Herb",
    "Lock": false,
    "Name": "药草",
    "Price": 200,
    "Stack": 3,
    "Target": "ally",
    "active_battle": true,
    "active_field": false,
    "image": "Hub",
    "itemClass": "Common"
  },
  "Ilya_PassiveConsume": {
    "BattleUse": null,
    "Description": "除伊利亚以外的其他队员每人仅限使用一次。\n 本次调查期间所选队员的闪避率增加2%。\n 选择所选队员的一个技能，为其赋予专属强化效果。",
    "FieldUse": "Ilya_PassiveConsume",
    "KeyID": "Ilya_PassiveConsume",
    "Lock": false,
    "Name": "伊利亚的伏特加",
    "Price": 100,
    "Stack": 3,
    "Target": "ally",
    "active_battle": 0,
    "active_field": true,
    "image": "IlyaPassive",
    "itemClass": "UnCommon"
  },
  "RedHammer": {
    "BattleUse": null,
    "Description": "选择装备道具中的一个。\n 选择相同等级的其它3个道具中的1个交换。",
    "FieldUse": "RedHammer",
    "KeyID": "RedHammer",
    "Lock": false,
    "Name": "黑铁锤",
    "Price": 500,
    "Stack": 1,
    "Target": null,
    "active_battle": false,
    "active_field": true,
    "image": "Hammer",
    "itemClass": "Unique"
  },
  "RedHerb": {
    "BattleUse": "S_RedHerb",
    "Description": "解除目标所有减益。",
    "FieldUse": "",
    "KeyID": "RedHerb",
    "Lock": false,
    "Name": "红光药草",
    "Price": 500,
    "Stack": 1,
    "Target": "ally",
    "active_battle": true,
    "active_field": false,
    "image": "herb",
    "itemClass": "Unique"
  },
  "RedWing": {
    "BattleUse": "S_RedWing",
    "Description": "使用时赋予目标闪避下一次攻击的增益。",
    "FieldUse": "",
    "KeyID": "RedWing",
    "Lock": false,
    "Name": "烟雾弹",
    "Price": 500,
    "Stack": 1,
    "Target": "ally",
    "active_battle": true,
    "active_field": false,
    "image": "smoke bomb",
    "itemClass": "Unique"
  },
  "SkillBookCharacter": {
    "BattleUse": null,
    "Description": "展示相当于队员数量的可学习技能，并选择其中一个技能学习。",
    "FieldUse": "SkillBookCharacter",
    "KeyID": "SkillBookCharacter",
    "Lock": false,
    "Name": "技能书",
    "Price": 300,
    "Stack": 10,
    "Target": null,
    "active_battle": false,
    "active_field": true,
    "image": "item_book_01",
    "itemClass": "UnCommon"
  },
  "SkillBookCharacter_Rare": {
    "BattleUse": null,
    "Description": "可查看每位队员的随机 1 个稀有技能，并选择其中一个技能。",
    "FieldUse": "SkillBookCharacter_Rare",
    "KeyID": "SkillBookCharacter_Rare",
    "Lock": false,
    "Name": "黄金技能书",
    "Price": 1000,
    "Stack": 5,
    "Target": null,
    "active_battle": false,
    "active_field": true,
    "image": "item_book_06",
    "itemClass": "Legendary"
  },
  "SkillBookInfinity": {
    "BattleUse": null,
    "Description": "展示队员的专属技能，每位队员各 5 个。\n 可选择并学习其中一个技能。\n （当有 3 位队员时展示 15 个技能，4 位时展示 20 个，选择其中一个）",
    "FieldUse": "SkillBookInfinity",
    "KeyID": "SkillBookInfinity",
    "Lock": 0,
    "Name": "无限技能书",
    "Price": 650,
    "Stack": 5,
    "Target": null,
    "active_battle": 0,
    "active_field": true,
    "image": "Item_InfinityBook",
    "itemClass": "Unique"
  },
  "SkillBookLucy": {
    "BattleUse": null,
    "Description": "从露西的随机 2 个稀有技能中选择 1 个学习。",
    "FieldUse": "SkillBookLucy",
    "KeyID": "SkillBookLucy",
    "Lock": 0,
    "Name": "神秘的技能书",
    "Price": 1000,
    "Stack": 0,
    "Target": null,
    "active_battle": 0,
    "active_field": true,
    "image": "item_book_03",
    "itemClass": "Legendary"
  },
  "SkillBookSuport": {
    "BattleUse": null,
    "Description": "可以给支援型角色使用。\n 可以从所选友军的所有技能中选择一个学习。",
    "FieldUse": "SkillBookSuport",
    "KeyID": "SkillBookSuport",
    "Lock": false,
    "Name": "技能书 - 治愈定式",
    "Price": 500,
    "Stack": 10,
    "Target": "ally",
    "active_battle": false,
    "active_field": true,
    "image": "item_book_05",
    "itemClass": "Rare"
  },
  "SmallBarrierMachine": {
    "BattleUse": "S_SmallBarrierMachine",
    "Description": "生成 12 点防护墙",
    "FieldUse": "",
    "KeyID": "SmallBarrierMachine",
    "Lock": false,
    "Name": "小型保护罩生成器",
    "Price": 200,
    "Stack": 2,
    "Target": "all_ally",
    "active_battle": true,
    "active_field": false,
    "image": "BarrierMachine",
    "itemClass": "Common"
  },
  "SodaWater": {
    "BattleUse": "S_Sparkling",
    "Description": "解除所有<sprite=0>弱化、<sprite=2>干扰减益",
    "FieldUse": "",
    "KeyID": "SodaWater",
    "Lock": false,
    "Name": "药丸",
    "Price": 200,
    "Stack": 3,
    "Target": "ally",
    "active_battle": true,
    "active_field": false,
    "image": "Pill",
    "itemClass": "Common"
  },
  "Specialpackage": {
    "BattleUse": null,
    "Description": "<color=red>无法在希望模式中使用。</color>\n \n 这里有一张商店主人留下的纸条。\n <color=#919191>这是特意为你准备的挑战，你能挑战成功吗？哈哈…</color>",
    "FieldUse": "Specialpackage",
    "KeyID": "Specialpackage",
    "Lock": 0,
    "Name": "商店主人的特别礼包",
    "Price": 600,
    "Stack": 0,
    "Target": null,
    "active_battle": 0,
    "active_field": true,
    "image": "SunMoonQuest",
    "itemClass": "UnCommon"
  },
  "TimeRelic": {
    "BattleUse": "S_MBoss2_1_0",
    "Description": "重复释放在本次战斗中<b>从手中释放的任意 8 个技能</b>。",
    "FieldUse": "",
    "KeyID": "TimeRelic",
    "Lock": false,
    "Name": "回旋的齿轮",
    "Price": 800,
    "Stack": 0,
    "Target": "ally",
    "active_battle": true,
    "active_field": false,
    "image": "Item (1)",
    "itemClass": "Unique"
  }
}