window.equipdef = {
  "AgentSunglass": {
    "Description": "攻击时超出命中率 100% 的数值将增加到暴击概率。",
    "EquipSkill": [],
    "Equip_Script": "AgentSunglass",
    "Itemclass": "Legendary",
    "KeyID": "AgentSunglass",
    "Lock": true,
    "Name": "特工的墨镜",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "AgentSunglass"
  },
  "Alicesgift": {
    "Description": "固定能力的伤害增加 2 点。\n 战斗开始时，使固定能力附带基本功。\n \n <color=#919191>约翰好像讨厌宗教... - 普瑞斯特</color>",
    "EquipSkill": [],
    "Equip_Script": "Alicesgift",
    "Itemclass": "Unique",
    "KeyID": "Alicesgift",
    "Lock": true,
    "Name": "爱丽丝的礼物",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": true,
    "TimeMoneyPrice": 0,
    "image": "AlicesGift"
  },
  "AmuletofAnger": {
    "Description": "",
    "EquipSkill": [],
    "Equip_Script": "AmuletofAnger",
    "Itemclass": "UnCommon",
    "KeyID": "AmuletofAnger",
    "Lock": false,
    "Name": "愤怒符咒",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Equip (2)"
  },
  "AmuletofStability": {
    "Description": "",
    "EquipSkill": [],
    "Equip_Script": "AmuletofStability",
    "Itemclass": "UnCommon",
    "KeyID": "AmuletofStability",
    "Lock": false,
    "Name": "稳定符咒",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Equip (3)"
  },
  "Analyticalscope": {
    "Description": "攻击行动倒计时为 1 的敌人时以暴击形式命中。\n 仅在使用固定能力或释放手中的技能时有效。\n \n <color=#919191>我会准确瞄准你的弱点。 - 西尔弗斯坦</color>",
    "EquipSkill": [],
    "Equip_Script": "Analyticalscope",
    "Itemclass": "Legendary",
    "KeyID": "Analyticalscope",
    "Lock": true,
    "Name": "天空守望者",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": true,
    "TimeMoneyPrice": 0,
    "image": "Analyticalscope"
  },
  "Ankh": {
    "Description": "",
    "EquipSkill": [],
    "Equip_Script": "Ankh",
    "Itemclass": "Rare",
    "KeyID": "Ankh",
    "Lock": false,
    "Name": "生命之符",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Ankh"
  },
  "ArmletofGambler": {
    "Description": "",
    "EquipSkill": [],
    "Equip_Script": "ArmletofGambler",
    "Itemclass": "Unique",
    "KeyID": "ArmletofGambler",
    "Lock": false,
    "Name": "赌徒的手镯",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Equip (81)"
  },
  "Arrowofangel": {
    "Description": "无视嘲讽",
    "EquipSkill": [],
    "Equip_Script": "Arrowofangel",
    "Itemclass": "Legendary",
    "KeyID": "Arrowofangel",
    "Lock": false,
    "Name": "天使之箭",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Equip (76)"
  },
  "BarrierInk": {
    "Description": "전투 시작시 최대체력의 50% 만큼 고통 피해를 입고, 최대 체력의 2배만큼 보호막을 얻습니다. \n보호막은 이번 전투동안 지속됩니다.\n체력이 0 이하였다면 발동하지 않습니다.",
    "EquipSkill": [],
    "Equip_Script": "BarrierInk",
    "Itemclass": "Legendary",
    "KeyID": "BarrierInk",
    "Lock": true,
    "Name": "墨水保护罩",
    "NoDrop": false,
    "Off": false,
    "SpecialUnlock": true,
    "TimeMoneyPrice": 0,
    "image": "Ink"
  },
  "BastardSword": {
    "Description": "",
    "EquipSkill": [],
    "Equip_Script": "BastardSword",
    "Itemclass": "UnCommon",
    "KeyID": "BastardSword",
    "Lock": false,
    "Name": "破坏神之剑",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Equip (17)"
  },
  "Bellofsalvation": {
    "Description": "",
    "EquipSkill": [],
    "Equip_Script": "Bellofsalvation",
    "Itemclass": "Rare",
    "KeyID": "Bellofsalvation",
    "Lock": false,
    "Name": "救赎之钟",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Bellofsalvation"
  },
  "BibleRevisedEdition": {
    "Description": "",
    "EquipSkill": [],
    "Equip_Script": "BibleRevisedEdition",
    "Itemclass": "Rare",
    "KeyID": "BibleRevisedEdition",
    "Lock": false,
    "Name": "圣书[修订版]",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Equip (49)"
  },
  "BlackMoonSword": {
    "Description": "",
    "EquipSkill": [],
    "Equip_Script": "BlackMoonSword",
    "Itemclass": "Legendary",
    "KeyID": "BlackMoonSword",
    "Lock": false,
    "Name": "黑月刀",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "BlackMoonSword"
  },
  "BlackSpikedArmor": {
    "Description": "被击中时反射所受伤害的一半。",
    "EquipSkill": [],
    "Equip_Script": "BlackSpikedArmor",
    "Itemclass": "Legendary",
    "KeyID": "BlackSpikedArmor",
    "Lock": false,
    "Name": "黑色荆棘铠甲",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Equip (73)"
  },
  "BlankBullet": {
    "Description": "每次战斗触发一次：战斗期间装备角色释放手中的技能累计消耗8点法力值时，对随机敌人造成眩晕。",
    "EquipSkill": [],
    "Equip_Script": "BlankBullet",
    "Itemclass": "Unique",
    "KeyID": "BlankBullet",
    "Lock": true,
    "Name": "古老的空包弹",
    "NoDrop": true,
    "Off": false,
    "SpecialUnlock": true,
    "TimeMoneyPrice": 0,
    "image": "Blank"
  },
  "BloodyMary": {
    "Description": "아무 아군이라도 빈사상태가 되면 자신 치유력의 2배 만큼 방벽을 생성합니다.\n이 효과는 전투당 한번 발동합니다.",
    "EquipSkill": [],
    "Equip_Script": "BloodyMary",
    "Itemclass": "Unique",
    "KeyID": "BloodyMary",
    "Lock": true,
    "Name": "血腥玛丽",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Equip (61)"
  },
  "CamouflageCloak": {
    "Description": "战斗开始时 100% 闪避一次攻击。",
    "EquipSkill": [],
    "Equip_Script": "CamouflageCloak",
    "Itemclass": "Unique",
    "KeyID": "CamouflageCloak",
    "Lock": true,
    "Name": "影子帷幕斗篷",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "CamouflageCloak"
  },
  "Candlestick": {
    "Name":"?",
    "Description": "대상에게 디버프를 1중첩을 부여할 때 마다, 33% 확률로 중첩수를 1 더 부여합니다.",
    "EquipSkill": [],
    "Equip_Script": "Candlestick",
    "ItemClass": "Legendary",
    "Itemclass": "Legendary",
    "KeyID": "Candlestick",
    "Lock": 0,
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": 0,
    "TimeMoneyPrice": 0,
    "image": "Equip (11)"
  },
  "CeremonialGloves": {
    "Description": "",
    "EquipSkill": [],
    "Equip_Script": "CeremonialGloves",
    "Itemclass": "UnCommon",
    "KeyID": "CeremonialGloves",
    "Lock": false,
    "Name": "礼仪手套",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Equip (46)"
  },
  "CharginTarge": {
    "Description": "体力极限处于保护状态时，攻击力增加 15%。",
    "EquipSkill": [],
    "Equip_Script": "CharginTarge",
    "Itemclass": "Rare",
    "KeyID": "CharginTarge",
    "Lock": false,
    "Name": "突击盾牌",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "CharginTarge"
  },
  "CrescentCape": {
    "Description": "",
    "EquipSkill": [],
    "Equip_Script": "CrescentCape",
    "Itemclass": "UnCommon",
    "KeyID": "CrescentCape",
    "Lock": false,
    "Name": "新月斗篷",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Equip (16)"
  },
  "CrescentsReflex": {
    "Description": "",
    "EquipSkill": [],
    "Equip_Script": "CrescentsReflex",
    "Itemclass": "Unique",
    "KeyID": "CrescentsReflex",
    "Lock": false,
    "Name": "月影",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Equip (28)"
  },
  "CrossBrooch": {
    "Description": "",
    "EquipSkill": [],
    "Equip_Script": "CrossBrooch",
    "Itemclass": "Rare",
    "KeyID": "CrossBrooch",
    "Lock": false,
    "Name": "十字架胸针",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "CrossBrooch"
  },
  "CrownofThorns": {
    "Description": "濒死状态时，手中装备角色的治疗技能将无视体力极限。",
    "EquipSkill": [],
    "Equip_Script": "CrownofThorns",
    "Itemclass": "Legendary",
    "KeyID": "CrownofThorns",
    "Lock": true,
    "Name": "荆棘王冠",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Equip (31)"
  },
  "CubicNecklace": {
    "Description": "",
    "EquipSkill": [],
    "Equip_Script": "CubicNecklace",
    "Itemclass": "Common",
    "KeyID": "CubicNecklace",
    "Lock": false,
    "Name": "宝石项链",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Equip (40)"
  },
  "CubicRing": {
    "Description": "",
    "EquipSkill": [],
    "Equip_Script": "CubicRing",
    "Itemclass": "Common",
    "KeyID": "CubicRing",
    "Lock": false,
    "Name": "宝石戒指",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Equip (21)"
  },
  "DarkCross": {
    "Description": "释放装备角色手中的友军指向技能时，使该友军无视嘲讽。\n \n <color=#919191>等我回到家，我要先吃个芝士蛋糕。 - 卡伦</color>",
    "EquipSkill": [],
    "Equip_Script": "DarkCross",
    "Itemclass": "Unique",
    "KeyID": "DarkCross",
    "Lock": true,
    "Name": "暗黑十字",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": true,
    "TimeMoneyPrice": 0,
    "image": "DarkCross"
  },
  "DarkPrestClothes": {
    "Description": "可将手中的<b>单体友军</b>恢复技能释放给敌人。\n 指向敌人释放恢复技能时，造成的伤害相当于恢复量的 130%。",
    "EquipSkill": [],
    "Equip_Script": "DarkPrestClothes",
    "Itemclass": "Legendary",
    "KeyID": "DarkPrestClothes",
    "Lock": true,
    "Name": "黑色祭司服",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Equip (83)"
  },
  "Deadeye": {
    "Description": "",
    "EquipSkill": [],
    "Equip_Script": "Deadeye",
    "Itemclass": "Unique",
    "KeyID": "Deadeye",
    "Lock": false,
    "Name": "暗杀者之眼",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Equip (12)"
  },
  "DemonHunter": {
    "Description": "手中第 6 张牌的费用变为 0，释放时将丢弃手中的所有技能。",
    "EquipSkill": [],
    "Equip_Script": "Dooooooom",
    "Itemclass": "Unique",
    "KeyID": "DemonHunter",
    "Lock": true,
    "Name": "恶魔猎人",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Equip (69)"
  },
  "DevilsHorn": {
    "Description": "착용자가 적에게 디버프를 부여할 때 마다 디버프 1중첩당 3의 고통 피해를 입힙니다.",
    "EquipSkill": [],
    "Equip_Script": "DevilsHorn",
    "Itemclass": "Unique",
    "KeyID": "DevilsHorn",
    "Lock": false,
    "Name": "恶魔犄角",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Equip (75)"
  },
  "DochiHat": {
    "Description": "释放治疗技能时，给目标附加攻击力 10%、闪避率 5%，持续 2 回合。",
    "EquipSkill": [],
    "Equip_Script": "DochiHat",
    "Itemclass": "Unique",
    "KeyID": "DochiHat",
    "Lock": true,
    "Name": "草刺猬帽",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "DochiHat"
  },
  "DolorousStroke": {
    "Description": "每当装备角色释放固定能力或技能时，增加暴击伤害 25%、暴击概率 10%、受暴击概率 10%。\n <b>暴击命中或受到暴击时</b>叠加层数重置。",
    "EquipSkill": [],
    "Equip_Script": "DolorousStroke",
    "Itemclass": "Legendary",
    "KeyID": "DolorousStroke",
    "Lock": true,
    "Name": "灾难一击",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Equip (70)"
  },
  "EagleEye": {
    "Description": "",
    "EquipSkill": [],
    "Equip_Script": "EagleEye",
    "Itemclass": "Rare",
    "KeyID": "EagleEye",
    "Lock": false,
    "Name": "鹰眼",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "EagleEye"
  },
  "EnchantedRing": {
    "Description": "每回合 50% 概率法力值 +1",
    "EquipSkill": [],
    "Equip_Script": "EnchantedRing",
    "Itemclass": "Unique",
    "KeyID": "EnchantedRing",
    "Lock": false,
    "Name": "附魔戒指",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Equip (11)"
  },
  "EndlessScroll": {
    "Description": "该装备能够无限叠加附魔属性且不会被诅咒。",
    "EquipSkill": [],
    "Equip_Script": "EndlessScroll",
    "Itemclass": "Rare",
    "KeyID": "EndlessScroll",
    "Lock": false,
    "Name": "无限魔法羊皮纸",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "EndlessScroll"
  },
  "Featheroflife": {
    "Description": "受到致命伤害时，2 回合期间免疫所有伤害。\n 触发该能力时，羽毛消失。\n \n <color=#919191>不要随便拔我的羽毛！ - 凤凰</color>",
    "EquipSkill": [],
    "Equip_Script": "Featheroflife",
    "Itemclass": "Unique",
    "KeyID": "Featheroflife",
    "Lock": true,
    "Name": "燃烧的羽毛",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": true,
    "TimeMoneyPrice": 0,
    "image": "Featheroflife"
  },
  "FlameDarkSword": {
    "Description": "攻击时 50% 概率向敌人释放“暗影斩”",
    "EquipSkill": [],
    "Equip_Script": "FlameDarkSword",
    "Itemclass": "Legendary",
    "KeyID": "FlameDarkSword",
    "Lock": false,
    "Name": "炽焰魔影剑",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Equip (8)"
  },
  "FlameShieldGenerator": {
    "Description": "每当装备角色释放手中的技能时，获得体力极限保护增益。\n \n <color=#919191>小心别烧到头发哦！ - 链锯小姐</color>",
    "EquipSkill": [],
    "Equip_Script": "FlameShieldGenerator",
    "Itemclass": "Legendary",
    "KeyID": "FlameShieldGenerator",
    "Lock": true,
    "Name": "燃烧的夜晚",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": true,
    "TimeMoneyPrice": 0,
    "image": "FlameShieldGenerator"
  },
  "ForbiddenLibram": {
    "Description": "手中治疗技能的治疗量变成 0~200%。",
    "EquipSkill": [],
    "Equip_Script": "ForbiddenLibram",
    "Itemclass": "Unique",
    "KeyID": "ForbiddenLibram",
    "Lock": true,
    "Name": "禁忌的圣书",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Equip (5)"
  },
  "ForestSword": {
    "Description": "在体力值为 0 点以下的状态下受到攻击时，抵挡伤害并使用奥义：草叶斩给所有敌人造成 50 点伤害。\n 使用此效果后，直到在营地内恢复之前都无法再次触发。\n 当前状态：&a",
    "EquipSkill": [],
    "Equip_Script": "ForestSword",
    "Itemclass": "Unique",
    "KeyID": "ForestSword",
    "Lock": true,
    "Name": "真正的森林之剑",
    "NoDrop": true,
    "Off": false,
    "SpecialUnlock": true,
    "TimeMoneyPrice": 0,
    "image": "ForestSword"
  },
  "ForestSword_0": {
    "Description": "戴上这个装备和当前关卡的BOSS战斗，希望不要变成无法战斗状态。\n <color=#919191>蕴藏在剑中的力量正在沉睡...</color>",
    "EquipSkill": [],
    "Equip_Script": "ForestSword_0",
    "Itemclass": "Rare",
    "KeyID": "ForestSword_0",
    "Lock": true,
    "Name": "森林之剑",
    "NoDrop": true,
    "Off": 0,
    "SpecialUnlock": true,
    "TimeMoneyPrice": 0,
    "image": "ForestSword"
  },
  "FoxOrb": {
    "Description": "每当装备角色击杀敌人时，永久提升封印灵珠的攻击力。\n 达成 15% 攻击力时道具升级。\n <color=red>男性角色无法装备</color>",
    "EquipSkill": [],
    "Equip_Script": "FoxOrb",
    "Itemclass": "Unique",
    "KeyID": "FoxOrb",
    "Lock": true,
    "Name": "封印灵珠",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "FoxOrb_0"
  },
  "FoxOrb_0": {
    "Description": "攻击时造成伤害的 20% 转化为体力值\n <color=red>男性角色无法装备</color>",
    "EquipSkill": [],
    "Equip_Script": "FoxOrb_0",
    "Itemclass": "Legendary",
    "KeyID": "FoxOrb_0",
    "Lock": true,
    "Name": "狐狸珠",
    "NoDrop": 0,
    "Off": true,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "FoxOrb_1"
  },
  "FrozenShuriken": {
    "Description": "回合开始时，牌库中装备角色费用 1 的攻击技能伤害增加 5 点。",
    "EquipSkill": [],
    "Equip_Script": "FrozenShuriken",
    "Itemclass": "Unique",
    "KeyID": "FrozenShuriken",
    "Lock": 0,
    "Name": "冰冻飞镖",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": 0,
    "TimeMoneyPrice": 0,
    "image": "FrozenSuriken"
  },
  "GasMask": {
    "Description": "战斗开始时，给牌库中装备角色的敌人指向技能附加中毒效果，给友军指向治疗技能则附加持续恢复效果。\n \n <color=#919191>散发哈密瓜的香味。</color>",
    "EquipSkill": [],
    "Equip_Script": "GasMask",
    "Itemclass": "Legendary",
    "KeyID": "GasMask",
    "Lock": true,
    "Name": "化学燃气罐",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": true,
    "TimeMoneyPrice": 0,
    "image": "GasTank"
  },
  "GhostBadge": {
    "Description": "",
    "EquipSkill": [],
    "Equip_Script": "GhostBadge",
    "Itemclass": "Common",
    "KeyID": "GhostBadge",
    "Lock": false,
    "Name": "幽灵徽章",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Equip (37)"
  },
  "GuardsCertificate": {
    "Description": "战斗开始时嘲讽所有敌人。\n \n <color=#919191>我究竟为什么会在这儿当守卫？ - 钢铁之心</color>",
    "EquipSkill": [],
    "Equip_Script": "GuardsCertificate",
    "Itemclass": "Unique",
    "KeyID": "GuardsCertificate",
    "Lock": true,
    "Name": "守卫队的证书",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": true,
    "TimeMoneyPrice": 0,
    "image": "GuardsCertificate"
  },
  "Guitar": {
    "Description": "仅限支援型角色装备，战斗开始时为固定能力赋予基本功。",
    "EquipSkill": [],
    "Equip_Script": "Guitar",
    "Itemclass": "Unique",
    "KeyID": "Guitar",
    "Lock": true,
    "Name": "荒野的旋律",
    "NoDrop": true,
    "Off": false,
    "SpecialUnlock": true,
    "TimeMoneyPrice": 0,
    "image": "Shamisen"
  },
  "HalfMask": {
    "Description": "复制其他队员释放的技能作为自己的固定能力。\n \n <color=#919191>某个男性使用过的面具，看起来曾经拥有过强大的力量，现在已经衰弱。</color>",
    "EquipSkill": [],
    "Equip_Script": "HalfMask",
    "Itemclass": "Legendary",
    "KeyID": "HalfMask",
    "Lock": true,
    "Name": "神秘人的半假面",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Halfmask"
  },
  "HandprintofGrimReaper": {
    "Description": "",
    "EquipSkill": [],
    "Equip_Script": "HandPrintofGrimReaper",
    "Itemclass": "Legendary",
    "KeyID": "HandprintofGrimReaper",
    "Lock": false,
    "Name": "镰刀收割者的手印",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Equip (74)"
  },
  "HeartofIceSpirit": {
    "Description": "被击中时使敌人无法行动(<sprite=2> 33%)。\n 根据装备角色的干扰成功率增加概率。",
    "EquipSkill": [],
    "Equip_Script": "HeartofIceSpirit",
    "Itemclass": "Legendary",
    "KeyID": "HeartofIceSpirit",
    "Lock": true,
    "Name": "冰霜精灵之心",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Equip (72)"
  },
  "HighPriestsLegacy": {
    "Description": "<b>战斗开始时</b>将牌库中自己的技能变成一次性技能，固定能力消耗法力值减少 1 点。",
    "EquipSkill": [],
    "Equip_Script": "HighPriestsLegacy",
    "Itemclass": "Unique",
    "KeyID": "HighPriestsLegacy",
    "Lock": true,
    "Name": "大祭司的遗产",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Equip (7)"
  },
  "HolySwordKarsaga": {
    "Description": "每回合结束时手中某一个技能的伤害、治疗量增加 30%。",
    "EquipSkill": [],
    "Equip_Script": "HolySwordKarsaga",
    "Itemclass": "Legendary",
    "KeyID": "HolySwordKarsaga",
    "Lock": true,
    "Name": "圣剑卡尔萨迦",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Equip (1)"
  },
  "HuntersNose": {
    "Description": "每回合第一个释放的技能或固定能力如果是自己的，则伤害增加 25%。",
    "EquipSkill": [],
    "Equip_Script": "HuntersNose",
    "Itemclass": "Unique",
    "KeyID": "HuntersNose",
    "Lock": false,
    "Name": "猎人的嗅觉",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Equip (67)"
  },
  "Ilya_Sword_0": {
    "Description": "同时佩戴雷鸣刀和雪月刀时，战斗开始后给自身所有技能赋予致命词条\n <color=#919191>伊利亚的武士刀，用于施展拔刀术</color>",
    "EquipSkill": [],
    "Equip_Script": "Ilya_Sword_0",
    "Itemclass": "Unique",
    "KeyID": "Ilya_Sword_0",
    "Lock": true,
    "Name": "雷鸣刀",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": true,
    "TimeMoneyPrice": 0,
    "image": "IlyaSword_0"
  },
  "Ilya_Sword_1": {
    "Description": "同时佩戴雷鸣刀和雪月刀时，战斗开始后给自身所有技能赋予致命词条\n <color=#919191>你们不要总搞错了，是雪，不是冰，这两个有很大的区别… - 伊利亚</color>",
    "EquipSkill": [],
    "Equip_Script": "Ilya_Sword_1",
    "Itemclass": "Unique",
    "KeyID": "Ilya_Sword_1",
    "Lock": true,
    "Name": "雪月刀",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": true,
    "TimeMoneyPrice": 0,
    "image": "IlyaSword_1"
  },
  "IronShield": {
    "Description": "",
    "EquipSkill": [],
    "Equip_Script": "IronShield",
    "Itemclass": "Rare",
    "KeyID": "IronShield",
    "Lock": false,
    "Name": "钢铁护盾",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "IronShield"
  },
  "KaleidoScopeNecklace": {
    "Description": "该道具的能力值取决于穿戴的角色。\n<color=#1681F3FF>男性：暴击率增加8%，闪避率减少6%\n女性：闪避率增加12%，暴击率减少4%\n攻击型角色：暴击率增加11%\n防御型角色：最大体力值增加6点，所受治疗量增加15%\n治疗型角色：治疗力增加2点，所有减益成功率增加10%</color>",
    "EquipSkill": [],
    "Equip_Script": "KaleidoScopeNecklace",
    "Itemclass": "Rare",
    "KeyID": "KaleidoScopeNecklace",
    "Lock": true,
    "Name": "万花筒项链",
    "NoDrop": false,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "kaleidoscope necklace_"
  },
  "King_Armor": {
    "Description": "防御型角色装备效果：每 3 个回合时下次出手的技能费用减少 1 点。",
    "EquipSkill": [],
    "Equip_Script": "King_Armor",
    "Itemclass": "Legendary",
    "KeyID": "King_Armor",
    "Lock": true,
    "Name": "被遗忘的王的铠甲",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": true,
    "TimeMoneyPrice": 0,
    "image": "King_Armor"
  },
  "King_Cape": {
    "Description": "支援型角色装备效果：每 3 个回合时下次出手的技能费用减少 1 点。",
    "EquipSkill": [],
    "Equip_Script": "King_Cape",
    "Itemclass": "Legendary",
    "KeyID": "King_Cape",
    "Lock": true,
    "Name": "被遗忘的王的斗篷",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": true,
    "TimeMoneyPrice": 0,
    "image": "King_Cape"
  },
  "King_Sword": {
    "Description": "攻击型角色装备效果：每 3 个回合时下次出手的技能费用减少 1 点。",
    "EquipSkill": [],
    "Equip_Script": "King_Sword",
    "Itemclass": "Legendary",
    "KeyID": "King_Sword",
    "Lock": true,
    "Name": "被遗忘的王的剑",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": true,
    "TimeMoneyPrice": 0,
    "image": "King_Sword"
  },
  "LastStand": {
    "Description": "处于濒死状态时，道具损坏并触发以下效果。\n \n 本次战斗期间最大体力值减少 50%、攻击力增加 30%、恢复所有体力值。",
    "EquipSkill": [],
    "Equip_Script": "LastStand",
    "Itemclass": "Unique",
    "KeyID": "LastStand",
    "Lock": false,
    "Name": "最后的抵抗",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Equip (4)"
  },
  "LeavesBelt": {
    "Description": "",
    "EquipSkill": [],
    "Equip_Script": "LeavesBelt",
    "Itemclass": "UnCommon",
    "KeyID": "LeavesBelt",
    "Lock": false,
    "Name": "树叶腰带",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Equip (14)"
  },
  "LifeStoneRing": {
    "Description": "",
    "EquipSkill": [],
    "Equip_Script": "LifeStoneRing",
    "Itemclass": "UnCommon",
    "KeyID": "LifeStoneRing",
    "Lock": false,
    "Name": "生命石戒指",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Equip (13)"
  },
  "LongSword": {
    "Description": "",
    "EquipSkill": [],
    "Equip_Script": "LongSword",
    "Itemclass": "UnCommon",
    "KeyID": "LongSword",
    "Lock": false,
    "Name": "长剑",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Equip (23)"
  },
  "LostofDecedent": {
    "Description": "受到暴击伤害时保护体力极限",
    "EquipSkill": [],
    "Equip_Script": "LostofDecedent",
    "Itemclass": "Legendary",
    "KeyID": "LostofDecedent",
    "Lock": false,
    "Name": "狮子的庇佑",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Equip (32)"
  },
  "LuckPrayAmulet": {
    "Description": "",
    "EquipSkill": [],
    "Equip_Script": "LuckPrayAmulet",
    "Itemclass": "UnCommon",
    "KeyID": "LuckPrayAmulet",
    "Lock": false,
    "Name": "幸运祈愿符咒",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Equip (24)"
  },
  "MagicThread": {
    "Description": "战斗开始时，牌库内自己的治疗技能费用减少 1 点。\n \n <color=#919191>如果我能像控制伊芙一样控制人… - 西斯</color>",
    "EquipSkill": [],
    "Equip_Script": "MagicThread",
    "Itemclass": "Unique",
    "KeyID": "MagicThread",
    "Lock": true,
    "Name": "魔法线团",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": true,
    "TimeMoneyPrice": 0,
    "image": "MagicThread"
  },
  "MessiahbladesPrototype": {
    "Description": "每回合生成“未完成幻影剑”。\n \n <color=#919191>其实我并不是只会幻影剑。 - 阿扎尔</color>",
    "EquipSkill": [],
    "Equip_Script": "MessiahbladesPrototype",
    "Itemclass": "Legendary",
    "KeyID": "MessiahbladesPrototype",
    "Lock": true,
    "Name": "弥赛亚刀锋原形",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": true,
    "TimeMoneyPrice": 0,
    "image": "MessiahbladesPrototype"
  },
  "Morph": {
    "Description": "战斗开始时，随机展示3个传说装备道具，并在本次战斗期间获得该装备道具的效果。",
    "EquipSkill": [],
    "Equip_Script": "Morph",
    "Itemclass": "Legendary",
    "KeyID": "Morph",
    "Lock": true,
    "Name": "变体精灵",
    "NoDrop": false,
    "Off": false,
    "SpecialUnlock": true,
    "TimeMoneyPrice": 0,
    "image": "Mope"
  },
  "NecklaceofLife": {
    "Description": "",
    "EquipSkill": [],
    "Equip_Script": "NecklaceofLife",
    "Itemclass": "UnCommon",
    "KeyID": "NecklaceofLife",
    "Lock": false,
    "Name": "生命石项链",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Equip (44)"
  },
  "OldBible": {
    "Description": "",
    "EquipSkill": [],
    "Equip_Script": "OldBilbe",
    "Itemclass": "Common",
    "KeyID": "OldBible",
    "Lock": false,
    "Name": "破旧的圣书",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Equip (35)"
  },
  "OrderofEgis": {
    "Description": "",
    "EquipSkill": [],
    "Equip_Script": "OrderofEgis",
    "Itemclass": "Unique",
    "KeyID": "OrderofEgis",
    "Lock": false,
    "Name": "守护标志",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Equip (30)"
  },
  "OrderofHonor": {
    "Description": "每当击杀六个敌人时，将具有 50 点伤害的[处决标志]技能拿到手中。",
    "EquipSkill": [],
    "Equip_Script": "OrderofHonor",
    "Itemclass": "Unique",
    "KeyID": "OrderofHonor",
    "Lock": false,
    "Name": "处决标志",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Equip (57)"
  },
  "OrderofSacrifice": {
    "Description": "",
    "EquipSkill": [],
    "Equip_Script": "OrderofSacrifice",
    "Itemclass": "Unique",
    "KeyID": "OrderofSacrifice",
    "Lock": false,
    "Name": "献身标志",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Equip (63)"
  },
  "OrderofValiancy": {
    "Description": "",
    "EquipSkill": [],
    "Equip_Script": "OrderofValiancy",
    "Itemclass": "Unique",
    "KeyID": "OrderofValiancy",
    "Lock": false,
    "Name": "勇猛标志",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Equip (62)"
  },
  "PoisonousBottle": {
    "Description": "添加痛苦减益的技能费用减少 1 点。",
    "EquipSkill": [],
    "Equip_Script": "PoisonousBottle",
    "Itemclass": "Unique",
    "KeyID": "PoisonousBottle",
    "Lock": false,
    "Name": "毒药瓶",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Equip (60)"
  },
  "PrayersHand": {
    "Description": "",
    "EquipSkill": [],
    "Equip_Script": "PrayersHand",
    "Itemclass": "UnCommon",
    "KeyID": "PrayersHand",
    "Lock": false,
    "Name": "祈愿之手",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Equip (47)"
  },
  "PrismStick": {
    "Description": "给敌人赋予干扰减益<sprite=2>时，给目标造成相当于自身最大体力值40%的伤害。",
    "EquipSkill": [],
    "Equip_Script": "PrismStick",
    "Itemclass": "Unique",
    "KeyID": "PrismStick",
    "Lock": true,
    "Name": "奇迹♬ KIRA☆KIRA☆ 棱镜棒",
    "NoDrop": false,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Prism stick"
  },
  "PyonHammer": {
    "Description": "对嘲讽目标造成的伤害增加40%。",
    "EquipSkill": [],
    "Equip_Script": "PyonHammer",
    "Itemclass": "Legendary",
    "KeyID": "PyonHammer",
    "Lock": true,
    "Name": "砰~☆充气锤",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": true,
    "TimeMoneyPrice": 0,
    "image": "MomoriEquip"
  },
  "RabbitMask": {
    "Description": "附加随机属性及高级附魔。\n 装备后无法解除。",
    "EquipSkill": [],
    "Equip_Script": "RabbitMask",
    "Itemclass": "Rare",
    "KeyID": "RabbitMask",
    "Lock": false,
    "Name": "多多的兔子面具",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "RabbitMask"
  },
  "Rapier": {
    "Description": "",
    "EquipSkill": [],
    "Equip_Script": "Rapier",
    "Itemclass": "Rare",
    "KeyID": "Rapier",
    "Lock": false,
    "Name": "双刃剑",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Equip (48)"
  },
  "RemialPaint": {
    "Description": "所有队员根据其职业攻击力+1、治疗力+1、防御力+5%。\n 当我的当前体力值超过 20% 时，每回合受到最多体力值的 20% 的<sprite=1>伤害。",
    "EquipSkill": [],
    "Equip_Script": "RemialPaint",
    "Itemclass": "Unique",
    "KeyID": "RemialPaint",
    "Lock": true,
    "Name": "不可名状的画",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "RemialPaint"
  },
  "Replica": {
    "Description": "战斗开始时，复制自身穿戴的其它道具的效果。",
    "EquipSkill": [],
    "Equip_Script": "Replica",
    "Itemclass": "Legendary",
    "KeyID": "Replica",
    "Lock": true,
    "Name": "复制人",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": true,
    "TimeMoneyPrice": 0,
    "image": "Replica"
  },
  "ReportersFootprint": {
    "Description": "<color=#919191>以下是乔伊留下的说明书 \n （内容大概是说战斗中有额外效果）</color>",
    "EquipSkill": [],
    "Equip_Script": "RepotersFootprint",
    "Itemclass": "Unique",
    "KeyID": "ReportersFootprint",
    "Lock": true,
    "Name": "乔伊的神秘粉末",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Equip (66)"
  },
  "Revenger": {
    "Description": "受到 2 次攻击时反击（66% 攻击力）。\n \n <color=#919191>血债血偿！ - 莉安</color>",
    "EquipSkill": [],
    "Equip_Script": "Revenger",
    "Itemclass": "Legendary",
    "KeyID": "Revenger",
    "Lock": true,
    "Name": "复仇者",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": true,
    "TimeMoneyPrice": 0,
    "image": "Revenger"
  },
  "RingofAngel": {
    "Description": "",
    "EquipSkill": [],
    "Equip_Script": "RingofAngel",
    "Itemclass": "Legendary",
    "KeyID": "RingofAngel",
    "Lock": true,
    "Name": "天使之环",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Equip (71)"
  },
  "RingofBanalman": {
    "Description": "",
    "EquipSkill": [],
    "Equip_Script": "RingofBanalman",
    "Itemclass": "UnCommon",
    "KeyID": "RingofBanalman",
    "Lock": false,
    "Name": "囚犯的戒指",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Equip (42)"
  },
  "RingofBlood": {
    "Description": "",
    "EquipSkill": [],
    "Equip_Script": "RingofBlood",
    "Itemclass": "Rare",
    "KeyID": "RingofBlood",
    "Lock": false,
    "Name": "狂战士的戒指",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Equip (56)"
  },
  "RingofDeath": {
    "Description": "",
    "EquipSkill": [],
    "Equip_Script": "RingofDeath",
    "Itemclass": "Rare",
    "KeyID": "RingofDeath",
    "Lock": false,
    "Name": "刺客的戒指",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Equip (51)"
  },
  "RingofFugitive": {
    "Description": "",
    "EquipSkill": [],
    "Equip_Script": "RingofFugitive",
    "Itemclass": "UnCommon",
    "KeyID": "RingofFugitive",
    "Lock": false,
    "Name": "逃亡者的戒指",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Equip (41)"
  },
  "RingofGambler": {
    "Description": "",
    "EquipSkill": [],
    "Equip_Script": "RingofGambler",
    "Itemclass": "UnCommon",
    "KeyID": "RingofGambler",
    "Lock": false,
    "Name": "赌徒的戒指",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Equip (25)"
  },
  "RingofHunt": {
    "Description": "",
    "EquipSkill": [],
    "Equip_Script": "RingofHunt",
    "Itemclass": "Rare",
    "KeyID": "RingofHunt",
    "Lock": false,
    "Name": "猎人的戒指",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Equip (55)"
  },
  "RingofMedia": {
    "Description": "",
    "EquipSkill": [],
    "Equip_Script": "RingofMedia",
    "Itemclass": "Rare",
    "KeyID": "RingofMedia",
    "Lock": false,
    "Name": "驿使的戒指",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Equip (52)"
  },
  "RingofStupidman": {
    "Description": "",
    "EquipSkill": [],
    "Equip_Script": "RingofStupidman",
    "Itemclass": "UnCommon",
    "KeyID": "RingofStupidman",
    "Lock": false,
    "Name": "守护者的戒指",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Equip (43)"
  },
  "RoseArmor": {
    "Description": "",
    "EquipSkill": [],
    "Equip_Script": "RoseArmor",
    "Itemclass": "Rare",
    "KeyID": "RoseArmor",
    "Lock": false,
    "Name": "玫瑰铠甲",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Equip (26)"
  },
  "RoseBadge": {
    "Description": "",
    "EquipSkill": [],
    "Equip_Script": "RoseBadge",
    "Itemclass": "Common",
    "KeyID": "RoseBadge",
    "Lock": false,
    "Name": "玫瑰徽章",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Equip (36)"
  },
  "RustyHammer": {
    "Description": "",
    "EquipSkill": [],
    "Equip_Script": "RustyHammer",
    "Itemclass": "Rare",
    "KeyID": "RustyHammer",
    "Lock": 0,
    "Name": "生锈的铁锤",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": 0,
    "TimeMoneyPrice": 0,
    "image": "Equip (50)"
  },
  "Rustydagger": {
    "Description": "",
    "EquipSkill": [],
    "Equip_Script": "Rustydagger",
    "Itemclass": "UnCommon",
    "KeyID": "Rustydagger",
    "Lock": 0,
    "Name": "生锈的短剑",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": 0,
    "TimeMoneyPrice": 0,
    "image": "Equip (29)"
  },
  "SacredNecklace": {
    "Description": "主动释放自己的治疗技能时，40% 概率可以重复使用。",
    "EquipSkill": [],
    "Equip_Script": "SacredNecklace",
    "Itemclass": "Unique",
    "KeyID": "SacredNecklace",
    "Lock": true,
    "Name": "神圣项链",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Equip (6)"
  },
  "SafetyPrayAmulet": {
    "Description": "",
    "EquipSkill": [],
    "Equip_Script": "SafetyPrayAmulet",
    "Itemclass": "UnCommon",
    "KeyID": "SafetyPrayAmulet",
    "Lock": false,
    "Name": "平安祈愿符咒",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Equip (45)"
  },
  "ScalesArmor": {
    "Description": "每当回合开始时，获得持续一回合的 9 点保护罩。",
    "EquipSkill": [],
    "Equip_Script": "ScalesArmor",
    "Itemclass": "Unique",
    "KeyID": "ScalesArmor",
    "Lock": false,
    "Name": "鳞甲",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "ScalesArmor"
  },
  "SceptreofLife": {
    "Description": "",
    "EquipSkill": [],
    "Equip_Script": "SceptreofLife",
    "Itemclass": "Rare",
    "KeyID": "SceptreofLife",
    "Lock": false,
    "Name": "生命石权杖",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Equip (53)"
  },
  "ShieldBadge": {
    "Description": "",
    "EquipSkill": [],
    "Equip_Script": "ShieldBadge",
    "Itemclass": "Common",
    "KeyID": "ShieldBadge",
    "Lock": false,
    "Name": "盾牌徽章",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Equip (39)"
  },
  "ShieldBreaker_Spear": {
    "Description": "对嘲讽目标造成的伤害增加33%。",
    "EquipSkill": [],
    "Equip_Script": "ShieldBreaker_Spear",
    "Itemclass": "Unique",
    "KeyID": "ShieldBreaker_Spear",
    "Lock": false,
    "Name": "盾牌破坏者",
    "NoDrop": false,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Spear"
  },
  "Slipper": {
    "Description": "",
    "EquipSkill": [],
    "Equip_Script": "Slipper",
    "Itemclass": "Common",
    "KeyID": "Slipper",
    "Lock": false,
    "Name": "拖鞋",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Equip (22)"
  },
  "StarRing": {
    "Description": "",
    "EquipSkill": [],
    "Equip_Script": "StarRing",
    "Itemclass": "UnCommon",
    "KeyID": "StarRing",
    "Lock": false,
    "Name": "星戒",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Equip (18)"
  },
  "Stellarhand": {
    "Description": "使用 1 费以上技能造成伤害时，给目标施加命中率 -5%，暴击率 -5%(<sprite=0>90%)的减益。\n 成功率根据装备角色的弱化减益成功率增加。",
    "EquipSkill": [],
    "Equip_Script": "StellarHand",
    "Itemclass": "Unique",
    "KeyID": "Stellarhand",
    "Lock": true,
    "Name": "星之手",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "StellarHand"
  },
  "StickofFaith": {
    "Description": "装备角色为支援型角色时，装备的治疗力、攻击力数值互换。\n \n <color=#919191>要是再被我发现拿它去打棒球，就让你到我的房间去忏悔！ - 普瑞斯特</color>",
    "EquipSkill": [],
    "Equip_Script": "StickofFaith",
    "Itemclass": "Unique",
    "KeyID": "StickofFaith",
    "Lock": true,
    "Name": "信仰法棒",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": true,
    "TimeMoneyPrice": 0,
    "image": "StickofFaith"
  },
  "StraightFlush": {
    "Description": "回合结束时，若手中有装备角色的 5 个各不相同的技能，则弃掉这些技能，将“命运”技能拿到手中。",
    "EquipSkill": [],
    "Equip_Script": "StraightFlush",
    "Itemclass": "Legendary",
    "KeyID": "StraightFlush",
    "Lock": true,
    "Name": "同花顺",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Equip (82)"
  },
  "SunCape": {
    "Description": "",
    "EquipSkill": [],
    "Equip_Script": "SunCape",
    "Itemclass": "UnCommon",
    "KeyID": "SunCape",
    "Lock": false,
    "Name": "太阳斗篷",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Equip (15)"
  },
  "Sunmoonstarcurse": {
    "Description": "将受到随机诅咒，即使有诅咒也可以解除装备。\n 该道具的诅咒无法解除。\n 若在装备过程中活着击杀BOSS，将变成<color=#FF24E3FF>英雄品质</color>的装备道具。",
    "EquipSkill": [],
    "Equip_Script": "Sunmoonstarcurse",
    "Itemclass": "Common",
    "KeyID": "Sunmoonstarcurse",
    "Lock": true,
    "Name": "日月星的诅咒",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": true,
    "TimeMoneyPrice": 0,
    "image": "SunmoonItem"
  },
  "Sunmoonstarcurse_Quest": {
    "Description": "将受到特定诅咒，即使有诅咒也可以解除装备。\n 该道具的诅咒无法解除。\n 若在装备过程中活着击杀3只BOSS，将变成 <color=#FF24E3FF>英雄品质</color>的装备道具。\n <b>已击杀&a只。</b>",
    "EquipSkill": [],
    "Equip_Script": "Sunmoonstarcurse_Quest",
    "Itemclass": "Common",
    "KeyID": "Sunmoonstarcurse_Quest",
    "Lock": true,
    "Name": "日月星的诅咒：商店主人版本",
    "NoDrop": 0,
    "Off": true,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "SunmoonItem"
  },
  "SweetPotato": {
    "Description": "<color=#919191>- 甘薯要烤熟才好吃</color>",
    "EquipSkill": [],
    "Equip_Script": "SweetPotato",
    "Itemclass": "Unique",
    "KeyID": "SweetPotato",
    "Lock": true,
    "Name": "甘薯",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "SweetPotato_0"
  },
  "SweetPotato_0": {
    "Description": "战斗结束时，恢复最大体力值的 20%。",
    "EquipSkill": [],
    "Equip_Script": "SweetPotato_0",
    "Itemclass": "Unique",
    "KeyID": "SweetPotato_0",
    "Lock": false,
    "Name": "半生不熟的蓝色甘薯",
    "NoDrop": 0,
    "Off": true,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "SweetPotato_1"
  },
  "SweetPotato_1": {
    "Description": "战斗结束时，恢复最大体力值的 40%。",
    "EquipSkill": [],
    "Equip_Script": "SweetPotato_1",
    "Itemclass": "Legendary",
    "KeyID": "SweetPotato_1",
    "Lock": false,
    "Name": "完全烤熟的蓝色甘薯",
    "NoDrop": 0,
    "Off": true,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "SweetPotato_2"
  },
  "SwordOfStar": {
    "Description": "向敌人释放干扰减益或弱化减益技能时，给目标造成相当于自身体力值 40% 的额外伤害。",
    "EquipSkill": [],
    "Equip_Script": "SwordOfStar",
    "Itemclass": "Legendary",
    "KeyID": "SwordOfStar",
    "Lock": true,
    "Name": "星之剑",
    "NoDrop": true,
    "Off": true,
    "SpecialUnlock": true,
    "TimeMoneyPrice": 0,
    "image": "SweetPotato_0"
  },
  "Taegeukring": {
    "Description": "",
    "EquipSkill": [],
    "Equip_Script": "Taegeukring",
    "Itemclass": "Rare",
    "KeyID": "Taegeukring",
    "Lock": false,
    "Name": "太极戒指",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Taegeukring"
  },
  "TargetBadge": {
    "Description": "",
    "EquipSkill": [],
    "Equip_Script": "TargetBadge",
    "Itemclass": "Common",
    "KeyID": "TargetBadge",
    "Lock": false,
    "Name": "靶子徽章",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Equip (38)"
  },
  "Tequila": {
    "Description": "战斗开始后第一回合免疫所有减益。",
    "EquipSkill": [],
    "Equip_Script": "Tequila",
    "Itemclass": "Unique",
    "KeyID": "Tequila",
    "Lock": true,
    "Name": "血色龙舌兰",
    "NoDrop": true,
    "Off": false,
    "SpecialUnlock": true,
    "TimeMoneyPrice": 0,
    "image": "Tequila"
  },
  "TheEquability": {
    "Description": "当濒死状态的友军成为敌人的单体攻击目标时，可以代替友军受到攻击。\n <color=#919191>-如果装备的是那只“鸟”，则不会触发。</color>",
    "EquipSkill": [],
    "Equip_Script": "TheEquability",
    "Itemclass": "Unique",
    "KeyID": "TheEquability",
    "Lock": true,
    "Name": "守护者的领带",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Equip (64)"
  },
  "ThePressure": {
    "Description": "战斗中抵达黑色迷雾时，受到 2 倍的迷雾伤害，在战斗结束前无法使用该装备的属性效果。",
    "EquipSkill": [],
    "Equip_Script": "ThePressure",
    "Itemclass": "Unique",
    "KeyID": "ThePressure",
    "Lock": true,
    "Name": "破灭之石",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Equip (65)"
  },
  "ThrowingDagger": {
    "Description": "",
    "EquipSkill": [],
    "Equip_Script": "ThrowingDagger",
    "Itemclass": "Rare",
    "KeyID": "ThrowingDagger",
    "Lock": false,
    "Name": "投掷短剑",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Equip (27)"
  },
  "Vadzerald": {
    "Description": "回合结束时，装备角色手中的一个技能费用增加 1 点。",
    "EquipSkill": [],
    "Equip_Script": "Vadzerald",
    "Itemclass": "Unique",
    "KeyID": "Vadzerald",
    "Lock": false,
    "Name": "贝斯拉德",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Equip (9)"
  },
  "VikingsBlood": {
    "Description": "攻击时造成伤害的 15% 转化为体力值",
    "EquipSkill": [],
    "Equip_Script": "VikingsBlood",
    "Itemclass": "Unique",
    "KeyID": "VikingsBlood",
    "Lock": false,
    "Name": "狂战士之血",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Equip (68)"
  },
  "VikingsMace": {
    "Description": "",
    "EquipSkill": [],
    "Equip_Script": "VikingsMace",
    "Itemclass": "Rare",
    "KeyID": "VikingsMace",
    "Lock": false,
    "Name": "狂战士的铁锤",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Equip (34)"
  },
  "WhitePriestCloth": {
    "Description": "可以将<b>指向单一敌人</b>的攻击技能释放给友军。\n 向友军释放攻击技能时，伤害转换为治疗。",
    "EquipSkill": [],
    "Equip_Script": "WhitePriestCloth",
    "Itemclass": "Unique",
    "KeyID": "WhitePriestCloth",
    "Lock": true,
    "Name": "白色祭司服",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": true,
    "TimeMoneyPrice": 0,
    "image": "priestly clothes"
  },
  "WoodenBat": {
    "Description": "用于击打棒球的木棒",
    "EquipSkill": [],
    "Equip_Script": "WoodenBat",
    "Itemclass": "Common",
    "KeyID": "WoodenBat",
    "Lock": false,
    "Name": "木棒",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Equip (33)"
  },
  "WoodenSword": {
    "Description": "",
    "EquipSkill": [],
    "Equip_Script": "WoodenSword",
    "Itemclass": "Common",
    "KeyID": "WoodenSword",
    "Lock": false,
    "Name": "木剑",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Equip (19)"
  },
  "WoodenSword13": {
    "Description": "",
    "EquipSkill": [],
    "Equip_Script": "WoodenSword13",
    "Itemclass": "Legendary",
    "KeyID": "WoodenSword13",
    "Lock": false,
    "Name": "木剑 +13",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Equip (20)"
  },
  "WrathfulAxe": {
    "Description": "",
    "EquipSkill": [],
    "Equip_Script": "WrathfulAxe",
    "Itemclass": "Rare",
    "KeyID": "WrathfulAxe",
    "Lock": false,
    "Name": "狂怒之斧",
    "NoDrop": 0,
    "Off": false,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "image": "Equip (10)"
  }
}