window.relicdef={
  "505Error": {
    "Description": "升级学习技能时，可额外选择其他调查队员的随机 3 个技能进行学习。",
    "KeyID": "505Error",
    "LastAreaNoDrop": true,
    "LastBattleNoDrop": 0,
    "Lock": true,
    "Name": "505Error",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": 0,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "25",
    "passive_script": "Error505"
  },
  "AlphaBullet": {
    "Description": "第二回合开始触发，每回合第一个从手中释放的技能暴击率增加100%。\n\n<color=#919191>产自枪弹地牢的子弹。</color>",
    "KeyID": "AlphaBullet",
    "LastAreaNoDrop": 0,
    "LastBattleNoDrop": 0,
    "Lock": true,
    "Name": "阿尔法子弹",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": 0,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "AlphaBullet",
    "passive_script": "AlphaBullet"
  },
  "AncientShield": {
    "Description": "战斗开始时，生成防御 7 点伤害的防护墙。\n 每次通过 1 个区域增加 2 点防护值。",
    "KeyID": "AncientShield",
    "LastAreaNoDrop": 0,
    "LastBattleNoDrop": true,
    "Lock": false,
    "Name": "远古盾牌",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "04",
    "passive_script": "AncientShield"
  },
  "AngelsPotion": {
    "Description": "每抽牌13次，解除友军随机1个减益。\n\n<color=#919191>虽然持有时能够获得正面效果，但含有剧毒，喝下去可能会有生命危险。</color>",
    "KeyID": "AngelsPotion",
    "LastAreaNoDrop": 0,
    "LastBattleNoDrop": 0,
    "Lock": false,
    "Name": "天使的药水",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": 0,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "AngelsPotion",
    "passive_script": "AngelsPotion"
  },
  "BattleFlag": {
    "Description": "战斗开始时，所有固定能力获得一次费用减少1点的效果。",
    "KeyID": "BattleFlag",
    "LastAreaNoDrop": false,
    "LastBattleNoDrop": true,
    "Lock": false,
    "Name": "战斗旗帜",
    "NoDrop": false,
    "Off": 0,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "banner of battle",
    "passive_script": "BattleFlag"
  },
  "BlackFlag": {
    "Description": "敌人持有的所有“嘲讽”增益获得“防御力减少10%”的效果。",
    "KeyID": "BlackFlag",
    "LastAreaNoDrop": false,
    "LastBattleNoDrop": 0,
    "Lock": false,
    "Name": "黑色旗帜",
    "NoDrop": false,
    "Off": 0,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "Black flag",
    "passive_script": "BlackFlag"
  },
  "BlackMoon": {
    "Description": "所有减益抵抗增加 15%\n 闪避率增加 3%",
    "KeyID": "BlackMoon",
    "LastAreaNoDrop": 0,
    "LastBattleNoDrop": 0,
    "Lock": false,
    "Name": "黑色月光",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "07",
    "passive_script": "BlackMoon"
  },
  "BlueRose": {
    "Description": "第 3 回合开始时，展示相当于队员数量的所有调查队员的随机稀有技能，选择技能拿到手中。",
    "KeyID": "BlueRose",
    "LastAreaNoDrop": 0,
    "LastBattleNoDrop": 0,
    "Lock": 0,
    "Name": "蓝玫瑰",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": 0,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "16",
    "passive_script": "BlueRose"
  },
  "BonFire": {
    "Description": "所有敌人的体力值增加30%。获得2个传说装备。",
    "KeyID": "BonFire",
    "LastAreaNoDrop": false,
    "LastBattleNoDrop": 0,
    "Lock": true,
    "Name": "篝火探索者",
    "NoDrop": true,
    "Off": true,
    "SpecialUnlock": true,
    "TimeMoneyPrice": 0,
    "Unchangeable": true,
    "image": "Bonfire",
    "passive_script": "BonFire"
  },
  "Bookofmoon": {
    "Description": "战斗时，手中最下面一个技能的伤害量，恢复量增加3点。\n当月亮碎片和太阳碎片都处于激活状态时，手中最上面的一个技能和最下面的一个技能获得迅速。",
    "KeyID": "Bookofmoon",
    "LastAreaNoDrop": 0,
    "LastBattleNoDrop": 0,
    "Lock": true,
    "Name": "月亮碎片",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": true,
    "TimeMoneyPrice": 0,
    "Unchangeable": false,
    "image": "6",
    "passive_script": "Bookofmoon"
  },
  "Bookofsun": {
    "Description": "战斗时，手中最上面一个技能的伤害量，恢复量增加3点。\n当月亮碎片和太阳碎片都处于激活状态时，手中最上面的一个技能和最下面的一个技能获得迅速。",
    "KeyID": "Bookofsun",
    "LastAreaNoDrop": 0,
    "LastBattleNoDrop": 0,
    "Lock": true,
    "Name": "太阳碎片",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": true,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "5",
    "passive_script": "Bookofsun"
  },
  "BottleOfDemons": {
    "Description": "濒死状态时恢复 1 点法力值。\n 每回合仅限触发一次。",
    "KeyID": "BottleOfDemons",
    "LastAreaNoDrop": 0,
    "LastBattleNoDrop": 0,
    "Lock": true,
    "Name": "恶鬼瓶",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": 0,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "BottleOFDemons",
    "passive_script": "BottleOfDemons"
  },
  "BrightShield": {
    "Description": "体力极限处于保护状态时，暴击率增加 60%。",
    "KeyID": "BrightShield",
    "LastAreaNoDrop": 0,
    "LastBattleNoDrop": 0,
    "Lock": true,
    "Name": "光辉盾牌",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": 0,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "1",
    "passive_script": "BrightShield"
  },
  "BrokenArrow": {
    "Description": "技能攻击未命中时，下一个出手的技能费用减少1点。\n一回合仅限触发一次。",
    "KeyID": "BrokenArrow",
    "LastAreaNoDrop": 0,
    "LastBattleNoDrop": 0,
    "Lock": 0,
    "Name": "折断的弓箭",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": 0,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "broken arrow",
    "passive_script": "BrokenArrow"
  },
  "BronzeMotor": {
    "Description": "每当主动释放技能时叠加 1 层层数。\n 叠加 5 层时，所有友军的暴击率增加 50%。\n 回合结束时，所有层数重置。",
    "KeyID": "BronzeMotor",
    "LastAreaNoDrop": 0,
    "LastBattleNoDrop": 0,
    "Lock": true,
    "Name": "青铜电机",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": 0,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "13",
    "passive_script": "BronzeMotor"
  },
  "Bulb": {
    "Description": "一回合内从手中释放2个“战斗开始时不在牌库中的技能”时抽取技能。\n每回合仅限触发1次。\n\n<color=#919191>据说插在某个地方时会变成太阳。</color>",
    "KeyID": "Bulb",
    "LastAreaNoDrop": 0,
    "LastBattleNoDrop": 0,
    "Lock": true,
    "Name": "电灯",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": 0,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "Bulb",
    "passive_script": "Bulb"
  },
  "CCBadge": {
    "Description": "每当解除友军身上的干扰减益时，恢复1点法力值或抽取技能。（1回合1次，效果随机）",
    "KeyID": "CCBadge",
    "LastAreaNoDrop": false,
    "LastBattleNoDrop": 0,
    "Lock": false,
    "Name": "干扰徽章",
    "NoDrop": false,
    "Off": 0,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "Disturbing badge",
    "passive_script": "CCBadge"
  },
  "Candy": {
    "Description": "回合结束时所有友军恢复2点体力值。",
    "KeyID": "Candy",
    "LastAreaNoDrop": 0,
    "LastBattleNoDrop": false,
    "Lock": 0,
    "Name": "棒棒糖",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": 0,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "Candy",
    "passive_script": "Candy"
  },
  "ChaosHourglass": {
    "Description": "回合开始时第一个出手的技能费用变成 0。\n 技能交换次数和速度减 1。",
    "KeyID": "ChaosHourglass",
    "LastAreaNoDrop": false,
    "LastBattleNoDrop": 0,
    "Lock": true,
    "Name": "混沌怀表",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "08",
    "passive_script": "ChaosHourglass"
  },
  "CheeseCake": {
    "Description": "增加所有友军 6 点最大体力值。",
    "KeyID": "CheeseCake",
    "LastAreaNoDrop": 0,
    "LastBattleNoDrop": 0,
    "Lock": 0,
    "Name": "芝士蛋糕",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "Unchangeable": true,
    "image": "22",
    "passive_script": "CheeseCake"
  },
  "Coppercoil": {
    "Description": "受到3点及以上伤害时，伤害减少2点。",
    "KeyID": "Coppercoil",
    "LastAreaNoDrop": 0,
    "LastBattleNoDrop": 0,
    "Lock": 0,
    "Name": "铜线圈",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": 0,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "copper coil",
    "passive_script": "Coppercoil"
  },
  "Crossoflight": {
    "Description": "每当从手中释放 4 次恢复技能后，下一个出手的指向敌人的技能将释放给所有敌人。",
    "KeyID": "Crossoflight",
    "LastAreaNoDrop": 0,
    "LastBattleNoDrop": 0,
    "Lock": true,
    "Name": "闪耀的十字架",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "CrossofLight",
    "passive_script": "Crossoflight"
  },
  "CursedMask": {
    "Description": "从宝箱房间中获得的装备道具将受到诅咒，但道具品质有35%的概率提升一个等级。（最高可提升至<color=purple>英雄品质</color>）",
    "KeyID": "CursedMask",
    "LastAreaNoDrop": true,
    "LastBattleNoDrop": true,
    "Lock": false,
    "Name": "被诅咒的法洛斯假面",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "CursedMask",
    "passive_script": "CursedMask"
  },
  "CuteComputer": {
    "Description": "战斗开始时，不再抽取2个技能，而是随机生成2个抽牌技能。",
    "KeyID": "CuteComputer",
    "LastAreaNoDrop": false,
    "LastBattleNoDrop": true,
    "Lock": true,
    "Name": "小电脑",
    "NoDrop": false,
    "Off": 0,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "29",
    "passive_script": "CuteComputer"
  },
  "DeliciousCarrot": {
    "Description": "从6个露西技能中选择1个学习。\n\n<color=#919191>杏仁杏仁</color>",
    "KeyID": "DeliciousCarrot",
    "LastAreaNoDrop": 0,
    "LastBattleNoDrop": true,
    "Lock": false,
    "Name": "美味胡萝卜",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": 0,
    "TimeMoneyPrice": 0,
    "Unchangeable": true,
    "image": "Carrot",
    "passive_script": "DeliciousCarrot"
  },
  "EndlessSoul": {
    "Description": "击杀敌人时立即获得 1 点法力值。",
    "KeyID": "EndlessSoul",
    "LastAreaNoDrop": 0,
    "LastBattleNoDrop": 0,
    "Lock": true,
    "Name": "无尽的灵魂",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 3,
    "Unchangeable": 0,
    "image": "01",
    "passive_script": "EndlessSoul"
  },
  "FakeCrown": {
    "Description": "战斗第一个回合的技能交换次数增加 4 次。",
    "KeyID": "FakeCrown",
    "LastAreaNoDrop": 0,
    "LastBattleNoDrop": true,
    "Lock": 0,
    "Name": "陶笛",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": 0,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "21",
    "passive_script": "FakeCrown"
  },
  "FlameBullet": {
    "Description": "每当施加2次追加攻击或反击时触发以下效果\n赋予目标持续3回合的痛苦减益，每回合造成3点痛苦伤害（1/5，<sprite=1>110%）。",
    "KeyID": "FlameBullet",
    "LastAreaNoDrop": 0,
    "LastBattleNoDrop": 0,
    "Lock": true,
    "Name": "爆炎弹",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": 0,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "FlameBullet",
    "passive_script": "FlameBullet"
  },
  "FlameOilBarrel": {
    "Description": "敌人身上的每1层弱化减益将对自身造成每回合4点的痛苦伤害。",
    "KeyID": "FlameOilBarrel",
    "LastAreaNoDrop": false,
    "LastBattleNoDrop": 0,
    "Lock": false,
    "Name": "火焰汽油桶",
    "NoDrop": false,
    "Off": 0,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "Flame oil can",
    "passive_script": "FlameOilBarrel"
  },
  "FrozenDebt": {
    "Description": "战斗开始时牌库中所有费用为 1 的技能伤害增加 5 点。",
    "KeyID": "FrozenDebt",
    "LastAreaNoDrop": 0,
    "LastBattleNoDrop": 0,
    "Lock": 0,
    "Name": "冰之扇",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": 0,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "FrozenDebt",
    "passive_script": "FrozenDebt"
  },
  "GhostCoin": {
    "Description": "每当敌人的嘲讽状态改变时，敌人受到本次战斗期间防御力减少10%的减益。（最多叠加10层）",
    "KeyID": "GhostCoin",
    "LastAreaNoDrop": 0,
    "LastBattleNoDrop": 0,
    "Lock": true,
    "Name": "幽灵硬币",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": 0,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "GhostCoin",
    "passive_script": "GhostCoin"
  },
  "Goldleaves": {
    "Description": "每结束两个回合，重复释放最后一个出手的技能。\n*不包括无法战斗的友军技能、露西技能和稀有技能。\n\n<color=#919191>金刺猬的叶子，是非常罕见的稀有物品</color>",
    "KeyID": "Goldleaves",
    "LastAreaNoDrop": 0,
    "LastBattleNoDrop": 0,
    "Lock": true,
    "Name": "金叶子",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": true,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "GoldLeaves",
    "passive_script": "Goldleaves"
  },
  "GolemRelic": {
    "Description": "每两个回合给随机一个技能附加强化模块。",
    "KeyID": "GolemRelic",
    "LastAreaNoDrop": 0,
    "LastBattleNoDrop": 0,
    "Lock": true,
    "Name": "石魔核反应堆",
    "NoDrop": true,
    "Off": 0,
    "SpecialUnlock": true,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "Item (2)",
    "passive_script": "GolemRelic"
  },
  "HealingLantern": {
    "Description": "每次击杀敌人时，所有濒死状态的友军体力值恢复至1点。",
    "KeyID": "HealingLantern",
    "LastAreaNoDrop": false,
    "LastBattleNoDrop": 0,
    "Lock": true,
    "Name": "治愈灯火",
    "NoDrop": false,
    "Off": 0,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "Healing lamp",
    "passive_script": "HealingLantern"
  },
  "HeavyJewelryBox": {
    "Description": "背包格子数 - 8\n遗物展示台格子数 + 2\n装备时获得1个遗物袋。",
    "KeyID": "HeavyJewelryBox",
    "LastAreaNoDrop": false,
    "LastBattleNoDrop": true,
    "Lock": true,
    "Name": "沉重的宝石箱",
    "NoDrop": false,
    "Off": 0,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "Unchangeable": true,
    "image": "Heavy jewel box",
    "passive_script": "HeavyJewelryBox"
  },
  "HipSack": {
    "Description": "战斗开始时额外抽取一个技能。\n在战斗中牌库洗牌时，若需要洗牌的技能数为20及以上，则额外抽取一个技能。",
    "KeyID": "HipSack",
    "LastAreaNoDrop": 0,
    "LastBattleNoDrop": 0,
    "Lock": 0,
    "Name": "腰包",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": 0,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "24",
    "passive_script": "HipSack"
  },
  "Holycross": {
    "Description": "获得保护罩增益时，额外获得9点保护罩。\n每回合仅限触发1次。",
    "KeyID": "Holycross",
    "LastAreaNoDrop": 0,
    "LastBattleNoDrop": 0,
    "Lock": false,
    "Name": "圣十字架",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": 0,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "HolyCross",
    "passive_script": "Holycross"
  },
  "JokerCard": {
    "Description": "释放时在牌库中生成“小丑牌”，并抽取技能，将对于敌人的 <sprite=1> 痛苦、<sprite=2>干扰、<sprite=0>弱化减益，每一种减益附加 15 点伤害的“小丑牌”放入牌库。",
    "KeyID": "JokerCard",
    "LastAreaNoDrop": 0,
    "LastBattleNoDrop": true,
    "Lock": true,
    "Name": "小丑牌",
    "NoDrop": true,
    "Off": false,
    "SpecialUnlock": true,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "JokerCard",
    "passive_script": "JokerCard"
  },
  "LastFlame": {
    "Description": "无法战斗抵抗增加 33%。\n 当友军受到致命伤害时，体力值恢复至 10 点。\n 该效果只触发一次。",
    "KeyID": "LastFlame",
    "LastAreaNoDrop": 0,
    "LastBattleNoDrop": 0,
    "Lock": false,
    "Name": "最后的火花",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "Unchangeable": false,
    "image": "05",
    "passive_script": "LastFlame"
  },
  "Librariansjournal": {
    "Description": "所有道具将处于已鉴定状态。\n获得1个诅咒解除卷轴。\n遗物展示台的最大格子数+1。",
    "KeyID": "Librariansjournal",
    "LastAreaNoDrop": true,
    "LastBattleNoDrop": true,
    "Lock": true,
    "Name": "史书日志",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "Unchangeable": true,
    "image": "2",
    "passive_script": "Librariansjournal"
  },
  "LostResearchJournal": {
    "Description": "一次战斗中，每使用2次药水，随机获得1个药水。",
    "KeyID": "LostResearchJournal",
    "LastAreaNoDrop": 0,
    "LastBattleNoDrop": 0,
    "Lock": true,
    "Name": "丢失的研究日志",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "Unchangeable": false,
    "image": "4",
    "passive_script": "LostResearchJournal"
  },
  "MagicBerry": {
    "Description": "回合开始时给所有敌人赋予受到暴击率增加 5% 的弱化减益(<sprite=0> 400%)。 \n已持有该减益的目标无法重复获得。",
    "KeyID": "MagicBerry",
    "LastAreaNoDrop": 0,
    "LastBattleNoDrop": 0,
    "Lock": 0,
    "Name": "魔法草莓",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": 0,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "11",
    "passive_script": "MagicBerry"
  },
  "MagicCrystal": {
    "Description": "第三回合开始时，手中所有技能的费用减少1点。",
    "KeyID": "MagicCrystal",
    "LastAreaNoDrop": false,
    "LastBattleNoDrop": 0,
    "Lock": false,
    "Name": "魔法水晶",
    "NoDrop": false,
    "Off": 0,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "Magic Crystal",
    "passive_script": "MagicCrystal"
  },
  "MagicLamp": {
    "Description": "回合结束时如果有剩余法力值，随机队员释放随机技能。",
    "KeyID": "MagicLamp",
    "LastAreaNoDrop": 0,
    "LastBattleNoDrop": 0,
    "Lock": true,
    "Name": "法术灯",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "Magiclamp",
    "passive_script": "Magiclamp"
  },
  "ManaBattery": {
    "Description": "从手中释放 3 费以上技能时，恢复 1 点法力值。\n 每回合仅限一次。",
    "KeyID": "ManaBattery",
    "LastAreaNoDrop": 0,
    "LastBattleNoDrop": 0,
    "Lock": true,
    "Name": "法力电池",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": 0,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "12",
    "passive_script": "ManaBattery"
  },
  "ManaBlaze": {
    "Description": "战斗第一个回合法力值 +2",
    "KeyID": "ManaBlaze",
    "LastAreaNoDrop": 0,
    "LastBattleNoDrop": true,
    "Lock": false,
    "Name": "魔法炫光",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "02",
    "passive_script": "ManaBlaze"
  },
  "ManaLock": {
    "Description": "当手中的技能费用大于3点时，将该技能的费用减少至3点。",
    "KeyID": "ManaLock",
    "LastAreaNoDrop": 0,
    "LastBattleNoDrop": 0,
    "Lock": true,
    "Name": "魔力锁",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": 0,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "Mana Lock",
    "passive_script": "ManaLock"
  },
  "Markofdeath": {
    "Description": "每当从手中释放10个技能时，下一个技能的伤害量及恢复量+80%。",
    "KeyID": "Markofdeath",
    "LastAreaNoDrop": 0,
    "LastBattleNoDrop": 0,
    "Lock": true,
    "Name": "死亡秘纹",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": true,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "MarkofDeath",
    "passive_script": "Markofdeath"
  },
  "Maskofthesun": {
    "Description": "每结束两个回合，复制并释放手中的随机技能。\n*不包含露西技能和稀有技能\n\n<color=#919191>“您好！我是程序法师。”——神秘的假面带着空虚的笑容说道。</color>",
    "KeyID": "Maskofthesun",
    "LastAreaNoDrop": 0,
    "LastBattleNoDrop": 0,
    "Lock": true,
    "Name": "太阳假面",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": 0,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "MaskoftheSun",
    "passive_script": "Maskofthesun"
  },
  "Memoryfragment": {
    "Description": "每当主动释放露西技能时，手中随机技能费用在本回合期间减少 1 点。\n无法使用此效果减少露西技能的费用。",
    "KeyID": "Memoryfragment",
    "LastAreaNoDrop": 0,
    "LastBattleNoDrop": 0,
    "Lock": true,
    "Name": "记忆碎片",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": 0,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "9",
    "passive_script": "Memoryfragment"
  },
  "Meteorite": {
    "Description": "若回合开始时第一个抽取的技能费用大于2点，则将该技能的费用变为0点，并再抽取一个技能。",
    "KeyID": "Meteorite",
    "LastAreaNoDrop": 0,
    "LastBattleNoDrop": 0,
    "Lock": true,
    "Name": "魔力陨星",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": 0,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "Mana meteor",
    "passive_script": "Meteorite"
  },
  "Milk": {
    "Description": "使用固定能力时，恢复使用固定能力的友军8点体力值，每回合仅限一次。",
    "KeyID": "Milk",
    "LastAreaNoDrop": false,
    "LastBattleNoDrop": 0,
    "Lock": true,
    "Name": "牛奶",
    "NoDrop": true,
    "Off": 0,
    "SpecialUnlock": true,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "26",
    "passive_script": "Milk"
  },
  "MindsEye": {
    "Description": "消除所有友军的命中率上限，降低所有敌人的命中率上限至 90%。",
    "KeyID": "MindsEye",
    "LastAreaNoDrop": 0,
    "LastBattleNoDrop": 0,
    "Lock": true,
    "Name": "心之眼",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": true,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "MindsEye",
    "passive_script": "MindsEye"
  },
  "MistTotem": {
    "Description": "到达黑色迷雾的回合时，所有友军恢复体力极限，且体力极限受到保护。",
    "KeyID": "MistTotem",
    "LastAreaNoDrop": 0,
    "LastBattleNoDrop": true,
    "Lock": 0,
    "Name": "迷雾图腾",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": 0,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "17",
    "passive_script": "MistTotem"
  },
  "NewPassive8": {
    "Description": "回合开始时若处于濒死状态则恢复20点体力值。非濒死状态则受到3点痛苦伤害。",
    "KeyID": "NewPassive8",
    "LastAreaNoDrop": false,
    "LastBattleNoDrop": 0,
    "Lock": true,
    "Name": "新遗物8",
    "NoDrop": true,
    "Off": true,
    "SpecialUnlock": true,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "SweetPotato_0",
    "passive_script": "NewPassive8"
  },
  "Obsidian": {
    "Description": "触发暴击时，下一个出手的技能发生暴击。（2回合触发1次）",
    "KeyID": "Obsidian",
    "LastAreaNoDrop": 0,
    "LastBattleNoDrop": 0,
    "Lock": true,
    "Name": "黑曜石",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": 0,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "obsidian",
    "passive_script": "Obsidian"
  },
  "OldHourglass": {
    "Description": "速度+3",
    "KeyID": "OldHourglass",
    "LastAreaNoDrop": true,
    "LastBattleNoDrop": 0,
    "Lock": true,
    "Name": "古老的怀表",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "OldHourglass",
    "passive_script": "OldHourglass"
  },
  "OldRule": {
    "Description": "招募或已经存在第4位队员触发。\n展示所有队员的所有专属技能，可选择学习其中2个技能。",
    "KeyID": "OldRule",
    "LastAreaNoDrop": false,
    "LastBattleNoDrop": true,
    "Lock": false,
    "Name": "古老的英雄徽章",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 3,
    "Unchangeable": true,
    "image": "03",
    "passive_script": "OldRule"
  },
  "PM_Draw_0": {
    "Description": "每当从手中释放5个技能时，抽取1个技能。",
    "KeyID": "PM_Draw_0",
    "LastAreaNoDrop": 0,
    "Lock": false,
    "Name": "坚韧的意志",
    "NoDrop": true,
    "Off": true,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "",
    "passive_script": "PM_Draw_0"
  },
  "PM_Draw_1": {
    "Description": "每次从牌库中抽取4个技能时，额外抽取1个技能。",
    "KeyID": "PM_Draw_1",
    "LastAreaNoDrop": 0,
    "Lock": 0,
    "Name": "满腔的意志",
    "NoDrop": true,
    "Off": true,
    "SpecialUnlock": 0,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "",
    "passive_script": "PM_Draw_1"
  },
  "PM_Mana_0": {
    "Description": "每当友军陷入濒死状态时，恢复2点法力值并抽取1个技能。",
    "KeyID": "PM_Mana_0",
    "LastAreaNoDrop": 0,
    "Lock": 0,
    "Name": "为了伙伴",
    "NoDrop": true,
    "Off": true,
    "SpecialUnlock": 0,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "Bonfire",
    "passive_script": "PM_Mana_0"
  },
  "PM_Mana_1": {
    "Description": "每当抽取4个技能时，恢复1点法力值。",
    "KeyID": "PM_Mana_1",
    "LastAreaNoDrop": 0,
    "Lock": 0,
    "Name": "不屈之心",
    "NoDrop": true,
    "Off": true,
    "SpecialUnlock": 0,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "",
    "passive_script": "PM_Mana_1"
  },
  "PM_Mana_2": {
    "Description": "当消耗所有法力值时恢复4点法力值。\n（每回合限1次）",
    "KeyID": "PM_Mana_2",
    "LastAreaNoDrop": 0,
    "Lock": 0,
    "Name": "燃烧的心",
    "NoDrop": true,
    "Off": true,
    "SpecialUnlock": 0,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "",
    "passive_script": "PM_Mana_2"
  },
  "P_Amethyst": {
    "Description": "赋予敌人3次痛苦减益<sprite=1>时恢复1点法力值。\n每回合仅限触发1次。",
    "KeyID": "P_Amethyst",
    "LastAreaNoDrop": 0,
    "LastBattleNoDrop": 0,
    "Lock": true,
    "Name": "紫水晶",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": 0,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "P_Amethyst",
    "passive_script": "P_Amethyst"
  },
  "P_Ruby": {
    "Description": "赋予敌人3次弱化减益<sprite=0>时恢复1点法力值。\n每回合仅限触发1次。",
    "KeyID": "P_Ruby",
    "LastAreaNoDrop": 0,
    "LastBattleNoDrop": 0,
    "Lock": true,
    "Name": "红宝石",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": 0,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "P_Ruby",
    "passive_script": "P_Ruby"
  },
  "P_Topaz": {
    "Description": "赋予敌人2次干扰减益<sprite=2>时恢复1点法力值。\n每回合触发1次。",
    "KeyID": "P_Topaz",
    "LastAreaNoDrop": 0,
    "LastBattleNoDrop": 0,
    "Lock": true,
    "Name": "黄宝石",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": 0,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "P_Topaz",
    "passive_script": "P_Topaz"
  },
  "PainBadge": {
    "Description": "每当解除友军身上的痛苦减益时，恢复4点体力值。",
    "KeyID": "PainBadge",
    "LastAreaNoDrop": false,
    "LastBattleNoDrop": 0,
    "Lock": false,
    "Name": "痛苦徽章",
    "NoDrop": false,
    "Off": 0,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "Pain badge",
    "passive_script": "PainBadge"
  },
  "Palette": {
    "Description": "赋予敌人的持续时间为2回合及以上的痛苦、弱化减益的持续时间增加1回合。",
    "KeyID": "Palette",
    "LastAreaNoDrop": 0,
    "LastBattleNoDrop": 0,
    "Lock": true,
    "Name": "双色调色板",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": 0,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "two-color palette",
    "passive_script": "Palette"
  },
  "PotionBag": {
    "Description": "随机获得 2 个药水。\n药水使用次数+2。\n遗物展示台的最大格子数+1。",
    "KeyID": "PotionBag",
    "LastAreaNoDrop": 0,
    "LastBattleNoDrop": 0,
    "Lock": true,
    "Name": "药水背包",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": 0,
    "TimeMoneyPrice": 0,
    "Unchangeable": true,
    "image": "23",
    "passive_script": "PotionBag"
  },
  "QuickCasting": {
    "Description": "释放有行动倒计时的技能时，根据倒计时抽取相应数量的技能。（最多2个，两回合触发1次）",
    "KeyID": "QuickCasting",
    "LastAreaNoDrop": 0,
    "LastBattleNoDrop": 0,
    "Lock": true,
    "Name": "快速蓄力",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "QuickCasting",
    "passive_script": "QuickCasting"
  },
  "RainbowBrush": {
    "Description": "赋予友军的持续时间为2回合及以上的增益的持续时间增加1回合。",
    "KeyID": "RainbowBrush",
    "LastAreaNoDrop": 0,
    "LastBattleNoDrop": 0,
    "Lock": true,
    "Name": "彩虹画笔",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": 0,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "rainbow brush",
    "passive_script": "RainbowBrush"
  },
  "ReapersTiara": {
    "Description": "展示12个遗物，并选择其中1个获得。\n\n<color=#919191>失礼了，请杀了我吧。</color>",
    "KeyID": "ReapersTiara",
    "LastAreaNoDrop": 0,
    "LastBattleNoDrop": false,
    "Lock": true,
    "Name": "死神之冠",
    "NoDrop": false,
    "Off": 0,
    "SpecialUnlock": true,
    "TimeMoneyPrice": 0,
    "Unchangeable": true,
    "image": "ReapersTiara",
    "passive_script": "ReapersTiara"
  },
  "RedBlossoms": {
    "Description": "第 4 回合开始时，将随机一个露西的稀有技能拿到手中。",
    "KeyID": "RedBlossoms",
    "LastAreaNoDrop": 0,
    "LastBattleNoDrop": 0,
    "Lock": false,
    "Name": "红色樱花",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": 0,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "20",
    "passive_script": "RedBlossoms"
  },
  "RelicBox": {
    "Description": "战斗开始时，在空余的遗物栏上添加随机遗物。（不包括无法回收的遗物）",
    "KeyID": "RelicBox",
    "LastAreaNoDrop": 0,
    "LastBattleNoDrop": true,
    "Lock": true,
    "Name": "遗物箱",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": 0,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "Relics box",
    "passive_script": "RelicBox"
  },
  "Revolvercylinder": {
    "Description": "追加攻击、反击的伤害增加3点。",
    "KeyID": "Revolvercylinder",
    "LastAreaNoDrop": 0,
    "LastBattleNoDrop": 0,
    "Lock": false,
    "Name": "旋转弹膛",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": 0,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "RevolverCylinder",
    "passive_script": "Revolvercylinder"
  },
  "SapPack": {
    "Description": "脱离濒死状态时所有友军恢复4点体力值。（每回合触发1次）",
    "KeyID": "SapPack",
    "LastAreaNoDrop": false,
    "LastBattleNoDrop": 0,
    "Lock": false,
    "Name": "输液袋",
    "NoDrop": false,
    "Off": 0,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "Pack",
    "passive_script": "SapPack"
  },
  "SecretWreath": {
    "Description": "帮助探索地图的秘密。",
    "KeyID": "SecretWreath",
    "LastAreaNoDrop": true,
    "LastBattleNoDrop": true,
    "Lock": true,
    "Name": "神秘花环",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 3,
    "Unchangeable": 0,
    "image": "SecretWreath",
    "passive_script": "SecretWreath"
  },
  "ShadowOrb": {
    "Description": "若手中的技能少于3个，从手中释放技能时从牌库中抽取技能。\n \n <color=#919191>正式名称是“暗黑阴影黑檀珠“。</color>",
    "KeyID": "ShadowOrb",
    "LastAreaNoDrop": 0,
    "LastBattleNoDrop": 0,
    "Lock": true,
    "Name": "暗影珠",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": true,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "ShadowOrb",
    "passive_script": "ShadowOrb"
  },
  "SharksFin": {
    "Description": "从 5 个紫色品质的装备道具中选择 1 个获得。\n\n<color=#919191>a</color>",
    "KeyID": "SharksFin",
    "LastAreaNoDrop": 0,
    "LastBattleNoDrop": true,
    "Lock": false,
    "Name": "鱼翅",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": 0,
    "TimeMoneyPrice": 0,
    "Unchangeable": true,
    "image": "Sharks",
    "passive_script": "SharksFin"
  },
  "ShineStone": {
    "Description": "消除因黑色迷雾而受到的每回合痛苦伤害及敌人的加速效果。",
    "KeyID": "ShineStone",
    "LastAreaNoDrop": 0,
    "LastBattleNoDrop": true,
    "Lock": false,
    "Name": "闪光石",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "ShineStone",
    "passive_script": "ShineStone"
  },
  "ShiningOrb": {
    "Description": "若手中的技能少于3个，从手中释放1费以上技能时恢复1点法力值\n\n<color=#919191>正式名称是“晶莹璀璨白玉珠”。</color>",
    "KeyID": "ShiningOrb",
    "LastAreaNoDrop": 0,
    "LastBattleNoDrop": 0,
    "Lock": true,
    "Name": "莹白珠",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": 0,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "ShiningOrb",
    "passive_script": "ShiningOrb"
  },
  "Sign": {
    "Description": "选择事件时将多 1 个可选项。",
    "KeyID": "Sign",
    "LastAreaNoDrop": true,
    "LastBattleNoDrop": 0,
    "Lock": 0,
    "Name": "罗盘",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": 0,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "18",
    "passive_script": "Sign"
  },
  "SixSixSix": {
    "Description": "抽取露西的诅咒技能时恢复 1 点法力值。\n 正在佩戴受诅咒的装备道具的角色治疗力和攻击力增加 2 点，对无法战斗的抵抗力增加 25%。",
    "KeyID": "SixSixSix",
    "LastAreaNoDrop": 0,
    "LastBattleNoDrop": 0,
    "Lock": true,
    "Name": "666",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": 0,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "8",
    "passive_script": "SixSixSix"
  },
  "SkeletonKey": {
    "Description": "立即获得 5 个钥匙。",
    "KeyID": "SkeletonKey",
    "LastAreaNoDrop": 0,
    "LastBattleNoDrop": true,
    "Lock": false,
    "Name": "骷髅钥匙",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "Unchangeable": true,
    "image": "3",
    "passive_script": "SkeletonKey"
  },
  "Spinyblowfish": {
    "Description": "对敌人造成的<color=purple>痛苦伤害</color>受到暴击率的影响，可能会触发暴击。",
    "KeyID": "Spinyblowfish",
    "LastAreaNoDrop": 0,
    "LastBattleNoDrop": 0,
    "Lock": true,
    "Name": "刺河豚",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": 0,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "Fish",
    "passive_script": "Spinyblowfish"
  },
  "Sunset": {
    "Description": "击杀敌人时，将超额伤害的30%转化为防护墙。",
    "KeyID": "Sunset",
    "LastAreaNoDrop": false,
    "LastBattleNoDrop": 0,
    "Lock": true,
    "Name": "黄昏",
    "NoDrop": true,
    "Off": 0,
    "SpecialUnlock": true,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "27",
    "passive_script": "Sunset"
  },
  "Superconductor": {
    "Description": "点击结束回合时，根据手中的技能数量（10-手中的技能数量）对随机敌人重复造成2点伤害。",
    "KeyID": "Superconductor",
    "LastAreaNoDrop": 0,
    "LastBattleNoDrop": 0,
    "Lock": false,
    "Name": "超导体",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": 0,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "SuperConductor",
    "passive_script": "Superconductor"
  },
  "SurgeStone": {
    "Description": "装备道具不再受到诅咒，道具已附魔的概率增加。",
    "KeyID": "SurgeStone",
    "LastAreaNoDrop": true,
    "LastBattleNoDrop": true,
    "Lock": false,
    "Name": "净化石",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 3,
    "Unchangeable": 0,
    "image": "SurgeStone",
    "passive_script": "SurgeStone"
  },
  "TankRelic": {
    "Description": "战斗中轮到迷雾攻击时，对所有敌人造成 40 点伤害。",
    "KeyID": "TankRelic",
    "LastAreaNoDrop": 0,
    "LastBattleNoDrop": true,
    "Lock": true,
    "Name": "爆竹炮弹",
    "NoDrop": true,
    "Off": 0,
    "SpecialUnlock": true,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "Item (5)",
    "passive_script": "TankRelic"
  },
  "ThornStem": {
    "Description": "赋予敌人无法行动的减益时，将同时赋予下一次所受伤害增加50%的弱化减益。",
    "KeyID": "ThornStem",
    "LastAreaNoDrop": 0,
    "LastBattleNoDrop": 0,
    "Lock": 0,
    "Name": "荆棘藤蔓",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": 0,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "14",
    "passive_script": "ThornStem"
  },
  "TimeStorage": {
    "Description": "结束回合时若有剩余法力值，则在下一回合追加获得相应法力值。\n 但不超过 2 点法力值。",
    "KeyID": "TimeStorage",
    "LastAreaNoDrop": 0,
    "LastBattleNoDrop": 0,
    "Lock": true,
    "Name": "时间仓库",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 5,
    "Unchangeable": 0,
    "image": "TimeStorage",
    "passive_script": "TimeStorage"
  },
  "ToothBottle": {
    "Description": "所有友军的<sprite=1>痛苦减益成功率减少 33%。\n 当敌人<sprite=1>抵抗痛苦减益时，造成相当于痛苦减益的伤害 X 持续回合数的<color=purple>痛苦伤害</color>。",
    "KeyID": "ToothBottle",
    "LastAreaNoDrop": 0,
    "LastBattleNoDrop": 0,
    "Lock": 0,
    "Name": "智齿病",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": 0,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "7",
    "passive_script": "ToothBottle"
  },
  "ToxicBarrel": {
    "Description": "敌人身上的每1层痛苦减益将对自身造成每回合3点的痛苦伤害。",
    "KeyID": "ToxicBarrel",
    "LastAreaNoDrop": 0,
    "LastBattleNoDrop": 0,
    "Lock": false,
    "Name": "毒性油桶",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": 0,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "toxic oil canister",
    "passive_script": "ToxicBarrel"
  },
  "Trailofmadness": {
    "Description": "超出目标体力的伤害将附加到下一个释放技能的伤害/恢复量。（最多50）\n \n <color=#919191>比我弱的人没资格命令我。 - 海因</color>",
    "KeyID": "Trailofmadness",
    "LastAreaNoDrop": 0,
    "LastBattleNoDrop": 0,
    "Lock": true,
    "Name": "癫狂之痕",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": true,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "Trailofmadness",
    "passive_script": "Trailofmadness"
  },
  "Tumble": {
    "Description": "每当释放露西抽牌技能时叠加1层，叠加3层后下一个抽取的技能费用变成0。",
    "KeyID": "Tumble",
    "LastAreaNoDrop": false,
    "LastBattleNoDrop": 0,
    "Lock": true,
    "Name": "风滚草",
    "NoDrop": true,
    "Off": 0,
    "SpecialUnlock": true,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "28",
    "passive_script": "Tumble"
  },
  "TwinsRelic": {
    "Description": "BOSS 对战时，将超量治疗体力值的 50% 并解除所有减益的露西技能添加到牌库中。",
    "KeyID": "TwinsRelic",
    "LastAreaNoDrop": 0,
    "LastBattleNoDrop": true,
    "Lock": true,
    "Name": "净化水晶",
    "NoDrop": true,
    "Off": 0,
    "SpecialUnlock": true,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "Item (4)",
    "passive_script": "TwinsRelic"
  },
  "Twistedlight": {
    "Description": "不会因黑色迷雾或<color=purple>痛苦伤害</color>而导致无法战斗。\n 每次战斗最多触发 4 回。",
    "KeyID": "Twistedlight",
    "LastAreaNoDrop": 0,
    "LastBattleNoDrop": 0,
    "Lock": true,
    "Name": "扭曲之光",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 5,
    "Unchangeable": 0,
    "image": "Twistedlight",
    "passive_script": "Twistedlight"
  },
  "UnknownSeed": {
    "Description": "当有剩余技能交换次数的状态下按下结束回合时，丢弃手中最下面的技能并抽取2个技能。",
    "KeyID": "UnknownSeed",
    "LastAreaNoDrop": 0,
    "LastBattleNoDrop": 0,
    "Lock": true,
    "Name": "神秘的种子",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": 0,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "seed",
    "passive_script": "UnknownSeed"
  },
  "WarlockSkull": {
    "Description": "黑色迷雾的回合减少一半。\n到达黑色迷雾的回合时，所有敌人所受伤害增加25%。",
    "KeyID": "WarlockSkull",
    "LastAreaNoDrop": 0,
    "LastBattleNoDrop": true,
    "Lock": 0,
    "Name": "黑魔法师的骷髅",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": 0,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "10",
    "passive_script": "WarlockSkull"
  },
  "WeaponCase": {
    "Description": "战斗开始时，给所有友军制作第三格装备栏，并随机装备普通~<color=#A3C52FFF>高级</color>品质的装备道具。\n制作的装备属性降低一半，且无速度属性。\n战斗结束时装备栏和装备道具消失。",
    "KeyID": "WeaponCase",
    "LastAreaNoDrop": false,
    "LastBattleNoDrop": true,
    "Lock": true,
    "Name": "武器箱",
    "NoDrop": false,
    "Off": 0,
    "SpecialUnlock": true,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "Weapon case",
    "passive_script": "WeaponCase"
  },
  "WeatherVane": {
    "Description": "每当主动释放8个技能时，恢复1点法力值。",
    "KeyID": "WeatherVane",
    "LastAreaNoDrop": 0,
    "LastBattleNoDrop": 0,
    "Lock": true,
    "Name": "风车",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": 0,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "19",
    "passive_script": "WeatherVane"
  },
  "WhiteMoon": {
    "Description": "所有减益成功率增加 15%\n 命中率增加 3%",
    "KeyID": "WhiteMoon",
    "LastAreaNoDrop": 0,
    "LastBattleNoDrop": 0,
    "Lock": false,
    "Name": "白色月光",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": false,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "06",
    "passive_script": "WhiteMoon"
  },
  "WitchRelic": {
    "Description": "每 2 个回合生成可向敌人释放的“痛苦诅咒”。",
    "KeyID": "WitchRelic",
    "LastAreaNoDrop": 0,
    "LastBattleNoDrop": 0,
    "Lock": true,
    "Name": "魔女的诅咒",
    "NoDrop": true,
    "Off": 0,
    "SpecialUnlock": true,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "Item (3)",
    "passive_script": "WitchRelic"
  },
  "blackRabbit": {
    "Description": "获得之前所有调查中未使用的金币的80%。\n（最多4000金币）\n获得金币后累积的金币将重置。\n累积的金币：&a金币",
    "KeyID": "blackRabbit",
    "LastAreaNoDrop": false,
    "LastBattleNoDrop": true,
    "Lock": true,
    "Name": "黑兔子玩偶",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": true,
    "TimeMoneyPrice": 0,
    "Unchangeable": true,
    "image": "BlackRabbit",
    "passive_script": "blackRabbit"
  },
  "branche": {
    "Description": "回合开始时给所有敌人赋予本次战斗期间每回合造成3点伤害的痛苦减益(<sprite=1>400%)。\n已持有该减益的目标无法重复获得。",
    "KeyID": "branche",
    "LastAreaNoDrop": 0,
    "LastBattleNoDrop": 0,
    "Lock": 0,
    "Name": "枯枝",
    "NoDrop": 0,
    "Off": 0,
    "SpecialUnlock": 0,
    "TimeMoneyPrice": 0,
    "Unchangeable": 0,
    "image": "Branche",
    "passive_script": "branche"
  }
}